### ISSUE TITLE
Arduino sketches do not allow subdirectories for inclusion [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1004]
This is [Issue 1004](http://code.google.com/p/arduino/issues/detail?id=1004) moved from a Google Code project.
Added by 2012-08-10T11:05:20.000Z by [mackatack](http://code.google.com/u/mackatack/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

I have a rather big (open source) project with quite a lot of files that I would like to move to subdirectories within the sketch directory.

for example:

sketch.ino
sketch.h
subdir/sub2/file.h
subdir/sub2/file.cpp
lib/libraryname/lib.h
utils/utilname/util.h

At this moment I cannot include files in subdirectories by using #include "subdir/sub2/file.h" because the files do not get copied to the temporary compilation directory. As a consequence I get the following order while compiling: "error: subdir/file.h: No such file or directory".

It's quite common that source code is split up in different logical folders as the developer sees fit. Please support subdirectories by copying all the files and directories to the compilation directory. The files in the subdirs should then also be able to include files in parent directories; #include "../parent.h" for example.

**Comment by ffissore** [comment]
Fixed since 8e2c3c777ca5db9d5c31862e4bf1934a62d671b3 and available in latest hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by SuperTango** [comment]
This isn't working for me.  (Or i'm doing it wrong...) 

Example code can be found at https://github.com/SuperTango/SubDirTest

In this example, I have a simple sketch that uses a library called "KellyKLS_Serial".  

When the KellyKLS_Serial.cpp and KellyKLS_Serial.h files are in the sketch directory, everything works fine.  (This can be seen by checking out the above repo and using the "lib_in_sketch_dir" tag).

If I move the .cpp and .h files into a directory called "KellyKLS_Serial", the files are copied into the temporary directory properly, but the build fails with the errors:

```Arduino: 1.6.6 (Mac OS X), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

WARNING: Spurious .git folder in 'USB Host Shield Library 2.0' library
sketch/SubDirTest.ino.cpp.o: In function `setup':
/Users/tango/src/Arduino/SubDirTest/SubDirTest.ino:6: undefined reference to `KellyKLS_Serial::init(Stream*)'
sketch/SubDirTest.ino.cpp.o: In function `__static_initialization_and_destruction_0':
/Users/tango/src/Arduino/SubDirTest/SubDirTest.ino:3: undefined reference to `KellyKLS_Serial::KellyKLS_Serial()'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling.
```
(Note, full errors at https://gist.github.com/SuperTango/c9a706fcfe16d7221a07)

this can be seen by checking out the "lib_in_subdir" tag from the repo referenced above.

Note that due to caching, If I built successfully as in the first example, I needed to rebuild the whole thing (i did it by quitting arduino-1.6.6) in order to see the second build fail.

**Comment by ffissore** [comment]
@SuperTango you're right. files are copied but not compiled. I'm working on it

**Comment by ffissore** [comment]
@SuperTango fixed in the hourly builds http://www.arduino.cc/en/Main/Software#hourly. Thank you for the heads up

**Comment by SuperTango** [comment]
Thanks very much!

**Comment by agdl** [comment]
Are you using the right path? you have to specify the folder:

```#include "myFolder/myFile.h"

**Comment by BlueDragonX** [comment]
Is there a good reason this is limited to being in ./src/? This seems unnecessary.
