### ISSUE TITLE
Multiple instances of INADDR_NONE [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1007]
This is [Issue 1007](http://code.google.com/p/arduino/issues/detail?id=1007) moved from a Google Code project.
Added by 2012-08-16T18:20:18.000Z by [sebastia...@gmail.com](http://code.google.com/u/114408990318135178582/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium
### Original description

**What steps will reproduce the problem?**
1. Sketch with two files, each importing (directly or indirectly) IPAddress.h
2. avr-nm -n on the resulting elf (on Windows)

**What is the expected output? What do you see instead?**
Expect only a single instance of INADDR_NONE in .bss section, but multiple are allocated, consuming precious SRAM space (in my case of a bigger piece of software, seven instances).

Note also that IPAddress consumes six bytes, not four, due to the class pointer required for the virtual function.

This is on arduino-1.0.1 under Windows 7.

**Please provide any additional information below.**
Suggest to declare INADDR_NONE extern in IPAddress.h, and to define it in IPAddress.cpp.

**Comment by jindrabasek** [comment]
I can see this bug is still happening even in the latest IPAddress.h version. https://github.com/arduino/Arduino/blob/8385aedc642d6cd76b50ac5167307121007e5045/hardware/arduino/avr/cores/arduino/IPAddress.h#L76

If IPAddress.h is imported/used in multiple files it causes big SRAM space loss.

const IPAddress INADDR_NONE(0,0,0,0); should me marked extern and defined in IPAddress.cpp

**Comment by hachi** [comment]
I just ran across this bug while trying to figure out what was eating all my sram in .data and .bss. Turns out I had about 15 copies of this and at 6 bytes each that's a big chunk.
