### ISSUE TITLE
[Library Manager] Please EasyNextionLibrary new release is not updated on Library Manager

### ISSUE THREAD

**Issue by Seithan** [arduino/Arduino#10090]
Please can you send me a report of what possibly is wrong with the new release? 
The new release is the 1.0.2 and it was released 12 days ago.

https://github.com/Seithan/EasyNextionLibrary/releases/tag/1.0.2

Thank you in advance.

**Comment by per1234** [comment]
The reason is that you didn't update the `version` value in library.properties before making the release:
https://github.com/Seithan/EasyNextionLibrary/blob/1.0.2/library.properties#L2
The Library Manager indexer uses this value for versioning, not the tag name. Since it already had a 1.0.1 version of your library, it ignored your `1.0.2` tag.

I see you have updated the `version` value after creating the `1.0.2` release:
https://github.com/Seithan/EasyNextionLibrary/commit/667b2697cd749b393656f265dfa22b7d7e24b920#diff-ea32f5b85735296fd64b577e91a19607R2

So the way to get Library Manager to pick up the new version of your library is to either make a new release (after updating the library.properties `version` values), or to redo the existing release.
