### ISSUE TITLE
My Libraries not updated in Arduino Library Manager

### ISSUE THREAD

**Issue by Asyasyarif** [arduino/Arduino#10119]
Hello, 

i've released new version in my repo and update library.properties,  but not updated ?
do i wrong ?
https://github.com/Asyasyarif/RFID-Spacecat/releases

thanks.

**Comment by per1234** [comment]
The reason your release was not picked up by the Arduino Library Manager indexer is because you didn't update the `version` value in library.properties before creating the tag/release:
https://github.com/Asyasyarif/RFID-Spacecat/blob/v1.2.3/library.properties#L2

The Library Manager uses the library.properties `version` value for versioning, so any tag that doesn't have a unique `version` value in library.properties is ignored.

I see that you have since updated the library.properties `version` value, so if you were to redo the existing v1.2.3 release, it would be picked up by the Arduino Library Manager indexer. If you don't want to do that, you can create a new release, remembering to update the `version` value first.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
