### ISSUE TITLE
TEE_UC20_Shield in library manager  Do not show the new version 

### ISSUE THREAD

**Issue by ThaiEasyElec** [arduino/Arduino#10163]
The latest version doesn't show up in the library manager.
https://github.com/ThaiEasyElec/TEE_UC20_Shield/blob/master/library.properties

**Comment by per1234** [comment]
Hi @ThaiEasyElec. The 1.0.3 release is available to me for installation via Library Manager:
![Clipboard01](https://user-images.githubusercontent.com/8572152/81282931-b643e200-9010-11ea-967c-0e9c2dae56de.png)

I see you only made the 1.0.3 four hours ago. It may take a while for the updated libraries index file to propagate through the caches to be available everywhere in the world.

I do notice that the 1.0.2 release is not available. The reason that release was not picked up by the Arduino Library Manager indexer is because you didn't update the `version` value in library.properties before creating the tag/release. The Library Manager uses the library.properties `version` value for versioning, so any tag that doesn't have a unique `version` value in library.properties is ignored. In that case, you had two tags that used the 1.0.1 version.

I'm going to go ahead and close this, but if the issue persists for you please comment here and I'll re-open.
