### ISSUE TITLE
Arduino Nano 33 BLE Sense Port lost

### ISSUE THREAD

**Issue by mbmchip** [arduino/Arduino#10178]
After uploading the wrong program，Arduino Nano 33 BLE Sense Port lost.

**Comment by per1234** [comment]
1. Press and release the reset button on your board quickly twice. You should now see the LED on the board pulsing, which means the bootloader is running.
1. Select the port of your board from the **Tools > Port** menu (or the equivalent if you're not using the Arduino IDE). The port number may be different when the bootloader is running so don't assume you already have the correct port selected.
1. Start an upload.

On the boards with native USB functionality like your Nano 33 BLE, the USB code that creates the CDC serial port is running on the same microcontroller as your sketch. This means your sketch code can break the USB code, or stop it from running. So you may find that the problem comes back after you upload the same problematic code again. Now that you know how to recover your board from this state, you have the ability to continue to troubleshoot your sketch. If you need help with that, feel free to post on the [Arduino Forum](http://forum.arduino.cc/index.php?topic=148850).
