### ISSUE TITLE
[Library Manager]  Arduino Library to receive Pixhawk sensor data.

### ISSUE THREAD

**Issue by shashikg** [arduino/Arduino#10243]
https://github.com/shashikg/PixhawkArduinoMAVLink

**Comment by cmaglie** [comment]
I've added the library to the indexer but there is a problem in the library.properties because you didn't define all the required fields:

```
JOB 3041 - 2020/05/22 23:53:46 Scraping https://github.com/shashikg/PixhawkArduinoMAVLink.git
JOB 3041 - 2020/05/22 23:53:50 Checking out tag: v1.0.0
JOB 3041 - 2020/05/22 23:53:50 Error syncing library: Error generating library from repo: 'sentence', 'paragraph', 'maintainer', 'architectures', 'category' fields must be defined
```

The description of the required fields is here: https://arduino.github.io/arduino-cli/library-specification/#libraryproperties-file-format
To fix the issue:

1. edit `library.properties` and add all the missing field
2. commit & push
3. delete the v1.0.0 tag and redo it so the release will pick up the updated library.properties -> https://github.com/shashikg/PixhawkArduinoMAVLink/blob/v1.0.0/library.properties

Once done the library will be automatically published within an hour.
If this doesn't happen and you need further assistance open a new issue so we can sort this out.
