### ISSUE TITLE
[Library manager] Add LcdMenu Library

### ISSUE THREAD

**Issue by forntoh** [arduino/Arduino#10327]
Please add this library to the Library manager
https://github.com/forntoh/LcdMenu
Thanks,

**Comment by per1234** [comment]
Hi @forntoh. Although your library is currently compliant with the requirements for inclusion in the Arduino Library Manager index, it was not at the time of your release/tag (due to the missing library.properties file), and the Library Manager indexer works from tags.

Please either redo the existing release/tag or else create a new one. Once that's done, please comment here to let us know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Boards-Manager-FAQ

**Comment by cmaglie** [comment]
Done.
