### ISSUE TITLE
[Library Manager] Library manager not updating new release. 

### ISSUE THREAD

**Issue by WarmCatUK** [arduino/Arduino#10353]
https://github.com/WarmCatUK/WarmCat_6x14Backpack
Library has been present for some time as 0.9.0
Some changes were made to the library and a 4 days ago I changed the version in library.properties to 0.9.1, created a new release also 0.9.1
However, the change is not reflected in the Arduino library.
Thanks in advance.

**Comment by per1234** [comment]
The reason is that you changed the `name` value in library.properties:
https://github.com/WarmCatUK/WarmCat_6x14Backpack/commit/901d3380b5d6485559b1d078eb50f387414423d8#diff-ea32f5b85735296fd64b577e91a19607R1

From the Library Manager FAQ:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#why-arent-releases-of-my-library-being-picked-up-by-library-manager
>Changing the name value in your library.properties from the one it had at the time when the library was added to the Library Manager index will cause releases to be ignored. You need to request a name change, as explained [here](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name).
