### ISSUE TITLE
[Library Manager] Update ElegantOTA and AsyncElegantOTA Libraries

### ISSUE THREAD

**Issue by ayushsharma82** [arduino/Arduino#10417]
Hi,
It has been quite some time that my libraries are not getting updated in the Arduino library index.

If possible, can you guys let me know why?

Here are the links to both the libraries:

1. https://github.com/ayushsharma82/AsyncElegantOTA
2. https://github.com/ayushsharma82/ElegantOTA

Thanks!

**Comment by per1234** [comment]
Hi @ayushsharma82 all the releases of those libraries are available to me in Library Manager:
![Clipboard01](https://user-images.githubusercontent.com/8572152/85537002-7046db80-b5c8-11ea-9028-69eb88b91217.png)
![Clipboard02](https://user-images.githubusercontent.com/8572152/85537012-72a93580-b5c8-11ea-9181-b5623efe6ad9.png)

The only exception is AsyncElegantOTA 1.0.1, because the library.properties `version` value wasn't updated:
https://github.com/ayushsharma82/AsyncElegantOTA/blob/v1.0.1/library.properties#L2

**Comment by ayushsharma82** [comment]
Yeah! Actually I used VSCode Arduino Extension which didn't update the library index and upon opening the Arduino IDE library manager, the index was updated.

Thanks for your support @per1234 !
