### ISSUE TITLE
TFT Arduino examples error 

### ISSUE THREAD

**Issue by siinnaaww** [arduino/Arduino#10438]
ALL the TFT examples shown in the Examples tab of the online editor are not compiling and showing the following error instead:
no matching function for call to 'TFT::TFT(int,int,int)'
I would appreciate it if someone could help me with this problem.

**Comment by per1234** [comment]
You can find the explanation for the error in the compilation output:
```
Multiple libraries were found for "TFT.h"

Used: /home/builder/opt/libraries/latest/tft_touch_shield_v1_0_1_0_2

Not used: /home/builder/opt/libraries/latest/tft_1_0_6
```
Unlike the standard Arduino IDE, every library in the Arduino Library Manager index is pre-installed on Arduino Web Editor. This is really convenient because it means you don't need to spend so much time installing libraries. The downside is that, with thousands of libraries installed, any common header filename (e.g., "TFT.h") is likely to occur in multiple libraries and the Arduino Web Editor might not be able to guess correctly which of those libraries your sketch was written for.

In this case, the example sketches were written for the [TFT library](https://github.com/arduino-libraries/TFT), but Arduino Web Editor is trying to compile the sketches using the ["TFT Touch Shield V1.0"](https://github.com/Seeed-Studio/TFT_Touch_Shield_V1) library instead.

Fortunately, there are ways to influence Arduino Web Editor to use the correct library. In this case, you can do this to make Arduino Web Editor use the right library:
1. Open the example sketch you want to try.
1. Click the button with the three dots to the right of the board menu at the top of the sketch.
1. Click "Save".
1. Name the sketch whatever you like.
1. Click the "OK" button.
1. In the Arduino Web Editor window, click the "Libraries" tab on the menu on the left side of the window.
1. Click the "Default" tab.
1. In the "Search libraries" field, type: tft
1. In the search results, hover the mouse pointer over the "TFT" entry.
1. Click the downward pointing triangle on the right side of the "Include" button.
1. From the dropdown menu, click "Version 1.0.6".
