### ISSUE TITLE
Arduino website - PJON library reference is broken

### ISSUE THREAD

**Issue by gioblu** [arduino/Arduino#10515]
In the Arduino's website, in the section "reference" I see this page related to the PJON library I develop and maintain:
https://www.arduino.cc/reference//en/libraries/pjon/

1. The indicated latest version is 9.1.0 when in reality the latest is 12.1.0
2. The description text is at least 5 years old, when the library included also encryption.
3. The compatibility, as defined by the `library.properties` file covers more targets than stated.
4. Is there any chance to have a link to our [website](www.pjon.org) in the description?

Is there any chance to have this page fixed?
Thank you.

**Comment by per1234** [comment]
Thanks so much for reporting this bug @gioblu! The bugs were fixed in response to your report back in July, but the issue was never closed, so I'm doing that now.

>Is there any chance to have a link to our website in the description?

I believe it works like this:

If  the `url` field in library.properties is the same as the URL of the library's repository, as with your library, then a single link is added to the reference page:
>[Read the documentation](https://github.com/gioblu/PJON)

However, if the library.properties `url` value is different from the repository URL, two links are added to the reference page, as you can see here:
https://www.arduino.cc/reference/en/libraries/wifinina/
>[Read the documentation](http://www.arduino.cc/en/Reference/WiFiNINA)
>
>[Go to repository](https://github.com/arduino-libraries/WiFiNINA)
