### ISSUE TITLE
NANO 33 IoT wont allow crypto configurtation

### ISSUE THREAD

**Issue by CAG5** [arduino/Arduino#10617]
I can and have been able to get connected to wifi, and upload sketches to include the firmware updater sketch, however, I have not been able to add a new device via the create portal nor the cloud portal.  Any help would be appreciated at this point.

**Comment by per1234** [comment]
Hi @CAG5 . I'm sorry to hear you're having a problem with Arduino Create.

I'm closing this issue because the correct place to report issues related to Arduino Create is the Arduino forum's **Create ** boards:
https://forum.arduino.cc/index.php?board=105.0
If you haven't done so already, please make a post there. Thanks!
