### ISSUE TITLE
Ethernet fails connecting after a while: client.connect() problem [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#1068]
This is [Issue 1068](http://code.google.com/p/arduino/issues/detail?id=1068) moved from a Google Code project.
Added by 2012-10-09T22:18:15.000Z by [P.K.Ton...@gmail.com](http://code.google.com/u/115162173103504327487/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Opening frequently a Ethernet connection (Once a minute)
2. After a while, the wiznet is no longer able to open connection.

**What is the expected output? What do you see instead?**
Running forever.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino Mega2560, Ethernet shield. (Official Arduino), Arduino 1.0.1, Win7

**Please provide any additional information below.**
It is hard to reproduce. Sometimes the cliet.connect() keeps returning a  false after a few hours, Sometimes after a few days.
I think (but i not sure) the problem occures more often if the WizNet is exposed to externel attempts to make a connection after opening ports on my router.

The problem and (possible) solution is discribes here:

http://forum.freetronics.com/viewtopic.php?t=176

I not sure if there is a relation to issue 1049.

**Comment by stevstrong** [comment]
HI,
I know, it is an old topic, but I have a very similar issue.
I have a W5500 module connected to a custom ATmega128A board.
I am using Arduino IDE version 1.6.1, the Ethernet lib adapted to W5500 (by merging the Wiznet lib to the native Arduino Ethernet lib). The merging only refers to the chip selection define and the addition of the new cpp and header files necessary for w5500.h.
In my software I run a local web server (always accessible) and a client, which client is connecting each second minute to a web server (NIST time TCP server on the internet), get the data from it and then disconnecting from it.
The problem is the client connection to this web server by calling "client.connect(...)".
After a time, which randomly varies between couple of minutes and hours (although it occures several times per day - up to 15 times), the client cannot connect anymore to the mentioned web server.
In these cases the "client.connect(...)" function returns consequently always "0". This means that once the conection failed, it will continuously fail, cannot recover anymore.
In my software I check if the connection fails for 20 consecutive times, and then a Watchdog reset is activated.
In addition, the Ethernet SW initialisation routine sets an IO pin to HW reset the W5500 chip as well before "Ethernet.begin(...)" and "client.connect(...)", so that the W5500 chip is HW reset for sure before the software starts initialsing it.
After reboot, the client connection works again. It works also then, when 10 seconds before was not yet working, so I can exclude NIST web server availability problem.

I checked the Ethernet sources, specially EthernetClient.cpp, and saw that a return value of "0" is given when no sockets are available.
But how can this happen?

Any hints how could I locate the root cause?

**Comment by ferobred** [comment]
Hi,
I have the same problem as @stevstrong 
In every connection with the server I close the connection with "client.stop()", But only works when I Restart the ethernet shield, not the next times.
It works with Ethernet.begin(mac,ip....) before client.connect(server,port) every connection.
I think it works because the begin function restarts all sockets, but i don´t know why the client.stop() don´t close that sockets.

cc @jecrespo

**Comment by stevstrong** [comment]
It seems that I could solve the problem with the following approach:
*****
  ctime = millis() + TIMEOUT_REPLY;  // time within to get reply
  while ( time_client.connected() )
  {
    if ( millis()>ctime ) {  // if no answer received within the prescribed time
      time_client.stop();
      return;
    }
    while ( time_client.available() ) {
      Time_ParseTCPData( time_client.read() );
    }
  }
  time_client.stop();
*****
I think that the constructs "while ( client.connected() )" and "while( client.availble() )" did the trick.
Hope that it helps others as well.

**Comment by agdl** [comment]
This issue was moved to arduino-libraries/Ethernet#15
