### ISSUE TITLE
[Library Manager] Could you please add arduino-slack-library to the library manager

### ISSUE THREAD

**Issue by witnessmenow** [arduino/Arduino#10700]
Hello,

Could you please add arduino-slack-library to the library manager:
https://github.com/witnessmenow/arduino-slack-api

Thanks,
Brian

**Comment by cmaglie** [comment]
Hi @witnessmenow sorry for the delay.

You named your library `ArduinoSlackAPI` the prefix `Arduino*` is reserved for the libraries made and maintained by Arduino, that's why we do not accept new libraries with this prefix.

Can you change the name of your library? `SlackAPI` or anything else will work.

To do this remember to:
1. change the name in `library.properties`
2. commit & push
3. delete the latest git tag and redo it on master

Thanks!

**Comment by witnessmenow** [comment]
Hello @cmaglie 

I've updated the library.properties, bumped the version and tagged a new release. I also deleted the old tag.

Thanks!

**Comment by cmaglie** [comment]
Done, thanks!
