### ISSUE TITLE
Tutorials missing from new search function 

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/Arduino#10796]
The "tutorials" sections seem to be missing from the search option.

Not sure why they would be excluded ?

Can we have them back please.

**Comment by per1234** [comment]
Thanks for reporting this issue @BallscrewBob. I just checked and am seeing tutorials in the search results. For example:
https://www.arduino.cc/search?q=%22blink%20without%20delay%22
So I'll assume this was fixed at some point since your report without the issue having been closed.

If you are still experiencing this bug, please comment here and I'll reopen.
