### ISSUE TITLE
Add a library controlKeyboard

### ISSUE THREAD

**Issue by YashuYathi** [arduino/Arduino#10797]
Please add this Arduino library.
https://github.com/YashuYathi/controlKeyboard.git

**Comment by per1234** [comment]
Hi @YashuYathi. In order to be added to the Library Manager index your library must contain a library.properties file. The format of this file is documented here:
https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format

After adding the library.properties file, you will need to create a new tag/release or redo the existing one. Make sure that the `version` value matches the tag of the release that contains it.

Once you have done this please comment here so we know we can proceed.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by YashuYathi** [comment]
I have done the changes. Please review it.

**Comment by per1234** [comment]
The library looks good to me now. However, it was not compliant with the requirements at the commit the 1.0.0 tag was made on:
https://github.com/YashuYathi/controlKeyboard/tree/1.0.0

So you'll need to either create a new [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag), or else redo the existing `1.0.0` tag.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

**Comment by YashuYathi** [comment]
I didn't get it. It is 1.0.0

**Comment by YashuYathi** [comment]
Sorry about that. I have changed it.

**Comment by per1234** [comment]
Your repository is still not compliant.

Please carefully follow these instructions:
1. Open this link: https://github.com/YashuYathi/controlKeyboard/releases
1. Click the "Draft a new release" button near the top right corner of the page.
1. In the "Tag version" box, type "1.0.1"
1. In the "Target" menu, make sure "master" is selected.
1. Click the "Publish release" button.

**Comment by YashuYathi** [comment]
Is this correct?

**Comment by per1234** [comment]
Looks good to me. Thanks!

**Comment by cmaglie** [comment]
Done, sorry for the long delay.
