### ISSUE TITLE
[Library Manager] Please add LinearRegression library to manager.

### ISSUE THREAD

**Issue by akkoyun** [arduino/Arduino#10919]
Hi all,
Can u add my library to library manager.

https://github.com/akkoyun/LinearRegression

**Comment by per1234** [comment]
Hi @akkoyun. In order to be added to the Library Manager index, you must have a `url` value defined in your library.properties. I It is currently undefined:
https://github.com/akkoyun/LinearRegression/blob/01.00.00/library.properties#L8
```
url=
```
You can just add the URL of your repository if you like.

After fixing that, please either update the `version` value in library.properties and create a new [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag), or else redo the existing release/tag.

Once you have done this, please comment here so we'll know we can proceed.

**Comment by akkoyun** [comment]
Updated please confirm
thanks.

**Comment by cmaglie** [comment]
Done.

**Comment by akkoyun** [comment]
Thanks my friend.

**Comment by njh** [comment]
It looks like this repository has now been deleted.

Do you mind giving some feedback about why it is gone @akkoyun ?
