### ISSUE TITLE
Mac os big sur error

### ISSUE THREAD

**Issue by VASAPOL** [arduino/Arduino#10971]
Hi i have issue with esp8266 in arduino. 
I cant uploads i tried a different computer and have same issue.please help
Macos Bigsur.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we end up determining on the forum that your problem is caused by a bug in official Arduino software, I'll be happy to reopen, but right now there's absolutely no evidence of that.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post the full and exact error output.
