### ISSUE TITLE
Cannot compile clean version of Marlin 2.0.x

### ISSUE THREAD

**Issue by hillsh** [arduino/Arduino#10989]
I cannot compile a clean download of Marlin 2.0.x with Arduino 1.8.13.  I have also tried the latest 1.9 beta version.  The error I am getting is 

Arduino: 1.9.0-beta (Windows 10), Board: "RAMBo"

avr-gcc: error: CreateProcess: No such file or directory

exit status 1
Error compiling for board RAMBo.

I think this error is somehow related to a problem with long filenames in Windows.  I have searched diligently on the web and tried any and all suggestions, to no avail.  I think this is a bug in Arduino which I hoped might be fixed in the beta version - nope.

**Comment by per1234** [comment]
Even though it mentions a different error message, I believe this is the same as https://github.com/arduino/Arduino/issues/10565 so I'll close this as duplicate.

You'll be happy to know that the issue should now be fixed in Arduino CLI (https://github.com/arduino/arduino-cli/pull/961), from which it will eventually make its way to an Arduino IDE. You can try out the fix by using the nightly build of Arduino CLI :
https://arduino.github.io/arduino-cli/latest/installation/#nightly-builds
