### ISSUE TITLE
Please add  this New library to  library manager for Bot Control

### ISSUE THREAD

**Issue by paulpavish** [arduino/Arduino#11197]
Opening this issue As mentioned in Library-Manager-FAQ on how to add a library to Arduino Library Manager.

The library to be included, link : https://github.com/paulpavish/MotorDriver_GuiNE_Bot/releases/tag/v1.0.0

Thankyou
Paul Pavish

**Comment by paulpavish** [comment]
Hi, Thank you for responding. 
Just out of curiosity to begin my sessions, How long will it take for this library to get listed in the Arduino LIbrary Manager !?

**Comment by per1234** [comment]
Hello @paulpavish. Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You will receive a notification from GitHub when the issue is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

**Comment by paulpavish** [comment]
I understand @per1234 .
Thank you

**Comment by cmaglie** [comment]
Done.
