### ISSUE TITLE
Mac OSX Catalina not show lib examples

### ISSUE THREAD

**Issue by RodrigoDornelles** [arduino/Arduino#11216]
i'm using a macbook with the latest version of mac os, and i can't list the examples created by third party libraries.

![screenshot](https://user-images.githubusercontent.com/29123479/106036969-ccb92e80-60b4-11eb-9bb2-256d44eed57b.png)

**Comment by per1234** [comment]
Hi @RodrigoDornelles. Thanks so much for reporting this.

In order to assist us with the investigation, please try this quick experiment of installing an arbitrary 3rd party library via Library Manager:

1. From the Arduino IDE's menus, select **Sketch > Include Library > Manage Libraries...**
2. Wait for the update to finish.
3. In the "Filter your search..." field, type "fastled"
4. Press the "Enter" key.
5. From the list of search results, click on "FastLED by Daniel Garcia".
6. Click the "Install" button.
7. Wait for the installation to finish.
8. Click the "Close" button.

Now open the **File > Examples** menu. Do you see "FastLED" in the menu?

**Comment by per1234** [comment]
Closing due to lack of response.

@RodrigoDornelles  if you'll provide the requested information I'll be happy to re-open this issue.

**Comment by RodrigoDornelles** [comment]
Sorry for the delay, I was without a computer, but finally when I fixed my macbook, this problem no longer occurs.
