### ISSUE TITLE
All menu's, context menu and button text is missing

### ISSUE THREAD

**Issue by dolfandringa** [arduino/Arduino#11234]
On Fedora 33 with wayland and dual monitor setup, the UI of the Arduino IDE is fully b0rked. The "File", etc menu at the top is missing, there is no text in the context menu (the menu does still appear though) and all text in buttons and dropdown/select boxes are missing too. This is for Arduino 1.8.13 for 64 bit downloaded from the arduino website. If I install the apt version from the fedora package maintainers, there is no issue, but I can't use that version because it's not supported by TeensyDuino.

The only error I see when launching arduino from the commandline is `Failed to load module "pk-gtk-module"`

![image](https://user-images.githubusercontent.com/1193497/106574484-e6a3b700-6575-11eb-880f-8165da8cb7b5.png)
![image](https://user-images.githubusercontent.com/1193497/106574501-edcac500-6575-11eb-8a43-8df2b62b054f.png)

**Comment by per1234** [comment]
Hi @dolfandringa. Thanks for your bug report. We already have a report of this: https://github.com/arduino/Arduino/issues/11150 and it's best to have only one issue per subject so we can consolidate all information to a single place, so I'll go ahead and close this as duplicate.

Please check https://github.com/arduino/Arduino/issues/11150 for the workaround and interesting discussion for this. You might want to subscribe to that issue in order to get updates about any new developments.
