### ISSUE TITLE
Can i change the name of my existing library ? 

### ISSUE THREAD

**Issue by paulpavish** [arduino/Arduino#11249]
My 'MotorDriver_GuinEBot' library was added to the library manager a week ago. Can i change the name of the library to just 'GuinEBot' but the header files will be the same. !? 

https://github.com/paulpavish/GuiNE_Bot_Arduino_Library

**Comment by per1234** [comment]
Yes, you can change the library name. You'll need to do that following:

1. Change the `name` value in library.properties to the new name: https://github.com/paulpavish/MotorDriver_GuiNE_Bot/blob/main/library.properties#L1
2. Update the `version` value in library.properties to the version you will be using for the release of the newly named library.
3. Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.
4. Wait for the entry for your library in the index to be manually updated.

**Comment by paulpavish** [comment]
Ok. what happens if i change the library repository name and then release a new version to the same library with different name and version 1.0.1 , will the library still be updated?

**Comment by per1234** [comment]
Even though GitHub automatically sets up a redirect when you change the repository name, we should also change the URL in the Library Manager index just to be safe if you change the repository name. So please let us know if you do that.

**Comment by paulpavish** [comment]
Ok. This is the already given repository link 'https://github.com/paulpavish/MotorDriver_GuiNE_Bot' . Renamed to 'https://github.com/paulpavish/GuiNE_Bot_Arduino_Library'

**Comment by paulpavish** [comment]
Still pending update.....

**Comment by per1234** [comment]
cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. So the delay before the request is processed is dependent on what point in the cycle your request happened to fall. You will receive a notification from GitHub when the issue is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
Done.
