### ISSUE TITLE
[Library Manager] Please add these libraries for our device "Agrumino Lemon"

### ISSUE THREAD

**Issue by Bighoneypot** [arduino/Arduino#11274]
Hello everyone and thank you for your work.

I ask you to add this library on Arduino for our "Agrumino Lemon" sensor.

Thank you.
If there are any problems with the library write me.

https://github.com/lifely-cc/agruminoLemon-libraries

**Comment by per1234** [comment]
Hi @Bighoneypot. Thanks for your interest in contributing to the Arduino Library Manager index. I get a "Page not found" error from the link you shared:
https://github.com/lifely-cc/agruminoLemon-libraries
Is the repository set to "private" visibility? I do see this similarly named repository:
https://github.com/lifely-cc/Agrumino

**Comment by Bighoneypot** [comment]
@per1234  Sorry now is public

**Comment by Bighoneypot** [comment]
@per1234 The correct repository is https://github.com/lifely-cc/agruminoLemon-libraries

**Comment by cmaglie** [comment]
Done.

**Comment by Bighoneypot** [comment]
@maglie Gday , I have a question.
I have update my libraries with a new release.
To use the new release on the Arduino libraries, do I need to ask for some authorization or is it all automatic? Thank you.

**Comment by per1234** [comment]
Hi @Bighoneypot every release which meets all the requirements listed in [the FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ) will be automatically added to the Library Manager index.

The job runs hourly but there might be some additional delays before the release is available for installation via Library Manager due to caching. Worst case scenario, I would say it should always show up within a day.

**Comment by Bighoneypot** [comment]
Thank you @per1234
