### ISSUE TITLE
Arduino Freeze

### ISSUE THREAD

**Issue by AniketFasate27** [arduino/Arduino#11275]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

**Comment by per1234** [comment]
Closing due to there not being enough information to investigate. @AniketFasate27 if you will provide all the necessary information, as specified in [the issue guidelines](https://github.com/arduino/Arduino/blob/master/CONTRIBUTING.md#issues), and comment here, then I'll be happy to take another look and consider reopening this.
