### ISSUE TITLE
[Library Manager] Change of Library Name

### ISSUE THREAD

**Issue by lakshanthad** [arduino/Arduino#11313]
Hi, 

The name for the following library, inside library.properties have been changed:

https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi

From "Seeed Arduino WiFi" to "Seeed Arduino rpcWiFi"

I have already updated the version inside library.properties and created a new release as well. 

Please help to include this update in Arduino Library Manager

Best Regards,
Lakshantha

**Comment by lakshanthad** [comment]
Can I know how long it will take for this update to appear on Arduino Library Manager?

Best Regards,
Lakshantha

**Comment by per1234** [comment]
Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You will receive a notification from GitHub when the issue is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache. So we'll get to it eventually. Please be patient.

**Comment by lakshanthad** [comment]
I understand.

Thank you for the clarification.

**Comment by cmaglie** [comment]
Done.

**Comment by lakshanthad** [comment]
Thank you
