### ISSUE TITLE
[Library Manager] Add Seeed Arduino rpcBLE to Arduino Library Manager 

### ISSUE THREAD

**Issue by lakshanthad** [arduino/Arduino#11324]
Hi,

Please add the following library to Arduino Library Manager:

https://github.com/Seeed-Studio/Seeed_Arduino_rpcBLE

Best Regards,
Lakshantha

**Comment by lakshanthad** [comment]
Hi, 
Can I know whether it will take longer for the library to get added?

Best Regards,
Lakshantha

**Comment by per1234** [comment]
Hello @lakshanthad 

Your library will not be available for installation via Library Manager until it has been added to the index. A maintainer occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You will receive a notification from GitHub when the issue is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache. So we'll get to it soon, please be patient.

**Comment by lakshanthad** [comment]
okay. Thank you

**Comment by cmaglie** [comment]
Done, sorry for the long delay!

**Comment by lakshanthad** [comment]
It's fine. Thank you
