### ISSUE TITLE
[library manager] Please the following GCodeParser library to library manager. 

### ISSUE THREAD

**Issue by tgolla** [arduino/Arduino#11375]
https://github.com/tgolla/GCodeParser

**Comment by tgolla** [comment]
Just wandering what the ETA is on getting the added.

**Comment by per1234** [comment]
Hi @tgolla. Your library will not be available for installation via Library Manager until it has been added to the index. The maintainer in charge of the index occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done.

So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You will receive a notification from GitHub when the issue is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
Done! sorry for the long delay!
