### ISSUE TITLE
Linker not picking up library with .c extension, only .cpp

### ISSUE THREAD

**Issue by DavesCodeMusings** [arduino/Arduino#11443]
I have recently created my own library of base64 functions and installed it into Documents\Arduino\libraries\b64 (on Windows.) The two files are b64.h and b64.c, because I have written the library in C, not C++.

Current behavior:
When I include my library in a sketch, every function in my library generates an 'undefined reference'. However, by renaming my b64.c file to b64.cpp, all of the errors disappear and things work as expected.

Expected behavior:
The Hacking Libraries reference (https://www.arduino.cc/en/Hacking/Libraries) mentions in the very first sentence, "Libraries are files written in C or C++ (.c, .cpp)" The Arduino IDE should follow suit and link .c files as well as .cpp files.

Version info:
I am using Arduino IDE 1.8.13

**Comment by per1234** [comment]
After [some minimal preprocessing](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#pre-processing), the .ino files of Arduino sketches are compiled as C++. This means that you will need to wrap the declarations for the C in `extern "C" {}` in order to use it in the sketch:
https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c/12994075#12994075
