### ISSUE TITLE
arduino 1.8.14 chooses wrong SD.h library on esp32

### ISSUE THREAD

**Issue by lbernstone** [arduino/Arduino#11531]
In Arduino 1.8.14, when including the SD.h library, there is a name overlap, and Arduino chooses the library in the sketchbook folder or arduino-1.8.14/libraries instead of the one in the espressif hardware folder.  This does not occur in 1.8.13, and continues even if the version in esp32 is bumped to 2.0.0.  The architecture specific library should be preferred over *.
```
In file included from /home/larryb/arduino-1.8.14/libraries/SD/src/utility/Sd2Card.h:26:0,
                 from /home/larryb/arduino-1.8.14/libraries/SD/src/utility/SdFat.h:29,
                 from /home/larryb/arduino-1.8.14/libraries/SD/src/SD.h:20,
                 from /tmp/sketch_may14a/sketch_may14a.ino:1:
/home/larryb/arduino-1.8.14/libraries/SD/src/utility/Sd2PinMap.h:524:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported.
  ^
Multiple libraries were found for "SD.h"
 Used: /home/larryb/arduino-1.8.14/libraries/SD
 Not used: /home/larryb/Arduino/hardware/espressif/esp32/libraries/SD

**Comment by per1234** [comment]
Hi @lbernstone. Thanks for taking the time to submit a bug report. This has already been fixed by https://github.com/arduino/Arduino/pull/11529
There will be an Arduino IDE 1.8.15 release out soon with the fix.

For details on the issue, please see this: https://github.com/arduino/arduino-cli/issues/1292
