### ISSUE TITLE
I2C call is clobbering switch statement

### ISSUE THREAD

**Issue by ThomHehl** [arduino/Arduino#11591]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.
In the attached project is a switch statement. In one of the cases, I call I2C using the wire libraries. After this, the case statement never works correctly.
[wfwtestboxtest.tar.gz](https://github.com/arduino/Arduino/files/6625409/wfwtestboxtest.tar.gz)

**Comment by per1234** [comment]
Hi @ThomHehl. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/

If the investigation there indicates that your problem is caused by a bug in official Arduino software, I'll be happy to reopen this.
