### ISSUE TITLE
Links in <Help> menu don't all work

### ISSUE THREAD

**Issue by illivv** [arduino/Arduino#11629]
Hi all,
I'm a newbie, which is why I'm probably the first one to report this. When I click on the links in the help menu, only some work. Others will lead to an exception message "URL couldn't be opened: /usr/share/arduino/reference/www.arduino.cc/en/Reference/HomePage.html" or similar.

**To Reproduce**
1. Open Arduino IDE
2. Click on 'Help'
3. Press any of the following:
- Environment
- Troubleshooting
- Reference
- FAQ
-> Error message Pops up.

**Expected behavior**
Opens a help document or one of the other documents

**Screenshots**
![image](https://user-images.githubusercontent.com/87392595/126076103-020a1017-d5f2-4487-855c-82136fbe2a3e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 
 - Manjaro Linux with 
 - KDE-Plasma 5.22.3,
 - KDE Fraework 5.84.0, 
 - Kernel-Version 5.12.16-1-MANJARO (64-bit)

**Additional context**
I'm using Arduino IDE Version 1.8.15, installed over Pamac.
I've found the documents in the path:
/usr/share/arduino/reference/arduino/www.arduino.cc/en/Guide/
the link tries to go to
/usr/share/arduino/reference/www.arduino.cc/en/Guide/
(notice the additional "arduino" folder)

Is it only my installation that is different?

**Comment by per1234** [comment]
>Is it only my installation that is different?

I think so. I can't reproduce it with my Linux installation. Probably the 3rd party package creator messed up the path.

I recommend using the official Arduino IDE downloaded from arduino.cc:
https://www.arduino.cc/en/software
If you have any problems with the Help menu links with the official Arduino IDE, feel free to comment here and I'll investigate further.

I also recommend using the documentation content from arduino.cc because the bundled reference content is outdated.
