### ISSUE TITLE
Library manager and multiple authors can be problematic

### ISSUE THREAD

**Issue by tablatronix** [arduino/Arduino#11679]
Cannot find library by author name, other effects are minimal afaik.

as per library manifest docs
`author - name/nickname of the authors and their email addresses (not mandatory) separated by comma (,)`

This yields some strange issues in the IDE, causing searching by author name to not work reliably, eg. empty search results.
Sometimes only one name is shown, sometimes both, searches for author usually return no results, and can change even in real time..

![Screen Shot 2021-10-06 at 11 31 21 AM](https://user-images.githubusercontent.com/807787/136246407-95012953-6845-43b4-b952-77276b97336b.png)
<img width="410" alt="Screen Shot 2021-10-06 at 11 29 48 AM" src="https://user-images.githubusercontent.com/807787/136246411-7c8638c1-5d03-4360-8e06-6ba62dbb8ea2.png">
<img width="378" alt="Screen Shot 2021-10-06 at 11 29 34 AM" src="https://user-images.githubusercontent.com/807787/136246413-a5159753-caaa-44ee-961b-306a8c46a8a9.png">

I have since removed myself from authors to make sure ppl can find it by `tzapu` since searching by library name is not sorted by relevance and its a mess.

**Comment by per1234** [comment]
Thanks @tablatronix. The search is now handled by Arduino CLI, so the change would need to be made in that codebase. Since I think it will be easier to understand when worded in the context of Arduino CLI rather than the Arduino IDE-specific context of this issue, I have resubmitted your issue here: https://github.com/arduino/arduino-cli/issues/1894

If you end up with additional information to share, feel free to comment in the other thread.
