### ISSUE TITLE
Telemetrix4Esp8266 not updated in library manager

### ISSUE THREAD

**Issue by MrYsLab** [arduino/Arduino#11759]
I updated https://github.com/MrYsLab/Telemetrix4Esp8266 yesterday created a new version (4.0.1). I checked library.properties for a matching version number and ran arduino-lint successfully. 

Could you please tell me if I need to do anything else?

I also updated https://github.com/MrYsLab/Telemetrix4Arduino yesterday. The library manager picked that up correctly.

Thanks.

**Comment by per1234** [comment]
Hi @MrYsLab 

## Problem

The problem is shown here in [the "Telemetrix4Esp8266" library's dedicated indexer logs web page](https://downloads.arduino.cc/libraries/logs/github.com/MrYsLab/Telemetrix4Esp8266/):

```text
2022/02/12 17:18:29 Checking out tag: 4.0.1
2022/02/12 17:18:29 Release Telemetrix4Esp8266:4.0.0 already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `4.0.1` tag.

You can see it here:

<https://github.com/MrYsLab/Telemetrix4Esp8266/blob/4.0.1/library.properties#2>

```text
version=4.0.0
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the  `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day. The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per
