### ISSUE TITLE
No Existing Option to Burn Bootloader From Command Line

### ISSUE THREAD

**Issue by davidcooper1** [arduino/Arduino#11765]
Recently, there was a request in the VS Code Arduino extension repo to add a burn bootloader command (microsoft/vscode-arduino#967). This extension can use either `arduino-cli` or the `arduino` command line options. However, I noticed that while this option is present in the `arduino-cli` it is not present in the `arduino` command line options, nor did I notice any previous request for this feature. Can this be implemented, so that dependent applications, such as the VS Code extension, can make use of this?

**Comment by per1234** [comment]
Hi @davidcooper1. Thanks for your request. [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/) is now considered the full replacement for the Arduino IDE 1.x command line interface, providing all the IDE's capabilities and much more. Those who use Arduino CLI directly will find far more user friendly and efficient than the Arduino IDE command line interface.

I see from [your nice pull request](https://github.com/microsoft/vscode-arduino/pull/1463) that you are already aware of the fact, but for the benefit of others who use the Arduino IDE command line interface indirectly via Microsoft's "**Visual Studio Code extension for Arduino**"](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino), I'll add that the extension can be used with Arduino CLI instead of Arduino IDE 1.x:

https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino#arduino-cli
