### ISSUE TITLE
Arduino IDE is not opening 

### ISSUE THREAD

**Issue by arslan437** [arduino/Arduino#11768]
IDE version : 1.8.19 

When I run the arduino debug exe file this is the what happen. 

![image](https://user-images.githubusercontent.com/55940958/156881679-989f0f59-69fb-42c4-84cb-ecfc9fa6f328.png)

**Comment by DragonflyRobotics** [comment]
Could you please provide details regarding your installation and computer? I am assuming that you installed it using the installer and provided admin privileges. The only immediate problem I can think of is that the IDE can't initialize the Serial interface because it is lacking privileges. This happens to me in Linux when I suddenly unplug an Arduino and the whole program completely freezes.

**Comment by arslan437** [comment]
I don't know what caused this. But I was working on esp32 based project. But suddenly it stopped working. I uninstalled the IDE and installed the latest version that I have downloaded from arduino.cc but didn't changed any thing.

I deleted the Arduino15 folder and then installed the IDE it worked after that.
