### ISSUE TITLE
Conflict with Windows Defender.

### ISSUE THREAD

**Issue by avandalen** [arduino/Arduino#11814]
See the topic here:
https://forum.arduino.cc/t/java-io-ioexception-when-saving/1023157

I have found the cause of the problem: there is a conflict with Windows Defender.
The solution is to exclude any files opened by Arduino.exe from Windows Defender.

This is the procedure:
Start > Settings > Update & Security > Windows Security > Virus & threat protection > Manage settings > Exclusions > Add or remove exclusions > (Windows security YES) > Add an exclusion: C:\Program Files (x86)\Arduino\arduino.exe

**Comment by per1234** [comment]
Thanks for taking the time to share your solution @avandalen.

Since there doesn't seem to be anything that could be done to fix or mitigate the problem in the files hosted under this repository (by design, antivirus software will not support a 3rd party application automatically excluding itself), I will close this.

It will continue to serve as a reference to other affected users.
