### ISSUE TITLE
Arduino IoT Cloud Dashboard Status Widget colour option requested

### ISSUE THREAD

**Issue by GentleGiantSoftware** [arduino/Arduino#11877]
Currently the status widget on the Arduino IoT Cloud Dashboard is coloured RED when the boolean value is FALSE and coloured GREEN when the boolean value is TRUE. But when this boolean for instance represents an alarm, then these colours are incorrect. Therefor it would be nice if the status widget could get a configuration option to define the colours for true and false, alternatively an option to at least swap the two colours would be appreciated.

**Comment by per1234** [comment]
Hi @GentleGiantSoftware. Thanks for taking the time to submit this suggestion for improvement of [Arduino IoT Cloud](https://docs.arduino.cc/cloud/iot-cloud).

I'm closing this issue because the correct place to report issues or make feature requests specific to the Arduino IoT Cloud is in its dedicated category on the Arduino forum:

https://forum.arduino.cc/c/software/iot-cloud/152

If you haven't done so already, please make a report there. Thanks!
