### ISSUE TITLE
Bug in IOT Cloud Android app

### ISSUE THREAD

**Issue by Sommerdal-ufm** [arduino/Arduino#11888]
I have a ESP32 app that goes to sleep after syncing a Time Picker variable.
If I open the Dashboard on my Android phone it shows:

DD/MM/YYYY
hh:mm:ss
Europe/Copenhagen

When the chip wakes up againg and assigns a new value to the variable the Dashboard is updated correctly.

On my PC the time is showed correctly with lastest assigned time.

It seems like a bug.

**Comment by per1234** [comment]
Hi @Sommerdal-ufm. Thanks for taking the time to submit this report about [**Arduino IoT Cloud**](https://docs.arduino.cc/cloud/iot-cloud).

I'm closing this issue because the correct place to report issues or make feature requests specific to **Arduino IoT Cloud** is in its dedicated category on the Arduino forum:

https://forum.arduino.cc/c/software/iot-cloud/152

If you haven't done so already, please make a report there. Thanks!
