### ISSUE TITLE
Static build for Termux

### ISSUE THREAD

**Issue by john-peterson** [arduino/Arduino#11880]
I am probably the only one on the planet doing this but I am trying different light weight coding assistance beyond the standard vim/ack. This might be a luxury but it does help. Especially code navigation to find everything. INSIDE ANDROID ;-) surprise. Not inside linux. The thing is static builds in Debian Linux works like magic in android. Dynamic builds results in this

~/arduino-1.8.19 $ ldd java/bin/java
        libpthread.so.0 => not found
        libjli.so => not found
        libdl.so.2 => not found
        libc.so.6 => not found

A daunting task to say the least. You don't want to find all those files. You want them inside all binaries. In any case if someone else is interested please comment. I might start inserting "-static" here and there. A... And I don't know exactly how many files are used. This was the first one it complained about..

Have a good one I'm hiking through wolf infested northern Poland this summer   only my phone no other computer

**Comment by per1234** [comment]
Hi @john-peterson. Thanks for sharing your project.

Since it doesn't appear to be a report of a defect or proposal for an enhancement to the codebase hosted in this repository, and since the Arduino IDE 1.x project is no longer actively developed, I'll close this issue. If you would like to collaborate on producing Android-compatible Arduino IDE 1.x builds, or want to raise awareness of the availability of this option in the community, I suggest starting a fork of the repository with the necessary changes to the build system, and/or posting about it on [Arduino Forum](https://forum.arduino.cc/)

Regards,
Per
