### ISSUE TITLE
Instalation guide is not corresponding with content of downloaded package.

### ISSUE THREAD

**Issue by robinpecha** [arduino/Arduino#11941]
Linux instalation guide points to install.sh file inside downloaded package arduino-1.8.19. But there is no file like this there. Some install.sh is hidden deeply in folders but its throw some errors and does not install ide. This can be confusing for new users.
https://www.arduino.cc/en/Guide/Linux
![image](https://github.com/arduino/Arduino/assets/9316280/b8dcb8bf-8610-49fa-bca3-36fa16e0c78a)
![image](https://github.com/arduino/Arduino/assets/9316280/4c6b05c4-b7e3-4f5d-958e-bbd78b8519c3)

**Comment by per1234** [comment]
Hi @robinpecha. I can see from your screenshot that you downloaded the Arduino IDE source code instead of the built application. This is the reason why you didn't find the `install.sh` file.

You must click the "**Linux 64 Bits**" download link on the Software page to download the build Arduino IDE application:

https://www.arduino.cc/en/software#legacy-ide-18x

After that file downloads, extract it and continue with the installation instructions from that folder. You can delete the Arduino IDE source code folder you have now, unless you are planning to do some work with the IDE's codebase.
