### ISSUE TITLE
A different MAC IDE crash

### ISSUE THREAD

**Issue by catinthehat** [arduino/Arduino#1213]
I was working on a Leonardo sketch which runs at a fixed periodic rate by calculating how much time to delay and was getting weird results where it went around the loop twice then a longer than desired delay and again twice in succession ... I was also using Serial at 115200 to send debug info to the Monitor.  I switched to a Uno to see if it had the same behavior and made the appropriate changes in the IDE and rebuilt.  Shortly after that the IDE crashed and would not launch again, additionally it deleted the sketch file and the MAC ran real slow for everything and each time I started the MAC I got a dialog box stating that the MAC had crashed the previous time and asked whether to reload open windows or not (the MAC had never crashed and I had been shuting down normally).  Couldnt get rid of the slowness or the bootup message even after reinstalling IDE.  Had to reload the MAC OS to resolve the slowness and the bootup message. The OS is Mt Lion and the IDE was 1.0.2 (now 1.0.3)

**Comment by ffissore** [comment]
It looks like a problem related to native component used by the IDE to use serial ports. It has been fixed in 1.5.8 (beta version). Can you give it a try? http://arduino.cc/en/Main/Software#beta
Since you're using Mt Lion, better would be if you could try "macosx-new" version from https://github.com/arduino/Arduino/pull/2590#issuecomment-72337128

**Comment by ffissore** [comment]
Fixed with IDE 1.6.0 release. If you still have problems, please open a new issue
