### ISSUE TITLE
ATTINY4313 Arduino ISP

### ISSUE THREAD

**Issue by weswortman** [arduino/Arduino#1214]
Even with core files cannot program ATTINY4313 using Arduino ISP. Error is C:\Installs\arduino-1.0\hardware\tiny\cores\tiny/TinyDebugSerial.h:690: error: cannot convert 'TinyDebugSerialWriter_115200_' to 'TinyDebugSerialWriter_' in assignment
and only for Assembly language. On google search it says Arduino uses outdated tool chain and there is a problem with the 4K memory. I have not resolved.

**Comment by per1234** [comment]
Toolchain has been updated since this issue was created and compiling for ATtiny4313 using the [arduino-tiny](https://code.google.com/archive/p/arduino-tiny) 0020 hardware package (after a small modification required due to changes in the Arduino IDE since the last release of that project) works fine for me.
