### ISSUE TITLE
SPI Number of Bits

### ISSUE THREAD

**Issue by bitsetter** [arduino/Arduino#1335]
Please allow the SPI routines on the non Due board to allow for less than 8 bits.
I have an application that uses 12 bits and if I can only send out bytes, I have to write my own SPI routines.  It would be nice to specify the number of bits to be sent out.
Like numberOfBits = 12

If nothing else, you could allow for half bytes (4bit) sends.
So I could do two 8 bit transfers and one 4 bit transfer to get 12 bits.

Thank you for considering my wish!

Bitsetter.

**Comment by cmaglie** [comment]
This change requires a quite amount of work to allow a very unusual scenario (non-8 bit SPI transfers) so I'm marking the issue as "won't fix".

@bitsetter 
this issue is very old but may you tell us why you need it? Can't you send your 12-bit values as a 16-bit with the high 4 bit padded with zeros? Maybe your device is not accepting it?
