### ISSUE TITLE
Can't use Tools / Burn Bootloader to just change fuses

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/Arduino#1437]
When {bootloader.file} is not specified, do not execute the {tools.avrdude.bootloader.pattern recipe}.

**Comment by per1234** [comment]
You are now welcome to define the tools patterns however you wish. If you don't want the pattern to do anything, just make it an empty definition:
```
tools.avrdude.bootloader.pattern=
```
Because you are able to override build properties, this can be done even when the platform is [referencing the tool](https://arduino.github.io/arduino-cli/latest/platform-specification/#tool-references) recipes from another platform. You can also do this on a per-board basis, or as a [custom board option](https://arduino.github.io/arduino-cli/latest/platform-specification/#custom-board-options) in boards.txt:
```
uno_nobootloader.tools.avrdude.bootloader.pattern=
```

`bootloader.file` is only an arbitrary property, with no special treatment by the Arduino platform system. Since the platform author already has the ability to accomplish this, it wouldn't make sense to add additional complexity to the platform system by making the [`bootloader` action](https://arduino.github.io/arduino-cli/latest/platform-specification/#burn-bootloader) be treated differently depending on whether `bootloader.file` is defined.
