### ISSUE TITLE
Remember board and port for  each code-window

### ISSUE THREAD

**Issue by matsekberg** [arduino/Arduino#1482]
When using multiple boards simultaneously it would be nice if the window being verified/uploaded remembers the board and port setting for the code window.
Now one have to alter board and port settings when switching between two projects in two separate windows.

**Comment by Ghostbird** [comment]
Definitely needs this. It's completely unexpected and confusing that the two windows share the Board and Port setting. The two separate windows suggest two separate running instances of the program, but I guess that is not the case.

**Comment by per1234** [comment]
At least on Windows, it is possible to accomplish this if each window is a separate instance of the Arduino IDE. This is done by starting the Arduino IDE multiple times (by clicking the Arduino IDE shortcut or a sketch) rather than having multiple windows of the same instance, which happens when you use **File > New**, **File > Open**, **File > Sketchbook**, or **File > Examples**.

**Comment by Ghostbird** [comment]
Ah, thanks! That makes perfect sense. The operating system probably doesn't matter. It's just that you open an entirely new process tree. This happens in those cases where opening Arduino IDE shows the splash screen.

**Comment by JesseBusman** [comment]
I was mildly annoyed by this, and can confirm that having two seperate Arduino processes helps. It would still be nice if you could have a different board setting per IDE window, instead of per IDE process which is very unintuitive. (can't visually tell whether two windows belong to the same process)

**Comment by per1234** [comment]
This has been implemented in Arduino IDE 2.x. The board and port selection in each window is completely independent, without any need for the user to follow a special procedure to accomplish this.
