### ISSUE TITLE
Update PROGMEM reference page to recommend "const"

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/Arduino#1536]
The old AVR toolchain Arduino uses does not require "const" together with PROGMEM, but it accept const.  But newer versions do require const.

This old documentation should be updated to recommend coding practice that is forward compatible.

http://arduino.cc/en/Reference/PROGMEM

It might also be good to mention Arduino Due, which doesn't use AVR PROGMEM.

**Comment by cmaglie** [comment]
See also #2647 #2122

**Comment by Nantonos** [comment]
Where is the repository for the Arduino reference pages? I would submit pull requests for documentaton updates, except that the content does not seem to be in this repository.

**Comment by ffissore** [comment]
@Nantonos we are working on improving the way people may contribute to the documentation. Stay tuned

**Comment by Nantonos** [comment]
Hello Federico,

Wednesday, February 18, 2015, 8:43:20 AM, you wrote:

> @Nantonos we are working on improving the way people may contribute to the documentation. Stay tuned

Excellent, great news.

With 1.0.x it seemed that the documentation shipped locally and the
online documentation were different. Was that issue fixed now that
1.6.0 is out?



-- 
Best regards,
 Nantonos                            mailto:nantonos@epona.net

**Comment by cmaglie** [comment]
Yes, 1.6.0 has an updated snapshot of the documentation.

**Comment by agdl** [comment]
@Nantonos  here https://github.com/arduino/reference-en the repo. We are still working on the documentation but you can contribute :)

**Comment by Nantonos** [comment]
Hello Arturo,

Friday, February 20, 2015, 10:34:43 AM, you wrote:

> @Nantonoshere https://github.com/arduino/reference-enthe repo. We
> are still working on the documentation but you can contribute :)

Excellent, thanks for the pointer.


-- 
Best regards,
 Nantonos                            mailto:nantonos@epona.net

**Comment by agdl** [comment]
@Nantonos reference updated let me know if you have any suggstion or improvement so i can include them both online and in the new repo :)

**Comment by Nantonos** [comment]
Hello Arturo,

Friday, February 20, 2015, 1:05:18 PM, you wrote:

> @Nantonosreference updated let me know if you have any suggstion or
> improvement so i can include them both online and in the new repo :)

Looking on
https://github.com/arduino/reference-en/blob/master/Language/Variables/Utilities/PROGMEM.adoc
I see one use of const in an example, but no text recommending const
or explaining why it is needed on newer gcc versions.

It would also be good to see discussion of how this is an AVR feature
and not applicable (except as AVR emulation for legacy code) on other
architectures such as the SAM on Due. Because this has been a topic of
discussion:

http://forum.arduino.cc/index.php?topic=155158.0

and is a known compat issue
https://github.com/arduino/Arduino/issues/1317
(as that issue is closed I assume Due has an avr/pgmspace.h compat
layer now? if so, the PROGMEM page should discuss it.

Would you prefer that I fork this repo and submit pull requests, or discuss
improvements on this list?

-- 
Best regards,
 Nantonos                            mailto:nantonos@epona.net

**Comment by agdl** [comment]
@Nantonos i pushed online a new PROGMEM reference here http://arduino.cc/en/Reference/PROGMEM you can use it as template to improve the dosumentation. Please if you want to contribute fork the repo and submit a PR!

**Comment by agdl** [comment]
ok you can fork it now
