### ISSUE TITLE
Arduino IDE issues with scrolling through examples, libraries and boards

### ISSUE THREAD

**Issue by scottyanke** [arduino/Arduino#1548]
In the current IDE version (1.0.3 on up) there are issues with scrolling through the Sketch/Import Library and Tools/Board options.  If there are more options than can vertically fit on the screen, the latest versions of the IDE do not allow for scrolling to view the remaining options.  This started in 1.0.3 with the Import Library, and continued in 1.5.2.  The File/Examples scrolling works in both of those versions, but not in the latest on GIT.

The issue is related to the removal of the MenuScroller class.  By comparing the differences in the IDE versions I was able to identify that this class was being removed in the latest versions of the IDE.  Using a copy from an older version, I was able to add that class back into a local copy of the IDE, and update the Editor.java file to make use of it.  When I did that, the scrolling functions returned to the IDE.

I am running Arduino on a Linux Fedora 19 box with Java 1.7.  This problem is reproducible every time, when the number of libraries and/or boards is greater than what will appear on a vertical menu.  The problem can be avoided by altering the source code from GIT to add the MenuScroller source file back, and alter Editor.java to include the line MenuScroller.setScrollerFor(importMenu); in the appropriate locations.

The issue can also be created by removing the MenuScroller references from the source of the older code I have for the IDE.

**Comment by DavidAntliff** [comment]
Well, it's 2019 and I've just downloaded Arduino 1.8.9. I'm using it with Ubuntu 16.04 and the i3 window manager. In my case, the board list is too long and there's no way I can see to scroll down to the boards I can't see, and therefore I can't select them. Is there a workaround?

**Comment by facchinm** [comment]
@DavidAntliff scrolling on mousewheel/arrow keys was added to all the dropdowns long time ago, and it behaves well on all systems I tested it in (not tiled window managers though).
Maybe the dropdown component is not recognizing the "window" size and extends indefinitely, not showing the graphical scroll arrows.

**Comment by DavidAntliff** [comment]
@facchinm ah, one issue I had was that I didn't have a mouse or scrollwheel (using a track pad). After connecting a mouse the menu is much easier to navigate.

With up/down cursor keys though, it behaves very strangely. I have to move the highlight to the bottom row, then one press down, then up, then down again, to get the entire menu to scroll and make the next item available. Repeating this multiple times eventually moves through the entire list.

Actually I've just worked out what I need to do - I need to leave the bottom item selected and then **wait** - the menu then automatically scrolls without needing any key-presses. This wasn't obvious to me before because the bottom of the menu had disappeared off the bottom of my screen. With this information I am able to access the entire menu from a touchpad, provided I guess correctly where the bottom of the list is when it's off the display.

**Comment by Dreded** [comment]
as of 1.8.9 in manjaro KDE Plasma I have the same issue my examples,libraries and boards are all off screen and I can select them with the arrows if I can guess which is the correct one.
