### ISSUE TITLE
Standalone Arduino page is missing auto-reset circuitry

### ISSUE THREAD

**Issue by madbob** [arduino/Arduino#1562]
Original by Matt Howell:

I believe there is an error on the standalone arduino page. This is the link to the page I am referring to: http://arduino.cc/en/Main/Standalone

If you build this you will find it is not capable of uploading a sketch to the ATMEGA328 (in my case). There should be a 0.01uF capacitor between the RESET pin on the ATMEGA328 and the DTR pin on the USB breakout from Sparkfun. I assume the ATMEGA328 needs a reset signal prior to be able to ingest the new sketch. After adding this capacitor and connection I am able to successfully upload sketches.

**Comment by agdl** [comment]
Corrected this according to other isssues

**Comment by q2dg** [comment]
When it says: "Attention: This procedure works on Arduino 1.0.x software." should say ""Attention: This procedure works on Arduino 1.*X*.x software."  ??

**Comment by per1234** [comment]
@agdl there is no mention of the auto-reset circuitry on http://arduino.cc/en/Main/Standalone so I'm reopening this. Maybe the changes were never pushed to the website or they have been accidentally reverted?

I have added a note about auto-reset circuitry in my proposed revisions to the page (https://github.com/arduino/Arduino/issues/6484) but that's not a real solution for this issue. What really needs to happen is for the photos in that tutorial to be redone with the auto-reset circuitry added.

I am willing to do this but I would need assurances that if my work was acceptable it would be added to the website in a timely manner. The reason is that I will need to buy the recommended hardware and I get pretty picky about my photography so it's going to be a time consuming process.

Regarding the other two issues mentioned, let's keep this issue strictly to the topic of adding auto-reset circuitry to http://arduino.cc/en/Main/Standalone. Other subjects should be discussed in the appropriate issue report.

**Comment by per1234** [comment]
It seems this tutorial has been completely removed from Arduino's website so I'll close this as resolved.

For future reference, here is the archived copy on the archive.org Wayback Machine:

https://web.archive.org/web/20220201170335/https://www.arduino.cc/en/Main/Standalone
