### ISSUE TITLE
Hidden warning during compilation

### ISSUE THREAD

**Issue by lestofante** [arduino/Arduino#1728]
in brach 1.5.x avr-gcc is called passing argument -w, that hide all warning.
This is very bad as wanings help to find error in the code, especially if it is written by someone new to coding and the magic of pointers.

please, at least give a flag in preferencies to remove the evil -w flag.

thank you

**Comment by tomfelker** [comment]
I get that the Arduino libraries are not yet warning free, and you don't want to show errors to users.  But the -w means I can't even turn them on for myself with #pragma diagnostic.  This is incredibly frustrating.

It's been over a year.  Perfect is the enemy of good - nobody seems to be implementing optional warnings.  Just remove -w, so the warnings show up in verbose mode, and so that I can put

#pragma GCC diagnostic error "-Wall"

in my own code.

**Comment by mikaelpatel** [comment]
There is no excuse for poor software quality. The compiler warnings should be set at the highest possible level so that all potential problems are exposed. And then they should be corrected. 

I cannot stress the importance of this. 

Please introduce -Wall and -Wextra and then do the work. Suppressing and ignoring warnings is a very bad and unprofessional practice.

**Comment by ffissore** [comment]
@tomfelker and @mikaelpatel your concerns are clear and understandable. However we must keep in mind that Arduino is also and especially a learning tools. A warning caused by the core or some library and not by a sketch may scare a student.
Enabling warnings when verbose output is on may be an acceptable proposal. I'm going to write to the teachers mailing list

**Comment by mikaelpatel** [comment]
@ffissore 
I fully agree with not having warnings originating from the source code for the Arduino core in any released/delivered code and that might confuse students. The idea is to have the highest possible warning level and then remove all warnings before release. The warning level should be maintained to help students write better code and get as much help as possible from the compiler. 

I do understand that this initially is a lot of work to clean up all the warnings that are in libraries right now but after that phase the overall code quality will be so much better. I also believe that this will help students.

**Comment by tomfelker** [comment]
I completely understand that we don't want to have to explain why a particular type-punned pointer breaks strict anti-aliasing rules, or whatever, to newbies.  I am not saying warnings should be visible by default.  I just want, personally, to be able to see warnings in my own code, without having to locally build the Arduino IDE or install hacky wrappers around gcc (as StackOverflow suggests).  And that's currently technically impossible because of -w.  I think if you take that out, even if the output is still hidden, then it should be possible for me to just add pragmas to make warnings be errors in my own code, and set verbose mode on locally.

**Comment by ffissore** [comment]
The output is hidden if you keep verbose compilation output unchecked. Take a look at file > preferences. In order to enable all warnings you need neither to build the IDE nor to use hacky wrappers. Just edit file platform.txt and remove `-w` from `compiler.c.flags` and `compiler.cpp.flags`

**Comment by mikaelpatel** [comment]
@tomfelker 
Here is a link to the platform.txt that I am using in Cosa; https://github.com/mikaelpatel/Cosa/blob/master/platform.txt

The latest addition to the options is -mcall-prologues which turns out to reduce foot print further. 

Cheers!

**Comment by tomfelker** [comment]
Thanks, that's very helpful!  Removing all references to -w in my platform.txt allowed my pragmas to work.

And with verbose mode off in the preferences, as per default, it actually has no user-visible student-confusing effect.  So I'd be in favor of it being the default, but at least knowing where to set it is good enough for now.

**Comment by ffissore** [comment]
I've added a new preference "show all compiler warnings" that turns warnings on
Available as nightly builds in the next few hours

**Comment by lmihalkovic** [comment]
@mikaelpatel  
```
There is no excuse for poor software quality.
```
Except if you can hide it... Like in the case of the IDE itself. If the hardware/firmware had been as bad, this would never have taken off.
