### ISSUE TITLE
Path names problem in 1.5 IDE's platforms.txt

### ISSUE THREAD

**Issue by tchilton** [arduino/Arduino#2052]
Although it seems to work with avrdude, there are consistency problems in the platforms.txt file's handling of paths. All the paths in tools.avrdude have Linux forward slashes, which results in the path names having a mix of forward and backslashes on the Windows platform. This can be seen by turning on verbose mode for an upload or opening the platforms.txt

This will be a problem for other integrating other programmers as they will probably copy the avrdude section (like I did)

Suggest that the platforms.txt should have both .windows and .Linux constructs by default, or possibly the IDE performs some form of sanity check on pathnames before attempting to execute them - although differentiating paths and switches could be tricky !

**Comment by lmihalkovic** [comment]
Isn't it amazing that so much can be written about such a trivial issue with so little actual result!? This issue is not unlike the normalization step that exist in IP to ensure a consistent endian-ness accross the board.

**Comment by cmaglie** [comment]
> Isn't it amazing that so much can be written about such a trivial issue with so little actual result!?

@lmihalkovic, at least read the issue before doing such harsh comments.

This issue started from the false assumption that Windows only handle paths with backslash while is perfectly capable of handling path with both forward and backslash (even mixed). The OP failed to show a use case when the actual setup fails, so I'm closing this issue as "works for me".

**Comment by lmihalkovic** [comment]
```
This issue started from the false assumption that Windows only handle paths with backslash while is perfectly capable of handling path with both forward and backslash (even mixed). The OP failed to show a use case when the actual setup fails, so I'm closing this issue as "works for me".
```

@cmaglie Precisely! I was referring to the amount of discussion, proposal, opinions that got expressed around something as small as a path 'problem'. It would surely be nice if the code/configs were more consistent when dealing with paths, but it can be hapily ignored due to the foregiveness of Windows.

IMHO there are many more entries showing a similar pattern of long discussions with elaborate arguments on various sides of mis-diagnosed 'problems', which prompt me to regularly say that your codebase is full of opportunities for useful improvements when your peel-off the layers of misunderstanding around these issues/features. Or in the words of someone much more eloquent: ```it is not that they cannot see the answer, it is that they cannot see the question```
