### ISSUE TITLE
5 min with serial monitor results in OutOfMemoryException

### ISSUE THREAD

**Issue by willie68** [arduino/Arduino#2233]
I have to debug some longer running tasks. But after some minutes i get an OutOfMEmoryException than the IDE is not resonding. I think it's the buffer for the serial monitor text area. 
As a workaround: Is there a possibility to clear the text area? Maybe an autoclear on low memory would help. 
Setting the memory params of the IDE doesn't help, because this would only postpone the problem. And without the autosave feature this bug is more serious. I have again lost some code because of this. 
Arduino IDE 1.5.7, SerialMOnitor with 57600 Baud.

**Comment by PaulStoffregen** [comment]
I should mention some bugs have turned up with the serial monitor using Teensy, since I added this speedup code.  At this point, I don't have any good info, other than this simple warning that unexpected bugs have surfaced.  They may be related to other changes, or they may be due to this speedup, or perhaps some complex interaction.

When I know more, I'll post again.  At this early stage, I just want to let you know some problems have surfaced as more users have tried this code, which I didn't in my initial testing.
