### ISSUE TITLE
Option to display line numbers along left vertical axis [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#227]
This is [Issue 227](http://code.google.com/p/arduino/issues/detail?id=227) moved from a Google Code project.
Added by 2010-04-02T21:38:58.000Z by [n.mcdona...@gmail.com](http://code.google.com/u/109221980925320237021/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium
### Original description

**What change would like to see?**
The IDE should have the option of displaying line numbers along the left 
side of the text area.

**Why?**
Because every other major IDE does.  It's especially nice when viewing 
error messages

**Would this cause any incompatibilities with previous versions?  If so, how**
**can these be mitigated?**
No

**Comment by TGC-TECH** [comment]
why won't they fix this, It is really annoying not have line numbers along the side when dealing with long programs like Marlin

**Comment by per1234** [comment]
I labeled it that way because it says "Closed (WontFix)" in the text added during the import. I did that as part of a bulk run through the unlabeled issues and I guess I didn't take the time to look at this issue beyond that text because it should have been obvious to me that the wontfix label is inappropriate. I've removed the label as well as the "Closed (WontFix)" to prevent future confusion.

**Comment by matthijskooijman** [comment]
Ah, I had missed the wontfix tag in the imported issue. Thanks for clarifying!
