### ISSUE TITLE
Due HardwareSerial Transmit not interrupt-driven...

### ISSUE THREAD

**Issue by WestfW** [arduino/Arduino#2271]
I would have expected that the Due Serial ports would be interrupt driven for both transmit and receive, just like the AVR serial ports.  But in fact the Due transmit code (UARTClass::write and USARTClass::write uses busy-loops:

size_t USARTClass::write( const uint8_t uc_data )
{
  // Check if the transmitter is ready
  while ((_pUsart->US_CSR & US_CSR_TXRDY) != US_CSR_TXRDY)
    ;

  // Send character
  _pUsart->US_THR = uc_data ;
  return 1;
}

**Comment by alirezasafadri** [comment]
Hi
I am new to Arduino IDE, ARM and github; although I have few years of programming experience with AVR Mega in C.
I understood that you guys have solved the problem with serial library of Arduino due. Now, the only thing that I do not understand is how I can implement what you have done in my Arduino IDE. I am using 1.6.3 and I do not have sam directory. Should I downgrade to your version? 
So could you please help me and I am really sorry if my question are very noob. If you are busy feel free to just give me keywords, I will read about them till I figure out a solution.
Thank you very much.

**Comment by collin80** [comment]
The changes have been merged into the 1.6.x branch so you shouldn't need to
do anything to get and use them. You do still have a sam directory but they
moved it around. You should be able to search the arduino forums for the
new location.

**Comment by alirezasafadri** [comment]
Hi Collin 80
I figured it out, I had a mistake in my code which was sending too much info through the port due to the mistake. I fixed it and noticed that it interrupt is used in serial library. That is why I removed my comment so that hopefully you guys won't waste your time answering my question. But thank you very much you actually answered it and I really appreciate that specially for the directory clarification. Sorry if I removed my comment and you had to add it again.
thank you very much,
Ali
