### ISSUE TITLE
java memory options not working.

### ISSUE THREAD

**Issue by willie68** [arduino/Arduino#2358]
Due to some testing of issue #2233 i try to set some other memory parameters for the java vm. (-Xms and -Xmx...)
As i can see in the preference.txt file, it's possible to set an option part as i can set initial and max memory for the vm.
```
run.options=-Xms256m -Xmx1024m
run.options.memory=false
run.options.memory.initial=256
run.options.memory.maximum=256
```
There are 2 preferences.txrt files. One in the arduino install directory (which seem's to be the default one) and one in <user>/AppData/Roaming/Arduino15/. But both will not work in any case. I have tried many different options, run.options.memory=false or run.options.memory=true
run.options= or run.options=-Xms256m -Xmx1024m but nothing changes the default behavier with -Xms128m and -Xmx128m...

**Comment by WhiteElf** [comment]
Still having the same issue with 1.6.0.

Windows 7 64bit 16gb RAM.

Can't use any of the Open/Sketchbook/Examples options.  Always get:
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

Executing this from the command line instead of running the loader solves the issue:
"D:\Utilities\Arduino\java\bin\javaw.exe" -Xms1024m -Xmx1024m -classpath "lib;lib\arduino-core.jar;lib\pde.jar;lib\jna.jar;lib\ecj.jar;lib\jssc-2.8.0.jar;lib\commons-codec-1.7.jar;lib\commons-exec-1.1.jar;lib\commons-httpclient-3.1.jar;lib\commons-logging-1.0.4.jar;lib\jmdns-3.4.1.jar;lib\jsch-0.1.50.jar" processing.app.Base

**Comment by WhiteElf** [comment]
Arduino-PR-2712-BUILD-197 resolves the heap space issue when attempting to load Sketch.  It doesn't read the memory setting in the preferences.txt file, however it does work with the arduino.l4j.ini file.
