### ISSUE TITLE
File > Examples menu issues when library is installed to sketchbook with same name as bundled library

### ISSUE THREAD

**Issue by JulyJim** [arduino/Arduino#2401]
I do not want to duplicate things - but here is my latest observation ( 1.0.6) on Windowze XP 
When "Preferences - Sketchbook location" directory is set to \Documents and Settings... Arduino\library and when SAME library directory exists in  \Program Files\ ....libraries then IDE File \ Examples will show two libraries of same name ( for example LiquidCrystal ) under DIFFERENT menu separators. 
The submenus will show correct sublibraries names - they are different in case of LiquidCrystal. One for I2C and the other "normal" data interface.

The issues is - when "normal" data interface sample code menu  is selected - the compiler will use the library set in the Preferences. 

Second and related issue - when you change the  Preferences - Sketchbook location directory to \Program Files\Arduino ... libraries BOTH LiquidCrystal menus will now show ONLY the \Program Files\Arduino ... libraries submenus and compiler will compile expected library when either is selected.

**Comment by per1234** [comment]
>When "Preferences - Sketchbook location" directory is set to \Documents and Settings... Arduino\library and when SAME library directory exists in \Program Files\ ....libraries then IDE File \ Examples will show two libraries of same name ( for example LiquidCrystal ) under DIFFERENT menu separators.

I do see some odd things happening in the **File > Examples** menu immediately after I set the sketchbook folder to the libraries folder. However, this is resolved after restarting the IDE and there is no legitimate reason for doing such a thing, so I don't think it's worth considering a bug.

>The issues is - when "normal" data interface sample code menu is selected - the compiler will use the library set in the Preferences.

A sketch being an example of a library has no influence over [dependency resolution priorities](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#dependency-resolution). It might seem logical for the library that contains the example to be given priority. However, examples are most often only demonstrations of how to use the library in your own sketches, and the same priority wouldn't apply once you tried to use the same code in your own sketch. So this would actually lead to to very confusing inconsistency between examples and sketches.

>Second and related issue - when you change the Preferences - Sketchbook location directory to \Program Files\Arduino ... 
...
and compiler will compile expected library when either is selected.

Likely this is the expected behavior resulting from [location priority](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#location-priority).
