### ISSUE TITLE
Multiple white spaces can not be used in keywords.txt

### ISSUE THREAD

**Issue by Myriads** [arduino/Arduino#2435]
If multiple white spaces are used to align KEYWORDs in keywords.txt file, then KEYWORDs are not recognized and not working in Arduino IDE.

**Comment by ffissore** [comment]
keywords columns are tab separated

**Comment by Myriads** [comment]
If PApplet.splitTokens(line) is used instead of PAapplet.split(line, '\t'),
then any white space can be used in Keywords.

2015-05-12 17:09 GMT+09:00 Federico Fissore <notifications@github.com>:

**Comment by ffissore** [comment]
IMHO tabs are a far safer separator, whatever the contents of the file is (almost)

**Comment by Myriads** [comment]
If multiple tabs are used for indentation, Keywords do not work.

**Comment by BrentWilkins** [comment]
@ffissore Will you please expand on the issue with splitting on white-space?  Makefiles are the only other example I can come up with that requires tabs.  I feel the problem isn't as bad as the way the single-tab-only files look.

**Comment by bperrybap** [comment]
Why is this a don't fix item?
This seems very silly.
The separator should be white space rather than <tab> and white space is white space.
tab or space should not matter.
The older IDEs would not accept more than a single tab. Someone went in and modified the IDE to support multiple tabs, and that would have been a good time to support using the space as a separator.

At this point, it seems like it is more of an issue obstinacy than a technical issue.

**Comment by per1234** [comment]
See https://github.com/arduino/Arduino/pull/6693
