### ISSUE TITLE
Arduino IDE on High DPI 

### ISSUE THREAD

**Issue by timhannah1988** [arduino/Arduino#2532]
I have recently purchased a Microsoft Surface Pro 3 which has a High DPI screen. I installed the IDE and loaded it for the first time and it appears that the gui doesn't support DPI scaling as the menus and text is tiny and unreadable. I am having to use the device with a lower resolution so that I can use the software properly. 

Is there any support i am missing or is it simply not supported yet. If the latter please can this be considered on future builds

**Comment by j40climb** [comment]
I'd like to see a fix for this as well. I have the same problem with my Samsung Ativ Book 9+. With all the new high DPI displays, this will become more of an issue.

**Comment by PaulStoffregen** [comment]
This seems more like a Java question.  Arduino's IDE uses the Java JRE to do all those menus, so the bigger question is whether there's some way to tell the JRE to render them with more pixels?

**Comment by j40climb** [comment]
Where is the UI code in the repro? Im knew to this project, but I'm willing
to dig in and look for a fix.

**Comment by PaulStoffregen** [comment]
> Where is the UI code in the repro?

Here:

https://github.com/arduino/Arduino/tree/ide-1.5.x/app/src/processing/app

Please be aware there are 4 branches.  Do NOT use the default "master" branch, because that's the code for version 1.0.x, which is being phased out.  If you use that code, you'll have to redo everything to get it accepted.

Work within the "ide-1.5.x" branch, which is the latest version.

**Comment by 5YHgB** [comment]
![naamloos](https://cloud.githubusercontent.com/assets/11330859/6503756/371b158c-c330-11e4-80dd-61df0af0d896.png)
I have this problem too. On my Lenovo Yoga 2 Pro the interface looks very small. Please fix.

**Comment by PaulStoffregen** [comment]
If anyone is still following this issue and cares about Arduino gaining graphics and font scaling, please test the build on pull request #2776

**Comment by choidamdam** [comment]
Any update on this? I'm using two windows laptops with HiDPI (one for work, one for home) displays and this is very annoying issue. 

Maybe we have to swich from Swing to JavaFX which support HiDPI better. (http://news.kynosarges.org/2015/06/29/javafx-dpi-scaling-fixed/)

**Comment by ffissore** [comment]
JavaFX and Swing are two totally different beasts. They can integrate with each other, but it's more about rewriting the IDE that switching

**Comment by Sembazuru** [comment]
I also value this issue. I can work-around the editing area by using 18pt font, but that only works in the actual code window. The Library and Board managers are almost unusable due to the small font being used on my high DPI monitor. Windows magnifier helps, but that is a kludge not a fix.

For reference, I'm on Windows10 64bit, and still see this behavior on IDE v 1.6.6.

**Comment by thoughtfix** [comment]
+1  I am using the same trick as Sembazuru by boosting my font size, but it's still a miserable experience trying to code from a Surface Book.

**Comment by mkstephenson** [comment]
I have the same problem, got a 4k 27" screen and you really have to squint to see any menu text

**Comment by cmaglie** [comment]
I'm closing this one, please let's continue the discussion on #4376.

**Comment by roman-ku** [comment]
@thoughtfix Same story here on a surface book.

**Comment by spacedSparking** [comment]
![arduinohighdpi](https://user-images.githubusercontent.com/24445174/35260879-7ac5082a-ffc2-11e7-98e4-693e3f1a7773.png)

This is a life saver! Adjusting the scaling factor to 200% worked like a charm. I am currently running `ant run` within the `/Arduino/build/` directory from the terminal. For the total git noob here, is it possible to install/make the High DPI Arduino IDE as an bona fide application instead of following the [build instructions](https://github.com/processing/processing/wiki/Build-Instructions)?

**Comment by cmaglie** [comment]
Sure, you can download the latest version here:

https://www.arduino.cc/en/Main/Software

**Comment by delucaa** [comment]
On my surface pro 4 using the 1.8.5 version in the code window using the size 18 you can see the characters well but the window settings, libraries, you see small while in additional URLs the text is not seen almost at all
![url](https://user-images.githubusercontent.com/5032254/35770025-71a7adaa-0914-11e8-95bc-da9741f3958c.jpg)

**Comment by spacedSparking** [comment]
@delucaa Have you tried rebooting? I noticed the same issue before a restart, but everything looks properly scaled for me now.

**Comment by delucaa** [comment]
yes but nothing ... I also tried to reinstall the program but nothing ..

**Comment by cmaglie** [comment]
@delucaa please open a new issue, this should be an easy fix.
