### ISSUE TITLE
"new" button behaviour is different from "file -> new"

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#2685]
Former will close the current sketch and replace it with a blank one. Latter will start a new sketch in a new window
Stick with the latter behaviour

**Comment by damellis** [comment]
I believe this was an intentional design decision that we inherited from Processing. They may have changed their minds about it, or we might prefer a different behavior -- but this isn't really a bug. The button is within the window and the new sketch is as well; the menu (on Mac in particular) is outside the window and so is the new sketch.

**Comment by mastrolinux** [comment]
I can confirm this is different from what processing does (just tested). Processing does open a new window if you press the new icon and if you click on file -> open (same behaviour). We are doing something different. We have different behaviours for the same "new" action. This is confusing the users. Will ask UX designer about it.
