### ISSUE TITLE
Compiler does not recognize changes in libraries

### ISSUE THREAD

**Issue by moritz1671y** [arduino/Arduino#2704]
While debugging a very simple library i made, i fixed an error in the library code (.cpp) but the compiler did not update the library and tried to use the precompiled file with the error still in it. Even after restarting the computer the precompiled file was still used. An option to clear the precompiled files and recompile everything would be useful.

**Comment by ffissore** [comment]
Can you share the whole verbose output genereted by the IDE?

**Comment by moritz1671y** [comment]
I had multiple errors. The main problem is that i am not able to tell the
IDE to recompile the library files.
Am 26.02.2015 20:30 schrieb "Federico Fissore" <notifications@github.com>:

**Comment by ffissore** [comment]
That's clear. However without additional details we can't reproduce the
problem. First step is to share the whole verbose output, indicating the
library files that are not compiled

**Comment by PaulStoffregen** [comment]
The IDE automatically recompiles library files that have changed.

**Comment by moritz1671y** [comment]
In my case it didn't. Is that a recent addition to the IDE?
Am 02.03.2015 11:34 schrieb "Paul Stoffregen" <notifications@github.com>:

**Comment by ffissore** [comment]
It is its default behaviour since the beginning (as far as I know). Did you manage to produce the verbose output I was asking for (file, preferences, verbose compile)? The ideal output is one generated right after having started the IDE, with you pointing at the row where your library is compiled and some code that shows that the IDE is using a previously compiled version

**Comment by PaulStoffregen** [comment]
It started here, in late 2011.  Before this, Arduino always recompiled all files.

http://code.google.com/p/arduino/issues/detail?id=638

I believe Arduino 1.0.1 was the first to merge this feature.

**Comment by moritz1671y** [comment]
@Frederico Fissore I have not worked with the IDE since i discovered the
issue but i will send you the requested data as soon as I get  to it again.

**Comment by moritz1671y** [comment]
@Federico Fissore I am sorry for misspelling your name.

**Comment by ffissore** [comment]
Not a problem. Can't wait to see that data

**Comment by moritz1671y** [comment]
/Documents/Arduino/libraries/SSDcontrol/SSDcontrol.cpp:95:28: error: no 'void SSDcontrol::SSDreset()' member function declared in class 'SSDcontrol'
 void SSDcontrol::SSDreset () {
                                              ^

Line 95 in SSDcontrol.cpp: void SSDcontrol::SSDreset() {
in SSDcontrol.h I declared: void SSDreset(); as public

**Comment by cmaglie** [comment]
Hi @moritz1671y

since there is a compile error surely there are no object files that the IDE can reuse.
From the few information you provided it looks like an error in your code instead.

If you are really sure that this is a bug in the IDE, you should post:

* the **full** content of SSDcontrol.cpp and SSDcontrol.h
* your **full** sketch 
* the **full** verbose compile output (remember to activate the "verbose compile" option from the preferences) 

This should be enough to allow us to reproduce the issue (remember: if we can't reproduce the issue we can't solve it!).

You can use http://gist.github.com to copy and paste if needed.

Thanks!

**Comment by agdl** [comment]
Please reopen this if needed
