### ISSUE TITLE
avr/dtostrf.h No such file or directory in Arduino 1.6 with plot.ly library.

### ISSUE THREAD

**Issue by jecrespo** [arduino/Arduino#2898]
Regarding to this issue https://github.com/plotly/arduino-api/issues/38, you get this error:
fatal error: avr/dtostrf.h: No such file or directory

The example complies with 1.0.6 version despite of avr/dtostrf.h doesn't exists.

dtostrf() is a avr-libc function but in Arduino IDE version 1.6 you can find in path C:\Program Files (x86)\Arduino\hardware\arduino\sam\cores\arduino\avr the files dtostrf.c and dtostrf.h.
Perhaps is a change in avr-libc new version included en Arduino 1.6?

**Comment by cmaglie** [comment]
Just remove the `#include <avr/dtostrf.h>`.

The `avr/dtostrf.h` in the `sam` folder is an implementation of `dtostrf` for the Arduino Due that uses the SAM3X processor (a completely different architecture than AVR). Since you talk about 1.0.6 I guess you're compiling for AVR so you don't need to include `avr/dtostrf.h` at all.

It works on 1.0.6 because the compiler treat the "missing include file" as a warning and not as an error. On 1.6.x things have changed and now if an include file is missing the compiler generates an error.
