### ISSUE TITLE
Compiler "temp" files - Question / configuration or a  bug?

### ISSUE THREAD

**Issue by VaclavSal** [arduino/Arduino#2971]
With about 30 h / cpp files being compiled into windows ...Temp directory I have noticed they DO NOT get erased / deleted and the directory keeps growing after each compile. 
Is this normal ? 

I am still happy  running 1.6.0 Nov issue.

**Comment by ffissore** [comment]
It's a bug

**Comment by mschlenker** [comment]
It's a feature. 

On Linux people are used to have /tmp erased upon boot time. I like being able to enable verbose compile messages, fish out the hex files out of /tmp after compiling and flash them to several AVRs - this is quite faster than compiling the one sketch over and over again...

Of couse it's a bug, but i suggest adding 

[_] Do not clear temporary files after upload

to the configuration interface to enable examining the compiled binaries or fishing out the hex file afterwards.

**Comment by matthijskooijman** [comment]
The intention, IIRC, is that the temp files are deleted by the IDE when it quits. This prevents recompilation of files during a single session, doesn't clutter the temp directory, but also allows taking out the hex or elf file you just compiled. This seems like the proper way to handle this to me. If it doesn't work like that on Windows, it's a bug.

**Comment by ffissore** [comment]
Indeed. [This code](https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/BaseNoGui.java#L136-136) tells the same story. However `deleteOnExit` is not recursive, hence the bug.

**Comment by mschlenker** [comment]
Ah, I see, of course, since 1.5.x the intention is only to recompile changed files. The temporary directory is used for all sketches in one session. Thus it would also make sense to clean up upon start for the  case the Arduino IDE crashes or gets killed - and of course for all those people with several dozen MB old sketches lying in %TEMP%. Determining which buildNNNNNNNNNNNNN.tmp was created by Arduino should by quite easy by looking on the filenames found there.

**Comment by mschlenker** [comment]
Please consolidate with 2724 https://github.com/arduino/Arduino/issues/2724

**Comment by ffissore** [comment]
See #2980 for a proposed fix
