### ISSUE TITLE
I2C LCD display and reset function on Uno

### ISSUE THREAD

**Issue by pierrotm777** [arduino/Arduino#3403]
I use a LCD 40x20 sainsmart .
It run very well, but sometime, when i reset my Uno board, the LCD don't reset always! I must to push several time the reset button.
I don't use actually the 2 R pullup that I2C needs !
Is an hardware issue or IDE ?

Thanks for your help !!!
PS. This issue exist with all IDE versions...

**Comment by agdl** [comment]
@pierrotm777 the Arduino Wire library uses the internal pull-ups resistors instead of two physical resistors. These pull-ups are activated when you call the Wire.begin(); before calling this, you have two open drain drivers that are floating and so you don't have a certain behaviour. To solve this for sure use the physical resistors.
