### ISSUE TITLE
[Library Manager] Some libraries by panStamp

### ISSUE THREAD

**Issue by dberenguer** [arduino/Arduino#3419]
The following libraries were not added into the Arduino Library Manager due to a naming-related issue.:

https://github.com/panStamp/swap
https://github.com/panStamp/sram
https://github.com/panStamp/mma8652

This issue has been fixed.

On the other hand, the "thermistor" library was renamed to "THERMISTOR" in library.properties just when you were updating your database:

https://github.com/panStamp/mma8652

Could you please remove "thermistor" (lowercase) from your records?

Thanks again,

**Comment by ffissore** [comment]
Added. Thanks! Lib "thermistor" (lowercase) is still there because you left the tag on your repo. No further manual intervetion will occur: please read https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#sorry-i-did-something-wrong-how-can-i-change-or-unpublish-an-already-published-library and wait until Sunday
