### ISSUE TITLE
Lilypad Arduino - Wrong baudrate config

### ISSUE THREAD

**Issue by rafaelmdribeiro** [arduino/Arduino#3477]
When we set the serial baudrate with 9600, the terminal shows correct only at 19200.

**Comment by Chris--A** [comment]
This, I assume is due to the lillypad using the internal 8Mhz clock, whereas the Uno has a 16Mhz clock (twice the speed).

Have you got lillypad selected in the 'boards' list?

However at first glance, it appears in code that the 8mhz isn't taken into account. I'd assume that all your timing functions will be halved too. `millis()` reading 500 would actually be a full second (1000)

**Comment by agdl** [comment]
Waiting for feedback for too long, I'm closing this. Reopen if needed.
