### ISSUE TITLE
Sketches are saved with non-native line endings. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#348]
This is [Issue 348](http://code.google.com/p/arduino/issues/detail?id=348) moved from a Google Code project.
Added by 2010-09-12T20:14:06.000Z by [DrZip...@gmail.com](http://code.google.com/u/103756129429363622233/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

Create a new sketch on a Windows system, and look at the resulting .pde file:

[heavyweight:~/Public/Arduino/sketch_sep12a] msmith% cat sketch_sep12a.pde 
#include <test.h>
#include <othertest.h>
[heavyweight:~/Public/Arduino/sketch_sep12a] msmith% hexdump -C sketch_sep12a.pde
00000000  23 69 6e 63 6c 75 64 65  20 3c 74 65 73 74 2e 68  |#include <test.h|
00000010  3e 0a 23 69 6e 63 6c 75  64 65 20 3c 6f 74 68 65  |>.#include <othe|
00000020  72 74 65 73 74 2e 68 3e  0a 0d 0a                 |rtest.h>...|
0000002b

Note that individual lines are separated with LF, whereas on a Windows system, this should be CR LF.

Note also that the file ends in CR LF, suggesting that the code that saves the file has considered the entire contents of the file to be a single line.

This seems to be borne out in that Base::save calls PApplet::saveStrings, where the latter expects an array of strings, each of which is written as a line to the file, but the former calls it with:

  static public void saveFile(String str, File file) throws IOException {
    File temp = File.createTempFile(file.getName(), null, file.getParentFile());
    PApplet.saveStrings(temp, new String[] { str });

which constructs an array of just one string.

The upshot of this is that Arduino creates text files with inconsistent line endings; most lines are terminated with LF, but there is a single CR LF appended to the end of the file.  This in turn means that tools such as Subversion which expect (in some configurations require) native line endings in files will refuse to process any file saved by Arduino.

Experiments show that in addition, if a file is created using another Windows editor that produces native line endings, the Arduino editor will replace these with LF when the file is saved, causing most version control systems to consider the entire file modified.

The correct fix would seem to simply involve generating the correct array of Strings when passing the sketch either to Base::saveFile, or when Base::saveFile calls PApplet::saveStrings.

**Comment by ppescher** [comment]
This issue should be reviewed and fixed.
I don't really know why, but it is the cause of very weird runtime behavior.
I have a project that involves GSM/GPRS and if line endings were mixed CR+LF in some file and only LF in some other ".ino" file in the same folder, then some AT command is refused by the modem, even if the printed string looks the same.
I was not able to track what's going on, but just saving all the files from inside the Arduino IDE (v1.6.4) was enough to fix that.
There were no build errors in any case, only runtime behavior was different.
See https://github.com/geolink/opentracker/pull/27

**Comment by matthijskooijman** [comment]
@ppescher I can't really think of any way where the file's line endings affect the resulting binary. AFAIK you cannot actually include line endings into string, for example (if you use line continuations, the line ending will not be present in the string I think?). Also, if the line ending type is relevant, won't that just mean that even is this issue is fixed, your sketch works only when compiled on Windows? It sounds like you should be investigating what change causes the breakage of your code exactly.

Not sure what @ffissore's plan for this ticket was, though, since he added a milestone but also a wontfix label?

**Comment by ppescher** [comment]
Thanks @matthijskooijman 
I know it looks crazy, because I spent quite a few days trying to understand what was going on. Unfortunately I had no time to investigate further, but I will as soon as I find some time.
I'm sure this things will bite me again, when I expect it the less, if it doesn't get fixed.
The only thing I was able to confirm is that the wrong runtime behavior disappeared when I made sure all the files had LF line endings. I briefly looked for some string literals that could be affected, but could not see any.
It must be more subtle (or stupid) than it seems. :)
I also confirm all the files saved by the IDE on a Windows platform have an LF separator between lines, except the last which is CRLF terminated.
