### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by ffissore** [arduino/Arduino#3653]
https://github.com/arduino/Arduino/wiki/Building-Arduino contains outdated and wrong instructions.

**Comment by NicoHood** [comment]
https://github.com/arduino/Arduino/issues/3638

**Comment by per1234** [comment]
Significant changes have been made to the documentation since this was opened and there are no specifics about what the "outdated and wrong instructions" might be so that I could check whether they still exist. I recently followed the Linux instructions and didn't have any problems.

So I'm going to go ahead and close this as fixed.
