### ISSUE TITLE
Inconsistencies between information showed in Library Manager and in web doc

### ISSUE THREAD

**Issue by q2dg** [arduino/Arduino#3875]
* AudioZero library can't be found in Library Manager!!!

* https://www.arduino.cc/en/Reference/HID page (which is the destiny of "See more" link of HID library when showed in Library Manager) doesn't exist. *(On the other hand, what's that library??...is it based on https://github.com/NicoHood/HID/tree/dev_2_4?? Does it deprecate Keyboard and Mouse libraries?...)*

* RTCZero library is called "RTC" on documentation (https://www.arduino.cc/en/Reference/RTC)

* USBHost library is described as "Due only" in Library Manager but in documentation is said it's compatible with Zero too.
 
* EEPROM library is described as "All boards except Due" in Library Manager but it should say "All boards except Due and Zero

**Comment by agdl** [comment]
Ho @q2dg 
* AudioZero has been added to library manager as you pointed out;
* this can be asked to @facchinm 
* you are right, but this is because in the future we want to have an homogeneous RTC library for RTCs in general. In this way we have something pre-build
* added Zero to the README;
* added Zero to the README;

**Comment by q2dg** [comment]
Thanks a lot ! I'll close this issue and will open another one remembering to Martino the missing https://www.arduino.cc/en/Reference/HID page , then.
