### ISSUE TITLE
Please add json-streaming-parser library to the Library Manager

### ISSUE THREAD

**Issue by squix78** [arduino/Arduino#4025]
Hi 

Please consider adding my library json-streaming-parser to the libraries managed by the Library Manager. The github repo is here: 
https://github.com/squix78/json-streaming-parser/

Kind regards,
Daniel

**Comment by cmaglie** [comment]
I've added the library to our fetch-list but, in order to get published in the library manager, you must **tag a release**: please read carefully https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Once you add a tag, the library should be automatically published within an hour (just wait that our hourly job runs).
