### ISSUE TITLE
Remove RobotIRremote library

### ISSUE THREAD

**Issue by PaoloP74** [arduino/Arduino#4040]
The RobotIRremote library continues to create problems with the installation of the homonymous library irRemote.
Can you delete from installation of IDE 1.6.6 the RobotIRremote and make it optional?
It would be downloaded only by those who own the Arduino robot.

"Translated with Google" :-/

**Comment by ffissore** [comment]
This should be fixed in recent IDEs. Can you give some evidence of such problems?

**Comment by PaoloP74** [comment]
Recently --> http://forum.arduino.cc/index.php?topic=356077.0
IDE select the wrong library
> Multiple libraries were found for "IRremote.h"
> Used: C:\Program Files (x86)\Arduino\libraries\RobotIRremote
> Not used: C:\Users\Lorenzo\Documents\Arduino\libraries\Arduino-IRremote-master
> Errore durante la compilazione

**Comment by q2dg** [comment]
Well, in hourly build from 29-10-2015 2:26  "Esplora", "Robot Control", "Robot IR Remote", "Robot Motor" and "TFT" libraries appear installed by default. I think there libraries should be removed to Library Manager.

**Comment by PaoloP74** [comment]
:+1:

**Comment by PaoloP74** [comment]
Up!

**Comment by per1234** [comment]
If you change the folder name from C:\Users\Lorenzo\Documents\Arduino\libraries\Arduino-IRremote-master to C:\Users\Lorenzo\Documents\Arduino\libraries\IRremote then the IDE will select the correct library because the include filename matches the folder. If you use Library Manager to install IRremote then it will automatically have the correct folder name. However, it seems only logical that if multiple files that match the include are found and none of them are in a folder that matches the filename then the normal include priorities should apply. In this case the file in the sketchbook folder should have higher priority than the one in the IDE install folder but this is not the case in your example. I seem to remember this idea already having been discussed in another issue and rejected. I did notice that if you do:
```
#include <IRremoteInt.h>
```
you get(using hourly build):
```
Multiple libraries were found for "IRremoteInt.h"
 Used: E:\Stuff\misc\electronics\arduino\libraries\IRremote
 Not used: C:\Program Files (x86)\arduino-nightly\libraries\RobotIRremote
```
or with your folder name:
```
Multiple libraries were found for "IRremoteInt.h"
 Used: E:\Stuff\misc\electronics\arduino\libraries\Arduino-IRremote-master
 Not used: C:\Program Files (x86)\arduino-nightly\libraries\RobotIRremote
```
So it's fairly random which library is used when the include filename doesn't match any library folder name.

**Comment by PaoloP74** [comment]
Can you delete from installation of next IDE 1.8.4 the Robot IR remote?

**Comment by cmaglie** [comment]
I cannot remove it from the bundle (for UX reasons) but I've renamed all the includes from `*IRremote.h` to `Robot*IRRemote.h`, this should fix all the conflicts once for all.
