### ISSUE TITLE
Board manager preferences URL doesn't take consider file://

### ISSUE THREAD

**Issue by aethaniel** [arduino/Arduino#4098]
While doing the setup for a given package, having the opportunity of using local URL file:// would be highly useful instead of pushing the (maybe wrong) files to a server.

Is it possible to obtain this?

**Comment by ffissore** [comment]
Yes we can add file:// support. In the meantime, you may want to rename your `package_myboard_index.json` file to `test_package_myboard_index.json`. The IDE will load that file as it was downloaded. Maintainers name protection still applies: because your test json file is not signed, you won't be able to use `arduino` or `Intel` platform names

**Comment by aethaniel** [comment]
Hi @ffissore, I have put test_package_....json file in /Arduino15 and it is indeed parsed.
Everything worked well after copying the corresponding package archive in 'staging' subfolder.

Thanks for the dev tip!

**Comment by ffissore** [comment]
Next hourly build will support file:// protocol as well. http://www.arduino.cc/en/Main/Software#hourly Thank you for the proposal
