### ISSUE TITLE
Document character functions. [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#424]
This is [Issue 424](http://code.google.com/p/arduino/issues/detail?id=424) moved from a Google Code project.
Added by 2010-12-04T04:53:09.000Z by [dmel...@gmail.com](http://code.google.com/u/107726014984682000895/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-0022, Component-Docs

### Original description

Document the new functions in WCharacters.h like isAscii(), isDigit(), etc.

**Comment by agdl** [comment]
@cmaglie @ffissore @matthijskooijman  
They are used in this basic example 
https://github.com/arduino/Arduino/blob/master/build/shared/examples/08.Strings/CharacterAnalysis/CharacterAnalysis.ino

Do you want on-line pages that explain them?

**Comment by cmaglie** [comment]
Yes, the original request on google code was to create docs page.

**Comment by agdl** [comment]
Where? In the Reference Home Page?

**Comment by cmaglie** [comment]
Yes (I guess...)

/cc @damellis @tigoe

**Comment by tigoe** [comment]
Can you give me a bit more context?

**Comment by cmaglie** [comment]
This is an old issue from google code:
http://code.google.com/p/arduino/issues/detail?id=424
that continued here:
https://github.com/arduino/Arduino/issues/424

@agdl wants to know it the requested functions (isAscii(), isDigit(), etc.) should be documented and added to the main reference page. (I guess yes, but not sure)

**Comment by tigoe** [comment]
yes, they should.

t.

**Comment by agdl** [comment]
Instead of having 13 new pages and since we have an example that shows how to use these functions, I added all the functions in the reference home page

https://www.arduino.cc/en/Reference.HomePage

Under the new category Characters

And commented all the functions in the same page:

https://www.arduino.cc/en/Reference/CharacterAnalysis

In which the example is also shown.

Let me know if it is acceptable and if so close this very old issue please!

**Comment by agdl** [comment]
I'm closing this. If there any further doubts or request please reopen it.
