### ISSUE TITLE
indexOf() returning wrong value in compound statement

### ISSUE THREAD

**Issue by richw8341** [arduino/Arduino#4269]
The expression       if(n=indexOf.someString("text")>=0)..........
will not return the correct index of "text"

This expression does work

                          n=indexOf.someString("text");
                          if(n>=0)............

**Comment by VogonJeltz** [comment]
as strstr is a standard C lib function I would suggest to try the following as a workaround (and the syntax is IMO a little more C- compliant...):

~~~
int16_t  strstrpos(char * haystack,  char * needle)   // find 1st occurance of substr in str
{
   char *p = strstr(haystack, needle);
   if (p) return p - haystack;
   return -1;   // Not found = -1.
}
~~~

**Comment by matthijskooijman** [comment]
The problem here is operator precedence: The `>=` operator is evaluated before the `=` assignment operator, so the result of the comparison is assigned to n. See also http://en.cppreference.com/w/cpp/language/operator_precedence

To fix this, you can add extra parenthesis: `if((n=indexOf.someString("text"))>=0)`

Since this is really a problem with your sketch, not the Arduino IDE, I'm closing this issue as invalid. If you have suggestions on where the documentation could have been better to prevent this isssue, feel free to still leave a comment.

**Comment by richw8341** [comment]
My bad. Sorry. Even after thirty years I still cannot see my errors sometimes 

Thanks for that explanation.. 

----- Original Message -----
