### ISSUE TITLE
Arduino15/library_index.json.tmp.gz is not refreshed 

### ISSUE THREAD

**Issue by MichaelJonker** [arduino/Arduino#4272]
Hello, I see still an issue with the library manager. This was also reported in https://github.com/arduino/Arduino/issues/4139

I noticed the issue is still there after I released a new version of a contributed library, which not did show up in the library manager. I tried this with the latest nightly build (of 20151204 02:17).

The symptoms are still the same, the file library_index.json.tmp.gz is not refreshed and I do not see the new libraries versions.

After renaming the file library_index.json.tmp.gz to something different, the IDE loads a new library_index.json.tmp.gz version and I see the new library updates in the library manager.
When I delete the newly copied library_index.json.tmp.gz and rename the old one back again, then I only see the old versions in the library manager.

Michael Jonker

**Comment by vicnevicne** [comment]
I checked the code. The issue is that the downloaded gz file is never deleted.
Consequently, when a new version is downloaded again, the "tmpFile.renameTo(gzipTmpFile)" fails (at cc/arduino/contributions/GZippedJsonDownloader.java:56 ).
The result (false) is not checked, so the process goes on and uncompresses the old version over and over again.

The fix is to delete the previous file by adding
```java
      gzipTmpFile.delete();
```

As the file is named "tmp", I guess the intention of the author was to delete it once uncompressed so I would add the delete right after the call to decompress(), as follows : 

```java
      new JsonDownloader(downloader, gzippedUrl).download(tmpFile, progress, statusText, progressListener);
      File gzipTmpFile = new File(tmpFile.getParentFile(), GzipUtils.getCompressedFilename(tmpFile.getName()));
      tmpFile.renameTo(gzipTmpFile);
      decompress(gzipTmpFile, tmpFile);
      gzipTmpFile.delete();
```

Alternately, to ease debugging, the delete could also be called just before the rename, to always keep one version on the disk, as follows :

```java
      new JsonDownloader(downloader, gzippedUrl).download(tmpFile, progress, statusText, progressListener);
      File gzipTmpFile = new File(tmpFile.getParentFile(), GzipUtils.getCompressedFilename(tmpFile.getName()));
      gzipTmpFile.delete();
      tmpFile.renameTo(gzipTmpFile);
      decompress(gzipTmpFile, tmpFile);
```

Can someone review and include that fix ?

KR. Vicne
