### ISSUE TITLE
Tabs cannot be unexpanded [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#430]
This is [Issue 430](http://code.google.com/p/arduino/issues/detail?id=430) moved from a Google Code project.
Added by 2010-12-11T14:51:49.000Z by [saberbat...@gmail.com](http://code.google.com/u/103620848300265378750/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1.  Change "editor.tabs.expand=true" to false in preferences.

**What is the expected output? What do you see instead?**

Indentation and tabs should remain as tabs in the code.  Instead, the tab key no longer functions, and indents are still converted to spaces.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**

Software version 0021, Windows XP SP2.  Uno board.

**Comment by werediver** [comment]
As far as I can see this issue is related to [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea) ([setTabsEmulated()](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/java/org/fife/ui/rtextarea/RTextAreaBase.java#L1147) and so on). Can somebody confirm that?

Do you think we should open an issue on the side of RSyntaxTextArea project? (I haven't found any related issues there)

**Comment by ffissore** [comment]
This is fixed with 1379505e1355cdbae4ecf97fa1f08e4c4a99bfec since 1.6.5

**Comment by MRGuenther** [comment]
I'm using version 1.7.7, and I have the exact same problem. Are you sure it was fixed? Could it be platform-dependent?

**Comment by Chris--A** [comment]
@MRGuenther 
You are probably having the same issue, however the IDE you mentioned is not this one!

Try: https://github.com/arduino-org/Arduino

If you are confused, maybe leave a comment here too: https://github.com/arduino-org/Arduino/issues/2
