### ISSUE TITLE
preprocessor allows errors to be compiled

### ISSUE THREAD

**Issue by i-make-robots** [arduino/Arduino#4334]
#if false
    #include "this_file_does_not_exist.h"
    #endif

    void setup() {}
    void loop() {}

should not create a linker error... but it does.

**Comment by per1234** [comment]
Using which version of the Arduino IDE? It compiles fine for me with 1.6.7 and the hourly build.

**Comment by vbextreme** [comment]
1.6.6 work

**Comment by matthijskooijman** [comment]
There have been some improvements in recent versions, so be sure to test the hourly build. Since @per1234 tested this, I'm closing this issue as already fixed in the latest version. @i-make-robots, if you test the latest hourly build and it is still broken for you, leave a comment here and we can reopen. Also, be sure to include the actual error message when reporting issues, that makes it easier to figure out a problem.

**Comment by i-make-robots** [comment]
Sorry, my bad. My first invalid ticket :)
