### ISSUE TITLE
USB bootloader in arduino uno

### ISSUE THREAD

**Issue by Alpesh2559** [arduino/Arduino#4470]
Use arduino uno board and using ISP want to update firmware.
I connect reset pin of arduino uno atmega16u2 controller with ground.
Board controoler succesfully goes in DFU mode and using flip tool by atmel connect controller at that all is ok.
now i download updated hex file of firmware from atmel official site  (http://www.atmel.com/devices/atm...)
and this link hex file download using atmel studio in arduino uno board ATmega16u2 controller using ISP but after download this hex file in board flesh memory board not goes to again in DFU mode by short reset PIN with ground. and also i think in atmel site some mistak in this link download hex file but this folder not consist ATmega16u2 hex file but only 16u4 and at90 controller DFU bootloader file..open link and show because atmega16u2 and 16u4 are different.

**Comment by matthijskooijman** [comment]
The firmware running on the Uno's 16u2 can be found here: https://github.com/arduino/Arduino/tree/master/hardware/arduino/avr/firmwares/atmegaxxu2 (hex files including the DFU bootloader for use with ISP are in that directory, versions without the bootloader included are in the usbserial subdirectory). The Uno does not normally use a firmware/bootloader from Atmel directly.

If you uploaded the wrong firmware, I would expect DFU to still work so you can replace the proper firmware (assuming that the DFU bootloader will not overwrite itself). If that doesn't work anymore, you will need an ISP programmer to upload a firmware to the 16u2.

I'm not sure what your actual question is, but I hope this helps you solve your problem. I'm closing this issue, since this is not really the right place for support questions (this github is intended for bugs and feature requests). Getting help with a project is better done on the Arduino forums.
