### ISSUE TITLE
Adding Library includes a bunch of headers that are not really needed

### ISSUE THREAD

**Issue by Makuna** [arduino/Arduino#4647]
When I include a library, there is generally one primary header representing it; but the include option spams my sketch with every include header in the library even though the primary one includes all the others.

I would have expected the "library include" feature to note that there was a matching header name to the library name and just include that one header file.

What is recommended way to solve this?

**Comment by per1234** [comment]
From https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification:
>When the user imports a library into their sketch (from the "Tools > Import Library" menu), an #include statement will be added for all header (.h) files in the src/ directory (but not its subfolders). As a result, these header files form something of a de facto interface to your library; in general, the only header files in the root src/ folder should be those that you want to expose to the user's sketch and plan to maintain compatibility with in future versions of the library. Place internal header files in a subfolder of the src/ folder.

Note that the same applies(only without the src folder) for libraries with 1.0 folder structure. So this caused by the less than ideal folder structure of the library you are including. Should be a fairly simple process to fix this, just move the internal source files to a subfolder and update the includes in the library to reflect the move.
