### ISSUE TITLE
ArduinoISP Windows 10 driver could not installed

### ISSUE THREAD

**Issue by DieterIllingen** [arduino/Arduino#4906]
Hi,
I downloaded the actual driver for ArduinoISP but Windows 10 tells me that the driver could not installed.
I followed getting started, but it will not reflect Windows 10. Is there a new driver? 

Thanks
   Dieter

**Comment by agdl** [comment]
@DieterIllingen I also had problems in installing these drivers on windows 10. However this product is a discontinued one in the arduino product line. Try using the adafruit installer
https://github.com/adafruit/Adafruit_Windows_Drivers/releases/download/1.0.0.0/adafruit_drivers.exe
The only difference will be that instead of selecting ArduinoISP as programmer you will have to choose USBTiny

**Comment by facchinm** [comment]
@agdl workaround works correctly, closing as solved
