### ISSUE TITLE
Arduino uno restart

### ISSUE THREAD

**Issue by saguez** [arduino/Arduino#5065]
software in use  :starping  from  rf24 library examples
Powered via usb Arduino does not restart 
Powered (9volts) via power connector Arduino does not restart 
with some 10 kOhms tricks on Rx Tx Arduino does not restart.
The only way to restart is to download with the arduino IDE **AND** call the serial monitor

**Comment by matthijskooijman** [comment]
This actually sounds like your hardware setup is faulty and/or your battery does not supply sufficient voltage. This is not the right place to get help with such things, I suggest you ask on the Arduino forums or IRC channel instead. If you further investigate and this turns out to be an Arduino software or hardware bug, feel free to reopen this issue or open a new one describing the exact problem.
