### ISSUE TITLE
Warning & failed after flashing

### ISSUE THREAD

**Issue by akarsh** [arduino/Arduino#5149]
I get this warning:
`WARNING: Spurious .github folder in 'DHT sensor library' library`

I am using
* OS X EI Capitain (10.11.5)
* Arduino 1.6.9
* DHT-sensor-library-master.zip (downloaded today)

Testing on ESP8266 board using the files from project
 https://github.com/relayr/ESP8266_Arduino/blob/master/wemos_d1/wemos_d1_workshop_demo/wemos_d1_workshop_demo.ino

Can you kindly help me solve this warning, as i get failed DHT in the serial monitor.

Thank you

**Comment by facchinm** [comment]
Hi @akarsh , the warning is only a reminder for library developers to help them removing unneeded files before release. 
Your problem seems related with ESP core and/or wiring of the DHT sensor (remember that they need a pullup on DATA line). Try opening an issue [here](https://github.com/esp8266/Arduino) or in the forum to get help with your project.
Thanks!
