### ISSUE TITLE
[Library Manager] Request to add to library manager: L293 library

### ISSUE THREAD

**Issue by HackerInside0** [arduino/Arduino#5227]
https://github.com/HackerInside0/L293.git

**Comment by cmaglie** [comment]
@HackerInside0 I see that there are two tags:

`1.0.0`
`1.0.0+metadata-corrections`

since both points to a `library.properties` file with `version=1.0.0` our indexer will pick just one of them randomly and ignore the other.

If the source code is the same, please just remove all existing tags and re-tag only the correct revision with `1.0.0`, so we avoid to publish a version with the wrong metadata.

**Comment by HackerInside0** [comment]
Corrected. Now there is only one tag that points to the version 1.0.0

**Comment by cmaglie** [comment]
Done!
