### ISSUE TITLE
Makey Makey can't be programmed 

### ISSUE THREAD

**Issue by bobbypop999** [arduino/Arduino#5231]
When I try to remap the keys on the Makey Makey it shows this:

Arduino: 1.6.10 (Mac OS X), Board: "SparkFun MaKey MaKey"
Board makeymakey (platform avr, package SparkFun) is unknown
Error compiling for board SparkFun MaKey MaKey.

Arduino: 1.6.10 (Mac OS X), Board: "SparkFun MaKey MaKey"

/Downloads/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware 

/Downloads/Arduino.app/Contents/Java/hardware" -hardware  Library/Arduino15/packages" -tools 

/Downloads/Arduino.app/Contents/Java/tools-builder" -tools 

/Downloads/Arduino.app/Contents/Java/hardware/tools/avr" -tools 

/Library/Arduino15/packages" -built-in-libraries 

Downloads/Arduino.app/Contents/Java/libraries" -libraries Documents/Arduino/libraries" -fqbn=SparkFun:avr:makeymakey -ide-version=10610 -build-path 

"/var/folders/3w/1r9vhjf17zs35n87w_b3pdn80000gn/T/build0730c4ff706d4a5864294ab51534c3fe.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose 

/Downloads/makey_makey_1_4_2-2/makey_makey_1_4_2/makey_makey_1_4_2.ino"

I downloaded the board from the board manager.

I managed it once before and it worked and I have re-installed the software and it still doesn't work.

**Comment by matthijskooijman** [comment]
Can you enable verbose compilation in the preferences and post the full output here? How did you install the makeymakey board files? Did you use the board manager?

**Comment by bobbypop999** [comment]
I have updated the problem please sort it.

**Comment by facchinm** [comment]
This problem usually appears when you have two versions of the same core installed (due to Board Manager issue). Navigate to `/Users/$yourusername/Library/Arduino15/packages/Sparkfun/hardware/avr` and you should find at least two folders. Delete the oldest one and you should be ok. If there is only one folder the problem is somewhere else and we should try to sort it out in another way (maybe via https://github.com/arduino/arduino-builder/pull/84)

**Comment by bobbypop999** [comment]
Thank you it now works and I know what to do naw if it happens again.
