### ISSUE TITLE
Timer0 Compensation

### ISSUE THREAD

**Issue by schuppeste** [arduino/Arduino#5244]
Please, create a little Workaround in wiring.h to compensate External Millis().

Many Arduino Boards have 16Mhz Crystals Tolerance +-30%/20ppm.

My Arduino Board Mega2560 Crystal drifts in compare to PPS GPS Impulse and TCX0/2ppm from 997to999ms.
Measurement: Average 15,958.000Hz/30ppm.

**Comment by matthijskooijman** [comment]
30ppm seems about right for a typical 16Mhz crystal. If you really need more accuracy, you should probably use a 32,768kHz crystal ("watch crystal"), which are often more accurate. This is not something supported by the Arduino environment, so you'll have to dig into the AVR timers yourself (IIRC timer2 supports adding an external clock, though not all chips support both external CPU and timer clocks).

I'm not sure what workaround you are proposing exactly. Do you want to the timer to run slightly faster or slower in software after calibration? If so, I'm not sure how well that will work, since I'm not sure the crystal inaccuracy is reliable (it might be too slow at one moment and too fast sometime later, depending on temperature, voltage, age, etc.). If you really want to do this, you should probably just create a my_millis() function and apply the compensation in there.

I'm closing this issue, as I do not think this is something to fix in the Arduino core. If I misunderstood, feel free to clarify in a comment.

**Comment by schuppeste** [comment]
Its okay, thanks!

I create a fork then to Swap Functions of Timer2 and Timer0, so i can Use Timers0 T0-Pin With 32khz Signal. Otter way i have to solder a watch crystal for asynchronous Operation instead original crystal to a new board.
