### ISSUE TITLE
Editor still does not handle backslashes at the end of lines

### ISSUE THREAD

**Issue by moconoz** [arduino/Arduino#5602]
This error still occurs in version 1.6.12

```
const byte Font5x7[6][7] = {
   {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,},   // 0x20, Space
   {0x0e, 0x08, 0x08, 0x08, 0x08, 0x08, 0x0e,},   // 0x5b, [
   {0x10, 0x10, 0x08, 0x04, 0x02, 0x01, 0x01,},   // 0x5c, \
   {0x0e, 0x02, 0x02, 0x02, 0x02, 0x02, 0x0e,},   // 0x5d, ]
   {0x04, 0x0a, 0x11, 0x00, 0x00, 0x00, 0x00,},   // 0x5e, ^
   {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1f,},   // 0x5f, _
   };
```
  the backslash causes the next line to be ignored corrupting the table

**Comment by moconoz** [comment]
The backslash in the previous entry was itself deleted when posting.

There was a backslash on the following line in the code snippet above
{0x10, 0x10, 0x08, 0x04, 0x02, 0x01, 0x01,}, // 0x5c, (backslash here)

**Comment by facchinm** [comment]
Hi @moconoz , could you post a sketch showing the problem? If you are pasting code snippets, enclose them between ``` so markdown doesn't mangle them

**Comment by cmaglie** [comment]
The `\` at the end of the line means that the current line continue to the next line. In other words this:

```
// This is a comment
```

and this:

```
// This is \
a comment
```

are exactly the same thing. This is a C/C++ standard feature.
The line in your code:
```
   {0x10, 0x10, 0x08, 0x04, 0x02, 0x01, 0x01,},   // 0x5c, \
   {0x0e, 0x02, 0x02, 0x02, 0x02, 0x02, 0x0e,},   // 0x5d, ]
```
is interpreted by the compiler as:
```
   {0x10, 0x10, 0x08, 0x04, 0x02, 0x01, 0x01,},   // 0x5c,    {0x0e, 0x02, 0x02, 0x02, 0x02, 0x02, 0x0e,},   // 0x5d, ]
```
so basically you lost a line because it becames part of the comment.

To workaround your problem you can try to put a trailing space after the `\` (not very good since the space is invisible), or better slightly change your comment style for example:

`// 0x5c, '\'`

or

`// \, 0x5c`

**Comment by moconoz** [comment]
Martino,

 

It has been resolved through another response. It is a standard feature of C/C++ where the backslash is used as a line continuation. I initially thought that a double backslash would work (ie override the escape character) but it doesn’t

 

The solution is not put the backslash at the end of the line.

 

Cheers

MOC

**Comment by moconoz** [comment]
Thanks,

 

I should have known that but it’s been a while since I’ve used that feature.

 

Cheers

MOC
