### ISSUE TITLE
Errors when opening files with a space [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#562]
This is [Issue 562](http://code.google.com/p/arduino/issues/detail?id=562) moved from a Google Code project.
Added by 2011-06-18T11:42:42.000Z by [maxikra...@gmail.com](http://code.google.com/u/116393963817580903993/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium

### Original description

**What steps will reproduce the problem?**
1. Open an *.pde file containing a space

**What is the expected output? What do you see instead?**
A normal error.
Instead the console shows many Java Errors.

**What version of the Arduino software are you using? On what operating**
**system?  Which Arduino board are you using?**
Arduino 0022 (Win7 64bit)
Board: Uno

**Comment by Chris--A** [comment]
This produces an appropriate output now. 

A message box appears saying '_cannot create sketch_'.

There are a lot of java errors produced in the console, however they are preceded by:
```
File name name test1.ino is invalid: ignored
java.io.IOException: No valid code files found
```

Which looks like the exception was intentional and is a 'normal error'.

**Comment by mrcity** [comment]
Since this is currently the first Google result for "arduino no valid code files found", I thought to add my encounter with this error.  I was trying to open up a .ino file from my file browser, but the IDE threw "no valid code files found" because it violated the valid file name rules.  After copying the code into a new sketch and saving it with the same name, I learned the sketch name must not begin with a number and should have fewer than 64 characters.
