### ISSUE TITLE
Error message: using typedef-name 'fpos_t' after 'struct'

### ISSUE THREAD

**Issue by joe68** [arduino/Arduino#5630]
Hi,
when I try to do an firmeupdate the following error appars:

In file included from ...\arduino_build_829823\sketch\SdFile.h:27:0,

                 from ...\arduino_build_829823\sketch\cardreader.h:8,

                 from ...\arduino_build_829823\sketch\Marlin_main.cpp:44:

SdBaseFile.h:38: error: using typedef-name 'fpos_t' after 'struct'

 struct fpos_t {

        ^

In file included from ...\arduino_build_829823\sketch\Marlin.h:10:0,

                 from ...\arduino_build_829823\sketch\Marlin_main.cpp:30:

...\arduino-1.6.13\hardware\tools\avr\avr\include\stdio.h:950:33: note: 'fpos_t' has a previous declaration here

 __extension__ typedef long long fpos_t;

                                 ^

Bibliothek LiquidCrystal in Version 1.0.5 im Ordner: ...\arduino-1.6.13\libraries\LiquidCrystal  wird verwendet
exit status 1
using typedef-name 'fpos_t' after 'struct'

Is there somewhere arround who can help? Thanks in advantage...

Joe

**Comment by facchinm** [comment]
The issue is lacking any information about the project, the board, the Arduino IDE in use etc.. Remember to add these info next time you report an issue so we can analyze it without guessing.
Anyway, I believe you are trying to compile https://github.com/RichCattell/Marlin which is not really active. A simple "search and replace" for any occurrence of  `fpos_t` will fix the problem (which is indeed caused by the recent AVR-libc update).
