### ISSUE TITLE
files in subfolders has not been compiled

### ISSUE THREAD

**Issue by iddq** [arduino/Arduino#5677]
Hello,

I'm trying to port my project from 1.6.7 to 1.6.13 and I'm facing following issue.
Files in subfolders of sketch has not been compiled.

**Comment by facchinm** [comment]
The recursive compilation on sketch subfolders different from `src` has been removed with 1.6.10 because it was close to a bug than a feature :smile: The relevant issue is https://github.com/arduino/Arduino/issues/5186 while the commit is https://github.com/arduino/arduino-builder/pull/148 .
Moving the extra (non user-modifiable) files in `src` will do the trick for both 1.6.7 and latest IDE.
