### ISSUE TITLE
Arduino Due, IDE Compiler NOT SHOWING MEMORY USAGE

### ISSUE THREAD

**Issue by matiaskenig** [arduino/Arduino#5707]
When compile in Arduino IDE, the GLOBAL MEMORY USAGE are showed in all versions EXCEPT WHEN DUE, why????

**Comment by facchinm** [comment]
Indeed, it's ONLY shown on AVR :smile: Jokes apart, the RAM usage calculation is much more useful on AVR boards, since its quantity is very limited. On ARM boards with 32KB+ SRAM it's quite difficult to trigger memory-related bugs. If you want to add it, the right place is https://github.com/arduino/Arduino/blob/master/hardware/arduino/sam/platform.txt#L92 , and you can use https://mcuoneclipse.com/2013/04/14/text-data-and-bss-code-and-data-size-explained/ and https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/platform.txt#L81 as inspiration
