### ISSUE TITLE
Copying between char arrays violates their contents.

### ISSUE THREAD

**Issue by aakumykov** [arduino/Arduino#5739]
I have a class that permanently listens on serial port for some tokens and returns data on demand.
Inside class method I have to copy data buffer to secondary var, clean buffer for new incoming data, return secondary var. (Incoming data is stored as dynamic char array along with data counter.)

**Issue:** secondary var contains corrupted data.

I make some tests to compare "classic" C++ compiler and Arduino IDE compiler. I try to copy data from array to array via simple assignment in for-cycle and via strcpy. From static char array to dynamic, from dynamic to dynamic. (Char arrays have null-character on it's tail.) Both ways produces broken results.
It seems there is a bug in Arduino IDE.

OS: Debian Jessie amd64
Arduino IDE: 1.6.13
Arduino board: Nano, Mega

= Example jutput from Arduino: =
ORIGINAL:
0: a [code 97]
1: b [code 98]
2: c [code 99]
3: 1 [code 49]
4: 2 [code 50]
5: 3 [code 51]
6:  [code 0]
COPY:
0: a [code 97]
1: b [code 98]
2:  [code 2]
3:   [code 0]
4: a [code 97]
5: b [code 98]
6:  [code 2]

= Example output from standard C++: =
ORIG:
0: a [code 97]
1: b [code 98]
2: c [code 99]
3: 1 [code 49]
4: 2 [code 50]
5: 3 [code 51]
6: 
COPY:
0: a [code 97]
1: b [code 98]
2: c [code 99]
3: 1 [code 49]
4: 2 [code 50]
5: 3 [code 51]
6: 

--------------------------- CODE FOR ARDUINO IDE ---------------------------
```
void show(char* a, int len, char* comment) {
    Serial.println(comment);
    for (int i=0; i < len; i++) {
      Serial.print(i);
      Serial.print(": ");
      Serial.print(a[i]);
      Serial.print(" [code ");
      Serial.print(int(a[i]));
      Serial.print("]");
      Serial.println("");
    }
    Serial.println("");
}

void setup() {
  Serial.begin(9600); while(!Serial);

  char s0[] = "abc123";
  int len = sizeof(s0);

  Serial.print("initial array: "); Serial.println(s0);
  Serial.print("size: "); Serial.println(len);
  Serial.println("");


  char* d1 = new char;
  for (int i=0; i < len; i++) { d1[i] = s0[i]; }
  show(d1, len, "static to dynamic (d1) with FOR cycle");


  char* d2 = new char;
  for (int i=0; i < len; i++) { d2[i] = d1[i]; }
  show(d2, len, "dynamic to dynamic (d2) with FOR cycle");


  char* d3 = new char;
  strcpy(d3,s0);
  show(d3, len, "static to dynamic (d3) with STRCPY");


  char* d4 = new char;
  strcpy(d4,d1);
  show(d4, len, "dynamic to dynamic (d4) with STRCPY");


  char* d5 = d1;
  show(d5, len, "dynamic to dynamic (d5) via pointer (from d1 !)");
}

void loop() {
  // put your main code here, to run repeatedly:
}
```
--------------------------- CODE FOR ARDUINO IDE ---------------------------

--------------------------- CODE FOR "CLASSIC" C++ ---------------------------
```
#include <iostream>
#include <string.h>
using namespace std;

void show(char* a, int len, char* comment) {
    cout << comment << endl;
    
    for (int i=0; i < len; i++) {
	cout << i << ": " << a[i] << " [code " << int(a[i]) << "]" << endl;
    }
}

int main () {
  char s0[] = "abc123";
  int len = sizeof(s0);

  cout << "initial array: " << s0 << endl;
  cout << "size: " << len << endl << endl;


  char* d1 = new char;
  for (int i=0; i < len; i++) { d1[i] = s0[i]; }
  show(d1, len, "static to dynamic (d1) with FOR cycle");


  char* d2 = new char;
  for (int i=0; i < len; i++) { d2[i] = d1[i]; }
  show(d2, len, "dynamic to dynamic (d2) with FOR cycle");


  char* d3 = new char;
  strcpy(d3,s0);
  show(d3, len, "static to dynamic (d3) with STRCPY");


  char* d4 = new char;
  strcpy(d4,d1);
  show(d4, len, "dynamic to dynamic (d4) with STRCPY");


  char* d5 = d1;
  show(d5, len, "dynamic to dynamic (d5) via pointer (from d1 !)");
}
```
--------------------------- CODE FOR "CLASSIC" C++ ---------------------------

**Comment by matthijskooijman** [comment]
> I make some tests to compare "classic" C++ compiler and Arduino IDE compiler. 

The Arduino IDE just uses the normal gcc C++ compiler under the hood, so there is no "Arduino IDE compiler" in this sense (there is some preprocessing of your code, but nothing that should affect this).

> char* d1 = new char;

This allocates memory for (a single) `char`, so that's 1 byte. You'r then writing multiple bytes into that memory, which overflows the allocated memory and potentially writes into other pieces of memory, as you observed.

I suspect that the reason this does not occur with your "Classic" example is that you run that on a 64-bit pc, where memory allocations are probably 64-bit aligned (so you ask for 1 byte, but really get 8). You're still overflowing the allocated memory, but writing into unused padding space. If you increase the length of your string, I suspect you'll see similar breakage. On the Arduino, which is an 8-bit AVR architecture, you ask for 1 byte and get 1 byte, hence the problem.

I'm pretty confident that this is the problem, so I'm closing this issue. If you have further questions, remarks or think there is a bug after all, feel free to leave more comments.
