### ISSUE TITLE
Use git submodule instead of libsync script

### ISSUE THREAD

**Issue by roncapat** [arduino/Arduino#5886]
Git submodules allow to maintain different repos linked together. 
I noticed that patches to the libraries, submitted here on the main repo, tend to be discarded and "routed" to the library-specific repo instead. Also, libsync script is a non-standard approach to import libraries in the main repo, giving that git provides a better solution. With submodules, commits could be thrown to the library-specific repo, with no risk to have duplicate code (it's just a gitlink). This could simplify development a bit.

**Comment by facchinm** [comment]
Some libraries are still in the main repo due to open PRs, but we are removing them as soon as they get closed (or merged). We encourage new PRs to be applied to the `arduino-libraries` repo but there is no automagic way to force it until we effectively remove the code from this one. The deploy script already fetches all the bundled libraries from their github releases
