### ISSUE TITLE
Error compiling sketch using SoftwareSerial 

### ISSUE THREAD

**Issue by danielgeiser** [arduino/Arduino#5927]
I'm using SoftwareSerial with Arduino 1.8.1 with a selected Attiny84 board. 
I call the library like this and try to compile but it won't : 

#include <SoftwareSerial.h>
void setup() {
  // put your setup code here, to run once:
}
void loop() {
  // put your main code here, to run repeatedly:
}
I got this error:
\SoftwareSerial\SoftwareSerial.cpp: In member function 'void SoftwareSerial::begin(long int)':
\SoftwareSerial\SoftwareSerial.cpp:317:37: error: expected primary-expression before ')' token

**Comment by facchinm** [comment]
Hi @danielgeiser ,
which Tiny core are you using? Unless the problem is related to the build process and not the core or the sketch, you should report it on the core maintainer's repo (which could be https://github.com/damellis/attiny or https://github.com/SpenceKonde/ATTinyCore, please check what you are using before posting there)
