### ISSUE TITLE
programming arduino pro mini using Arduino UNO..baud rate problem

### ISSUE THREAD

**Issue by sarwadenj** [arduino/Arduino#5930]
Hi everybody,
I'm trying to upload code in Arduino pro mini using Arduino UNO. 
Using    Serial.begin(115200); i want to print data.
After opening serial monitor at baud rate 115200 garbage type data coming and on changing baud rate in serial monitor to 230400 my data is printing.

I checked by changing value at  Serial.begin(115200); like 9600 or other values then for corresponding values garbage only coming and for taking next value in serial monitor it printing the data..

So what's the issue? How i solved it?

**Comment by facchinm** [comment]
Hi @sarwadenj , double check the quartz frequency of your board and the fuses selection. 8Mhz vs 16Mhz is a common problem, and brings double (or half) Serial baud rate as primary result (apart from wrong timing).
For future questions, search and ask the [forum](http://forum.arduino.cc/) since it's a quite common problem.
