### ISSUE TITLE
Version 1.8.1 doesn't copy 'data' folder on save as

### ISSUE THREAD

**Issue by tttapa** [arduino/Arduino#5998]
When using the Arduino IDE with an ESP8266, for example, I use the data folder in the sketch folder (the folder that opens when you hit CTRL+K) for files to upload to the SPIFFS. (HTML, CSS, JS, icons etc.) In version 1.6.x, this data folder was copied when doing a 'save as', but using the new 1.8.1 version, I have to copy the folder manually.
Why was this feature removed?

I'm using Ubuntu 16.04.

Pieter

**Comment by matthijskooijman** [comment]
Hm, I remember considering to remove this support, but in the end I settled on removing support for the `code` subdirectory and leaving the `data` subdirectory intact in 4ef56995c61ac0f40866e14004dc6bf6dd1788d3

It also seems the code for it is still present: https://github.com/arduino/Arduino/blob/master/arduino-core/src/processing/app/Sketch.java#L357-L360 So that means this was not intentionally removed, but apparently broken at some point. I have not tried to reproduce this yet.
