### ISSUE TITLE
Running Arduino IDE under Windows (Installer or Windows Store) with ClearType causes the menus to display gibberish.

### ISSUE THREAD

**Issue by SarreqTeryx** [arduino/Arduino#6170]
I'm not sure why, but shutting off ClearType fixes this problem, at the cost of text clarity

![2017-04-08 3](https://cloud.githubusercontent.com/assets/3124383/24833134/f0caa7e6-1c8d-11e7-95a1-f1e8fcbc4596.png)

![2017-04-08 4](https://cloud.githubusercontent.com/assets/3124383/24833133/f0c7439e-1c8d-11e7-955b-146ef8b5f1a1.png)

**Comment by nitram509** [comment]
I would like to add some information.

I'm using Windows 10 Pro 64 bit (German version) with active Clear Type since years and never experienced such gibberish problem.
Maybe there is some issue overlapping, but clearly, it is not just ClearType setting alone.

**Comment by Phoenix1o1** [comment]
I wish to add something to this too.
I am running Win 10 Pro Build 16299 x64, and as other reported turning Off cleartype fixes the issue with me too.
In my specific case the issue is (i think) due to the fact that I'm using a different default font systemwise (It's called B612). Reverting to windows default (i think it's called Segoe) fixes the issue.
Also, in the Setting windows of the IDE, the text can be read properly, so the issue is specific to menus only.
I suggest adding in the setting an option to choose the font to be used in the menus and allow the users to change it at will,  or investigating the issue more deeply.
I don't want to turn cleartype off any time I want to use the IDE and than back on when i'm finished.

**Comment by Phoenix1o1** [comment]
![image](https://user-images.githubusercontent.com/5053221/52900241-df9e0580-31f3-11e9-8ccb-fb19810824fa.png)

**Comment by Phoenix1o1** [comment]
@cmaglie do you have any update on this Issue? It could possibly be related to this #7839

**Comment by facchinm** [comment]
It's surely related with #7839 ; a possible fix would be to override the menu fonts like this (https://github.com/arduino/Arduino/pull/8647/files#diff-0437e0831865dfac93630d3acc7321c9R43) but it would make them inconsistent with the rest of the system (better inconsistent that garbled anyway :stuck_out_tongue: )

**Comment by cmaglie** [comment]
@Phoenix1o1 
It may be that the driver of your graphics card is not updated?

**Comment by facchinm** [comment]
@SarreqTeryx @Phoenix1o1 @nitram509 I've investigated on the problem and found a solution that may fit.
By adding
```
-Dawt.useSystemAAFontSettings=on
```
to `arduino.l4j.ini` the fonts reappear as if ClearType was off, but just in the Arduino IDE and just for the menus.
Could you try if it also works for you? In this case we could add a line in the troubleshooting page (I would avoid applying this setting to everyone)

**Comment by sandeepmistry** [comment]
I'm closing this for now due to lack of feedback, please re-open if needed with what @facchinm requested above.

**Comment by ammarchalifah** [comment]
I'm having this problem too. I'm using Windows 7, and I've tried the solution proposed by facchnim to add -Dawt.useSystemAAFontSettings=on to to arduino.l4j.ini. It doesn't work.

**Comment by jeremyBass** [comment]
Just to add, I tried the 
`-Dawt.useSystemAAFontSettings=on`

and it did restore the font.  I am on the insider's build for win 10 build 20185.re_prerelease.200731-1415 although it should work for any win 10.
