### ISSUE TITLE
[Library Manager] Add Digit Led Display Library to Arduino Library Manager

### ISSUE THREAD

**Issue by ozhantr** [arduino/Arduino#6185]
https://github.com/ozhantr/DigitLedDisplay

**Comment by cmaglie** [comment]
The library has been added but in order to be published you must create a tag/release, otherwise our indexer will ignore it. Once you create the tag the library will be automatically published within an hour.

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-add-my-library-to-library-manager

**Comment by ozhantr** [comment]
thank you.
