### ISSUE TITLE
No option to set RTS on Close, as specified on page

### ISSUE THREAD

**Issue by Kilili** [arduino/Arduino#6203]
This is for WIN10x64

https://www.arduino.cc/en/Guide/ArduinoProMini

**Comment by per1234** [comment]
This option is specific to the FTDI chips. You won't find it with other common USB-TTL serial chips such as CH340. Since the text of that page specifically says "If using the FTDI cable on Windows" I'm going to close this issue.

I do question whether those instructions are necessary since I have never heard of this option in years on the Arduino Forum. With my counterfeit FTDI FT232 breakout boards, I've never needed to enable that setting for auto-reset to work. I suppose that would be a subject for a different issue report.
