### ISSUE TITLE
Setting boolean flag adds 80 to 182 bytes to Global variables

### ISSUE THREAD

**Issue by nielseng2017** [arduino/Arduino#6205]
Adding a simple Boolean flag "aflag = true;" adds 83 and 182 bytes to global variables.
IDE 1.6.11
I'm stumped - setting a declared flag (either local or global), when added/compliled into a do loop in two cases adds between 83 (global declare) and 182 (local declare) bytes respectively to global variables?  Why any increase?  

What am I missing?

In both cases, the increase in global variables size causes one program to NOT run - including setup.

bool aflag = false;

do{
     switch(val){
       case 0xff:
           aflag = true;   adding this instruction causes the increase in global variable size
      break;
} while(!aflag);

**Comment by facchinm** [comment]
Well, without that line the compiler optimizes the loop since the condition is always true. Double check what you are doing because it looks like your logic in not so clear :slightly_smiling_face:  If you face other problems, write on the [forum](forum.arduino.cc) for further assistance with personal projects, thanks.
