### ISSUE TITLE
[Library Manager] Please add Guarateca

### ISSUE THREAD

**Issue by JoaquimFlavio** [arduino/Arduino#6211]
https://github.com/JoaquimFlavio/GuaraTeca

**Comment by per1234** [comment]
Please read https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ and make the necessary changes so that your repository complies:
- Library must be in the root folder of the repository. Your repository contains multiple libraries, in subfolders. It is not possible to add it to Library Manager in this form.
- Once the repository has been fixed you need to make a release or tag matching the `version` value in library.properties.

**Comment by cmaglie** [comment]
Since you added the library on the other issue this one can be closed, I imagine.
