### ISSUE TITLE
Document ternary operator

### ISSUE THREAD

**Issue by thedub2001** [arduino/Arduino#6247]
Hello I just discovered the the Serial.print() function can be used with conditional testing :
```
Serial.print(test ? "test=true" : "test=false");
```
If the "test" variable is true then the output will be : 
```
test=true
```

If the "test" variable is false then the output will be : 
```
test=false
```
I just thought this function could appear somewhere in the Serial.print() reference documentation

**Comment by facchinm** [comment]
Well, it's not only about Serial.print , the ternary operator is allowed in any function if the "arguments" type is correct. However, it could be surely documented, but I'd prefer waiting until we merge some of [these](https://github.com/arduino/Arduino/pulls?q=is%3Apr+is%3Aopen+label%3A%22Print+and+Stream+class%22) PRs

**Comment by NeatNit** [comment]
I think the `? :` operator is a common enough source of confusion to warrant a mention in the reference. I think it would fit nicely under "Further Syntax":

![image](https://cloud.githubusercontent.com/assets/2400026/26035630/057697b6-38d8-11e7-8cf9-ed213408d693.png)

**Comment by juanpablojofre** [comment]
I'm with @NeatNit!!
The ternary operator should be documented as part of the syntax of the language.
Where I disagree with @NeatNit is in the location.
Since it's an operator, it should be listed as such.
I would suggest a new header: Conditional Operator
and the entry underneath as:
- ? : (ternary operator)

**Comment by NeatNit** [comment]
It would be lonely all by itself under that header. 😢

**Comment by cousteaulecommandant** [comment]
Definitely not under "Further syntax"; this is just a plain old operator.  Maybe under "Boolean operators".

**Comment by feikname** [comment]
Why not under control structures? The ternary operator is esssentially a one-line alternative to `if {} else { }` blocks.

**Comment by cousteaulecommandant** [comment]
> Why not under control structures?

I'd rather not, since it's quite different from a control structure in how it's used – the statements in that section are typically used with blocks of code, which doesn't work with `? :`.
However it might be possible to put the documentation of `? :` as a section of the documentation for `if` as is done with comparison operators (and if not, I'd definitely link to `? :` on the "See also" section of `if`).

**Comment by thedub2001** [comment]
I found another strange operator and I can't find documentation, perhaps it could be gathered at the same place in future documentation : 
```
for (auto dataobj : data){
    Serial.println(dataobj.key);
}
```
_example from https://bblanchon.github.io/ArduinoJson/doc/decoding/_

**Comment by feikname** [comment]
@thedub2001 It's a [range-based `for` loop](https://stackoverflow.com/a/35490271).

**Comment by cousteaulecommandant** [comment]
> `for (auto dataobj : data)`

I'd classify that as "advanced C++ *'black magic'* that is out of the scope of the Arduino documentation".
In fact all the code in that page uses quite a lot of C++ mechanisms such as references, templates, and custom classes, which are also seen in the internal Arduino code but are usually opaque to the user.

**Comment by per1234** [comment]
Moved to https://github.com/arduino/reference-en/issues/519
