### ISSUE TITLE
Arduino Leonardo information misleading

### ISSUE THREAD

**Issue by troywweber7** [arduino/Arduino#6248]
information on the [arduino leonardo page](https://www.arduino.cc/en/Main/ArduinoBoardLeonardo) is a bit misleading in a subtle way. The [getting started section](https://www.arduino.cc/en/Main/ArduinoBoardLeonardo#overview) talks about the Wifi library, but does the Leonardo have wifi or not? I didn't think it did, but this documentation confuses me.

**Comment by per1234** [comment]
I don't find any mention of "WiFi" on either the [Leonardo product page](https://store.arduino.cc/arduino-leonardo-with-headers) or the [Leonardo Getting Started page](https://www.arduino.cc/en/Guide/ArduinoLeonardoMicro) so I think this issue has been resolved at some point since your report.

I'm going to close this issue as resolved. If I'm wrong about this feel free to comment with some direction to the problematic text and I'll re-open.

Thanks for your report @troywweber7!
