### ISSUE TITLE
Serial.print bug ?

### ISSUE THREAD

**Issue by Testato** [arduino/Arduino#6293]
this code work only for an half, 
it print only `12`

```
void setup() {
Serial.begin(9600);
}
void loop() {
  Serial.print(1234);
  exit(0);    
}
```

**Comment by facchinm** [comment]
The report is missing "some" information... If the bug report refers to a UNO, it's quite normal that not all bytes are being written, since the 16u2 changes its behaviour based on the status of the 328 (and probably changes baud rate, too, I have no time to check).
However, adding a small delay between the `print` and `exit` should solve the issue.
Reopen if needed

**Comment by bengtmartensson** [comment]
Just two comments:

1. Normal programming practice says that you cannot rely everything to be output until you flush or close the buffer/stream. It appears that [Serial.end](https://www.arduino.cc/en/Serial/End) should be used to close the stream.

2. exit is meaningless in the Arduino context.

**Comment by matthijskooijman** [comment]
Actually, I think `exit()` might be calling `abort()`, which IIRC disables interrupts and then starts looping infinitely. Because interrupts are disabled, serial output stops. If you insist on using `exit()`, make sure to call `Serial.flush()` to write all serial output first.

**Comment by MauroMombelli** [comment]
correct answer is then:

1. Normal programming practice says that you cannot rely everything to be output until you flush or close the buffer/stream. It appears that Serial.end should be used to close the stream.

2. exit() [...] disables interrupts and then starts looping infinitely. Because interrupts are disabled, serial output stops.

This happen because the Serial library is asynchronous.
