### ISSUE TITLE
Library structure: allow different version

### ISSUE THREAD

**Issue by aster94** [arduino/Arduino#6328]
Hello, 
Maybe it is already possible and i don t know. If not it would be great to use different version of the same library. For examply i use the standard arduino board (i.e. Uno and nano) and also some attiny. When i change between them i need to modify the library to have it working. 
I think it would be useful

**Comment by facchinm** [comment]
Hi @aster94 ,
it's totally possible, just put the hardware specific parts between `ifdefs` 
For example, if you need a function to run on the UNO only, you can enclose the code between
```
#ifdef ARDUINO_AVR_UNO
... (your code here) ....
#endif
```
of use `ARDUINO_ARCH_AVR` if you want to be more generic. The same applies to ATTINY architecture. 
If you have more questions on this topic please write on the forum, since it reaches a broader audience and these kind of questions are quite common :wink:

**Comment by aster94** [comment]
Thank @facchinm!
