### ISSUE TITLE
Calculate equlation problems

### ISSUE THREAD

**Issue by aliemresafak** [arduino/Arduino#6460]
Have a nice days. I suppose I found a bug. Following the equlation that `a = a *(500/1024)` its result 0. 
but i tried to solve equlation with different way that `a = (a*500)/1024` it works. 

had i problem of coding?

**Comment by facchinm** [comment]
Hi @aliemresafak , this is the expected behaviour in C/C++ ; the division is executed before the multiplication and the result is truncated to an integer (being an integer division).
Thus `500/1024` always gives 0, unless you declare them `float`.
Next time you have a programming problem that's too strange no-one encountered in the past, the best place to ask for support is the [forum](http://forum.arduino.cc). Thanks!
