### ISSUE TITLE
Serial Library

### ISSUE THREAD

**Issue by vctrex** [arduino/Arduino#6563]
I'm using Arduino 1.8.3_1 with avr-gcc 6.3.0_1 and I am unable to compile any program with Serial library. Everytime I'm getting error (here is example of "ReadASCIIString")

>Arduino:1.8.3 (Linux), Board:"Arduino/Genuino Uno"
>
>Archiving built core (caching) in: /tmp/arduino_cache_813680 
>/core/core_arduino_avr_uno_1463c1525e5674af859013f08ea32c59.a
>lto1: internal compiler error: Segmentation fault
>0x8b64df crash_signal
>	../../gcc/toplev.c:333
>0x7fd3925d2a8f ???
>	/builddir/glibc-2.25/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
>0x7428b6 maybe_record_node
	../../gcc/ipa-devirt.c:2468
0x747245 possible_polymorphic_call_targets(tree_node*, long, ipa_polymorphic_call_context, bool*, void**, bool)
	../../gcc/ipa-devirt.c:3186
0x747d0e possible_polymorphic_call_targets(cgraph_edge*, bool*, void**, bool)
	../../gcc/ipa-utils.h:115
0x747d0e ipa_devirt
	../../gcc/ipa-devirt.c:3597
0x747d0e execute
	../../gcc/ipa-devirt.c:3913
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /usr/bin/avr-gcc returned 1 exit status
compilation terminated.
/usr/bin/avr-ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
exit status 1

**Comment by facchinm** [comment]
It looks like a bug in the compiler. It's probably worth reporting to gcc bugtracker (it looks like [this one](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60871) but the affected versions do not match at all).
I'm closing the issue, anyway, since we only target and provide toolchains "approved" by Atmel (4.9.2 and, ongoing, 5.4.0) so we can't directly investigate a fix for this one, sorry.
Thanks for reporting anyway! Feel free to use the issue as an "internal tracker" if you decide to file a bug on gcc
