### ISSUE TITLE
Callback progress status

### ISSUE THREAD

**Issue by cabbagecreek** [arduino/Arduino#6595]
I an developing software that uses commandline upload /compile it would be nice to have a estimated progress status.
Using commandline there is limited streams that can be listen to. Adding a flag to the command that created a progress status on standard output that the calling software can parse and report to the calling Software UI.

**Comment by facchinm** [comment]
Hi @cabbagecreek ,
there is a HUGE problem in adding such abstraction: the external tools we call already have their progress bars since they know what they're going to do. `arduino-builder` has its progress report too, which is the one we could expose more easily. Instead, a single `avrdude` flash involved at least three different operations and thus three progress bars, so adding a wrapper over them is not going to give any useful information.
If you are developing a CLI software, I strongly suggest you to use `arduino-builder` as a backend (and trap the progress it reports, see https://github.com/arduino/arduino-builder/blob/master/src/arduino.cc/builder/constants/constants.go#L173 for the tag) and then launch the uploader and show its verbose output (which 99% of the time already contains a progress bar).
