### ISSUE TITLE
Switch in IDE to skip compiling

### ISSUE THREAD

**Issue by lensman11** [arduino/Arduino#6625]
Is it possible to add a switch to skip compiling if there has been no code changes in the current script???
I often re-upload previously compiled code or reloaded scripts to more than 1 board for testing purposes and the re-compile is a real pain..

**Comment by facchinm** [comment]
Hi @lensman11 ,
if a sketch hasn't changed the "recompile" phase should take a very short time (like 1 second or 2) since all the files are already cached and the only action required is linking everything together.
I agree that, ideally, if a sketch is untouched that phase is useless, but you could have changed a library from outside the IDE so checking every file for modifications is needed. This requirement wouldn't give you the super speedup you can obtain by exporting the generated binary and simply flash it on all the boards.
Anyway, if you are experiencing a different situation (for example, the recompile time is way longer) I'd like to investigate; a verbose output with timestamps and your pc configuration would be a good starting point for debugging.
