### ISSUE TITLE
to which data type is Arduino String 100% compatible? char* or string or neither one?

### ISSUE THREAD

**Issue by tofrnr** [arduino/Arduino#6724]
To which data type is Arduino String 100% compatible? char* or string or neither one?
The documentation, does not state anywhere if String is a null-terminated ANSI C char* from `<cstring> or <string.h>`
or a C++ string from `<string>`
http://www.cplusplus.com/reference/cstring/

**Comment by matthijskooijman** [comment]
It is neither, it is a custom Arduino class, probably introduced because gcc on AVR does not offer `std::string`: https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/WString.h

**Comment by tofrnr** [comment]
> re: @per1234 per1234 referenced this issue 15 hours ago 
> What is the termination of a String returned by Serial.readString ? #6723 

that is not true, #6723 is not a duplicate of this topic.
#6723 is about how Seria.redString terminates the input strin after having pressed ENTER, and this question has still not been answered.

It is impudent and intolerable that issues are closed and marked as duplicate falsely weithout being resolved in either way!

**Comment by matthijskooijman** [comment]
I'll ignore your previous comment, since that is about another issue (where I also just responded).

As for this issue, I think I've responded to your question, so there's no longer any point in keeping this issue open. If, based on the answers, you have specific suggestions on where the documentation could be improved, feel free to open a new issue.
