### ISSUE TITLE
I want to add my library to Library Manager

### ISSUE THREAD

**Issue by maykon** [arduino/Arduino#6787]
Hi, I want to add my library to Library Manager.

Please check my project: https://github.com/maykon/ButtonDebounce

Thanks.
Maykon L. Capellari

**Comment by per1234** [comment]
You need to create a release or tag that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by maykon** [comment]
Create release with tag 1.0.1.

Thanks.

**Comment by maykon** [comment]
Hi, I need change anymore or it´s OK?

Thanks.

**Comment by per1234** [comment]
It's fine now. That's why I removed the "Waiting for feedback" label. cmaglie will add your library to the index after some days when he goes through and does all the outstanding requests. He will close this issue at that time, and you'll get a notification about this. Shortly after that your library will be available for installation via Library Manager.

**Comment by cmaglie** [comment]
Done
