### ISSUE TITLE
Clean up examples to remove warnings [imported]

### ISSUE THREAD

**Issue by cmaglie** [arduino/Arduino#693]
This is [Issue 693](http://code.google.com/p/arduino/issues/detail?id=693) moved from a Google Code project.
Added by 2011-10-24T01:49:13.000Z by [maniac...@ymail.com](http://code.google.com/u/104304625040622075887/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Component-Examples
### Original description

Some examples have warnings which indicate where a few clean-ups could be made.  This patch fixes all those.

(If it doesn't apply cleanly let me know, I'll regenerate one from a clean repo)

**Comment by per1234** [comment]
### Done:
- BlinkWithoutDelay.ino: https://github.com/arduino/Arduino/commit/83ef1814cfda808f94cd80a70d7cee8725e24a13
- Arrays.ino: https://github.com/arduino/Arduino/commit/a6022df4221bc02892607466866513e88a45e121
- StringIndexOf.ino: https://github.com/arduino/Arduino/commit/47bcf07f5e7b0d07f0fcef64490d65333c570f7d
- StringToIntRGB.ino: This file is no longer part of the bundled examples.

### WontFix:
- StringLength.ino: I think this change is not desirable because it introduces a type (`size_t`) that the target audience of the bundled examples will not be familiar with.
```diff
 String txtMsg = "";                         // a string for incoming text
-int lastStringLength = txtMsg.length();     // previous length of the String
+size_t lastStringLength = txtMsg.length();     // previous length of the String
```

### To Do
- StringAdditionOperator.ino: Will be fixed by https://github.com/arduino/Arduino/pull/6448
