### ISSUE TITLE
Please add this Library to the Library Manager

### ISSUE THREAD

**Issue by thehapyone** [arduino/Arduino#6954]
I will like the below Arduino Library to be included in the Library Manager:
https://github.com/thehapyone/BareBoneSim800

**Comment by per1234** [comment]
In order to be added to the Library Manager index your library must contain a library.properties file. The format of this file is documented here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

Make sure that the `version` value matches the tag of the release that contains it.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by thehapyone** [comment]
Please check now.

**Comment by cmaglie** [comment]
Done!
