### ISSUE TITLE
Error compile Windows 10 and esp8266

### ISSUE THREAD

**Issue by sabas1080** [arduino/Arduino#7011]
Hi 

#### Hardware
Hardware:			ESP12
Core Version:      	2.3.0

### Description

Problem description

### Settings in IDE

Module:  			Wemos D1
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

### Sketch
```
Example Blink
```

### Debug Messages

```
unable to rename ... arduino.ar ... reason: File exists
```

I already tried running as administrator, in Arduino IDE 1.8.4 and 1.8.5 installer and portable #2987

![24882775_1039864912834193_1928425778_o](https://user-images.githubusercontent.com/2874292/33677214-a25fbd54-da7d-11e7-85f8-41d4025e32d2.png)

Also try cleaning and deleting Arduino15 and the same error

Thanks

**Comment by facchinm** [comment]
Hi @sabas1080 ,
the line showing the problem is https://github.com/esp8266/Arduino/blob/master/platform.txt#L84 . However, it only happens on the third execution of that recipe, which makes me think about some antivirus activity starting on that event (rapid modification of the same file in TEMP folder).
Can you try rerunning the compilation with your antivirus off? Thanks

**Comment by sabas1080** [comment]
Remove antivirus is solution, thanks!
