### ISSUE TITLE
Arduino IDE won't start

### ISSUE THREAD

**Issue by Aventedor** [arduino/Arduino#7050]
My Arduino IDE is not opening. It just shows the start window and then it crashes without showing any error. I have uninstalled and reinstalled it many times but it's of no use. Also tried with several versions but it shows same result. ONLY the start window splashes and gets off.

**Comment by per1234** [comment]
This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do end up determining this is caused by a bug I'll reopen the issue but at this point we don't have anywhere near enough information from you to start an investigation so it's better if we work through it on the forum.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
