### ISSUE TITLE
[Add to Library Manager] RN487x library

### ISSUE THREAD

**Issue by EmbeddedMan** [arduino/Arduino#7078]
Please add the following library to the library manager index:
https://github.com/chipKIT32-libraries/RN487x

Thank you!

*Brian

**Comment by per1234** [comment]
Your `version` property value in library.properties should match the tag of the release. In this case the tag is 1.1.1 but the `version` property is set to 1.0.0:
https://github.com/chipKIT32-libraries/RN487x/blob/v1.1.1/library.properties#L2
because you updated the `version` property value after the release.

**Comment by EmbeddedMan** [comment]
Thanks per1234 - you are quite right. It has been corrected and should be good to go now. Version at 1.1.2.

Thanks so much-

**Comment by cmaglie** [comment]
Done!
