### ISSUE TITLE
Feature request : Tuning methods for internal Oscillator (AVR054,AVR055)

### ISSUE THREAD

**Issue by thedub2001** [arduino/Arduino#7114]
For a low energy project, I use the Atmega328p with no external crystal resonator running at 8MHz with internal clock. The internal oscillator is not very accurate and this generates issues when receiving Serial messages at slow speed (9600kbps).

I saw that AVR provide methods to improve internal oscillator accuracy :

> There are two ways to perform a calibration. Runtime or in production. Runtime one needs an accurate external reference. It can be UART (AVR054), external 32kHz XTAL (AVR055) or usb framelength (VUSB on attiny45/85).

I currently miss an easy way on Arduino IDE to find the best OSCCAL value for the Atmega328p.
Actually I would like to be able to use the 32khz crystal of the Arduino UNO to tune the chip.

My hardware:
I use an ISP programmer plugged to the UNO ISP headers, to program the Atmega328 (plugged in the Arduino UNO slot) in 8MHz internal clock mode

This can help : 
[OSCCAL calibration using 32kHz with WinAVR](http://community.atmel.com/projects/osccal-calibration-using-32khz-x)

**Comment by matthijskooijman** [comment]
This is not something the Arduino IDE can easily provide, since it relies on external hardware and a custom sketch. Calibration is probably also a bit of a corner case, which would be nice, but does not warrant the development effort to support. You should probably just figure out a way to achieve this that fits your setup and use that.

FWIW, the Uno does not actually have a 32khz crystal.
