### ISSUE TITLE
Cannot solve {runtime.ide.path} and {source_file} in custom recipe (platform.txt)

### ISSUE THREAD

**Issue by frestucc** [arduino/Arduino#7160]
I'm working on a parser to call before the Arduino processing, I set some recipes on platform.txt using {runtime.ide.path} and {source_file} properties, but they cannot be solved in the requested path. Both 1.8.5 and 1.9 beta seems have the same issue.

**Comment by per1234** [comment]
From a forum thread, I know @frestucc is wanting to use these properties in a custom [hook recipe](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#pre-and-post-build-hooks-since-ide-165)

(Using Arduino IDE 1.9.0-beta build 36, Windows 10):
`{runtime.ide.path}` is blank in `recipe.preproc.macros`, undefined in all other recipes (standard or hook). The hardware specification lists it as a "[global predefined property](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#global-predefined-properties)" so this makes no sense.

`{source_file}` is only defined in `recipe.preproc.macros` and the compilation recipes. It is not defined in any of the [hook recipes](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#pre-and-post-build-hooks-since-ide-165). The specification only mentions it as available to the compilation recipes. The hooks aren't run before and after the compilation of each individual `{source_file}`. So, with the current system, this could only be defined for the hooks as the first file to be compiled after running the prebuild hook recipe or the last file compiled before running the postbuild hook recipe. The same situation occurs with `{object_file}`, `{archive_file}`, and `{object_files}`.
