### ISSUE TITLE
Gamebuino-Classic and Gamebuino-META library update

### ISSUE THREAD

**Issue by Rodot** [arduino/Arduino#7261]
Hello Arduino,

The library Gamebuino is now renamed to Gamebuino-Classic
https://github.com/Gamebuino/Gamebuino-Classic

Also both our libraries Gamebuino-Meta and Gamebuino-Classic don't seem to be updated after several days, even though we tagged them and updated library.properties ?
https://github.com/Gamebuino/Gamebuino-Classic 
https://github.com/Gamebuino/Gamebuino-Meta

Thank you very much and have a great day :)

**Comment by per1234** [comment]
In addition to renaming Gamebuino to Gamebuino-classic, you also renamed Gamebuino-Meta to Gamebuino-META:
https://github.com/Gamebuino/Gamebuino-Meta/commit/341bf78893dc3e0b9a38db62949ac1cc90879c53

When you change the `name` value in library.properties the Library Manager indexer entry must be manually updated so that's why the releases after the name change were not automatically added to the Library Manager index.

cmaglie will update the entries for your libraries at the next opportunity.

**Comment by Rodot** [comment]
Oh, sorry about that and thank you for the clarification. We're updating everything but now it shouldn't move anymore :)

**Comment by cmaglie** [comment]
Done
