### ISSUE TITLE
SD card cluster size

### ISSUE THREAD

**Issue by TobiasKnauss** [arduino/Arduino#7263]
https://www.arduino.cc/en/Tutorial/CardInfo
Code is faulty: it assumes that the SD card cluster size is always 512 bytes. This is simply wrong. The cluster size is set when the card is formatted and my range from 512B to 32kB.

**Comment by SimonePDA** [comment]
Hi, the code is correct and I understand that you mistakenly took the 512 bytes value for a BLOCK as the value for a CLUSTER. You are right when you say that clusters may have different sizes, but the code says something different.
First it gets the number of BLOCKS per CLUSTER (more than one block per cluster is used by bigger clusters and this goes with what you say), then it gets the number of clusters in the volume and the final calculation is the value divided by 2 to get a value in kB with the standard block size of 512 bytes.
To avoid any misunderstanding, I've added an explanation at the end of the tutorial to explain this difference between blocks and clusters.

Thank you for opening this issue because it allowed us to clarify further this aspect of SD cards.
