### ISSUE TITLE
DFL168A Synchronous version Library

### ISSUE THREAD

**Issue by Dafulai** [arduino/Arduino#7281]
Hello,
Please add library from gitHub:
https://github.com/Dafulai/DFL168A-Sync-Library

Thanks

**Comment by per1234** [comment]
In order to be added to the Arduino Library Manager index your library must be located in the root of the repository, rather than in the DFL168A_Sync subfolder. 

Please correct the issue, create a new release or tag (or redo the existing release), and then comment here so we know we can proceed with adding your library.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by Dafulai** [comment]
Hello,
  We have changed the link to:
https://github.com/Dafulai/DFL168A-Sync-Library/archive/1.0.0.zip
Thanks

**Comment by cmaglie** [comment]
Done!
