### ISSUE TITLE
Add RGB Led library

### ISSUE THREAD

**Issue by Manghao** [arduino/Arduino#7286]
[My deposit of libratry to add](https://github.com/Manghao/RGBLed)

Following the instructions provided [here ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ)

Thank you in advance

**Comment by per1234** [comment]
Note that since the [`version` property](https://github.com/Manghao/RGBLed/blob/v1.0.1/library.properties#L2) in library.properties was not updated before the 1.0.1 tag was created, only the 1.0.0 version of your library will be available in Library Manager. To fix this you would need to update the `version` property and then redo the tag or create a new one.

**Comment by Manghao** [comment]
I forgot to change the version of the file, I just changed that and I pushed the modification

**Comment by cmaglie** [comment]
Done!
