### ISSUE TITLE
Current Library update - CoDrone

### ISSUE THREAD

**Issue by RobolinkInc** [arduino/Arduino#7352]
Hi,
We'd like to upload new version of CoDrone library to the Arduino Library Manager.
We didn't update for a while and we just update few month ago and today.
I realize that library have to update from GitHub automatically from master or branch but not update.
If something missing in repo let me know
The library can be found here: https://github.com/RobolinkInc/CoDrone.git
Thank You, http://robolink.com/

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) to make the version available via the Library Manager. The [last release](https://github.com/RobolinkInc/CoDrone/releases) you did was 1.4.4 and so that's why the newest version available via Library Manager is also 1.4.4.

Make sure that your `version` field in library.properties is set to the release version before you create the release.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ
