### ISSUE TITLE
[Library Manager] Please add RARGBLED v1.0.3 to library manager

### ISSUE THREAD

**Issue by hippymulehead** [arduino/Arduino#7358]
URL of Repository: https://github.com/hippymulehead/RARGBLED
Release: https://github.com/hippymulehead/RARGBLED/tree/v1.0.3

**Comment by per1234** [comment]
The release must contain a library.properties file but you added that file after creating the 1.0.3 release. Please create a new release that does contain this file.

**Comment by hippymulehead** [comment]
URL of Repository: https://github.com/hippymulehead/RARGBLED
Release: https://github.com/hippymulehead/RARGBLED/tree/v1.0.4

**Comment by per1234** [comment]
That will work but note that you forgot to update the [`version` ](https://github.com/hippymulehead/RARGBLED/blob/v1.0.4/library.properties#L2)value in library.properties before you made the release. It's that version property that Library Manager uses for versioning, rather than the tag name. So even though the release is v1.0.4, it will be shown as 1.0.3 in Library Manager.

**Comment by cmaglie** [comment]
Done!
