### ISSUE TITLE
[Library Manager] Please add library for Grove - Temp&Humi&Barometer Sensor(BME280)

### ISSUE THREAD

**Issue by lanselambor** [arduino/Arduino#7435]
github: https://github.com/Seeed-Studio/Grove_BME280
release: https://github.com/Seeed-Studio/Grove_BME280/releases/tag/v1.0.0

**Comment by cmaglie** [comment]
`Grove - Temp&Humi&Barometer Sensor(BME280)`

same here, no `&` nor `()` in the name.

**Comment by lanselambor** [comment]
Fixed that, thank you! 😃

**Comment by per1234** [comment]
The name still contains the disallowed character `&`:
https://github.com/Seeed-Studio/Grove_BME280/blob/1.0.1/library.properties#L1

**Comment by lanselambor** [comment]
Please check  it again.

**Comment by lanselambor** [comment]
@per1234 please add this library to Library Manger,  thanks a lot.

**Comment by per1234** [comment]
I don't have any power to add libraries to the index; I just try to help out a bit with administration of the issue tracker. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. I removed the `Waiting for feedback` tag after you resolved the issue so that means this will be processed on the next run through the requests. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by cmaglie** [comment]
done
