### ISSUE TITLE
Serial Montior Buggin out

### ISSUE THREAD

**Issue by luma420** [arduino/Arduino#7501]
I´ve tried to output some ultrasonic distances but my serialmonitor only puts out number like 0.32.0, 0.33.0 and so on even with newline the monitor is writting into one inifinte line baud rate is the same as my serial.begin i´ve tried to flush it before but it wont even print simple strings

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do end up determining this is caused by a bug in the Arduino IDE I'll be happy to reopen this issue.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
3. Add a comment to this issue with the link to your thread to help anyone else who later has the same problem find the solution.
