### ISSUE TITLE
Documentation dispute about Arduino-IDE-1.5-3rd-party-Hardware-specification

### ISSUE THREAD

**Issue by jantje** [arduino/Arduino#7554]
This issue is to discuss the recent  changes on the wiki page https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification where I removed something and @per1234 put it back the next day :-( As far as I know none of us has "Arduino authority" so someone of Arduino should jump in.

This is about the sections **Recipes to build the core.a archive file** and **Recipes for linking**
I think that for these commands the {archive_file} property should not be used to build the command, and as such should not be in the section **The recipe can be built concatenating the following properties set by the IDE:**
I understand the {archive_file} property exists (and may need some documentation somewhere) but it should not be used to build a command as it is not a FQN property. Therefore I think that it should not be listed in this section and only {archive_file_path} should be listed as a archive reference.

FQN=Fully qualified name

PS there may be better places to discuss the documentation and I'm willing to move to this "better place" if requested.
PSS I created a pull request #7544 to make avr platform.txt use {archive_file_path} in the link command which was not the case

**Comment by per1234** [comment]
Here is jantje's edit:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification/_compare/4601bc4542eb69dbbd115df66136424bed038fa3

This edit:
1. Documents `{archive_file_path}`.
2. Changes `recipe.ar.pattern` and `recipe.c.combine.pattern` to use `{archive_file_path}` rather than ``{build.path}/{archive_file}`.
3. Removes the documentation of `{archive_file}`.

My edit:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification/_compare/b8a94b9ae58697e600a6d704eaf35a51fd8ba672...6b54c21d7519ee0b2cc07cf4db4c28c0a7b5a28a
**only** reverts (3) in the above list. The reason I did this is because I believe it's important to completely document all properties in the specification.
>it should not be used to build a command

Rather than judge whether this information could ever be useful to any 3rd party package author, I prefer to just offer complete documentation and let then do with it as they wish. That section of the specification is prefaced: "The recipe **can** be built concatenating the following properties set by the IDE:", not "These are the properties jantje thinks you should use in your recipe".

With what appears to be a comprehensive specification available, most people are not going to go off digging through the Arduino IDE's source code for undocumented features. So once this sort of documentation is removed the knowledge is essentially lost to the community.

Regarding (1), I'm wholly in support of this addition to the specification. Thanks!

Regarding (2), I'm a bit ambivalent since it's not actually correct considering those parts of the specification are prefaced "For example, Arduino provides the following for AVR:". So until such time as [your PR](https://github.com/arduino/Arduino/pull/7544) is merged, that statement is a lie. I understand the reason for that change and I think the PR is likely to be merged without too much delay and so I did not revert that part. I do think it's best practices to only update documentation after the corresponding change has been made since many PRs are never merged or are merged after a long delay.

**Comment by jantje** [comment]
> The reason I did this is because I believe it's important to completely document all properties in the specification.

I also like complete documentation (though it is a illusion) but with your revert of  my change the documentation states it is ok to use {archive_file} as part of any recipe and I think it is not.
This is also the reason why I think it is up to arduino to make a statement.

As an architect I document things before the facts. 

>With what appears to be a comprehensive specification available, most people are not going to go off digging through the Arduino IDE's source code for undocumented features. So once this sort of documentation is removed the knowledge is essentially lost to the community.

As stated in the original post. I'm not against documenting the existence of {archive_file}. IMHO in Arduino IDE 1.6.6 Arduino opted to use a FQN for the archive and name it {archive_file_path}. Therefore  {archive_file} should not be advocated to be used in recipes.

archive_file documentation could be added to the section Global Predefined properties. 


I think this issue creates to strong emotions. That is/was not my intention. So let me explain what my point is.
I think the intention of Arduino changed in arduino IDE 1.6.6 from {archive_file} should be used in the link and archive recipes to  {archive_file_path} should be used in the link and archive recipes.

Because I have a Issue https://github.com/Sloeber/arduino-eclipse-plugin/issues/969 on my arduino IDE alternative named sloeber caused by a hardware provider using  {archive_file} and not {archive_file_path}, I thought the best way to help the creator of the issue in the discussion with the hardware provider to fix the issue was updating the documentation.
The next day I noticed someone else has a different view and my replace to a addition.
As it is no use undoing each others changes for ever I thought a issue with all involved parties was the way to go.
And that is why I created this issue

**Comment by matthijskooijman** [comment]
This seems like a fine place to have a discussion about something like this, so thanks for bringing this up. I believe we should be able to find a solution that is acceptable for all of us.

My view on this is that we should document all available options, so it should definitely stay in the list (at least for backward compatibility, and perhaps there are non-standard recipes that somehow need the *name* of the file rather than the *path* to the file).

I haven't checked, but it seems that what @per1234 about not being a global property makes sense, so the current place is correct.

However, to prevent people from actually using this property in unsupported ways, perhaps add an explicit remark:

> Older cores used `{build.path}/{archive_file}` as the output path of the .a file, but this is no longer recommended, as the archive file might be moved elsewhere in the future. Instead, use the newer `{archive_file_path}`, which contains the full path to the .a file and should always be correct.

I can also imagine that changing the example for `{archive_file_path}` would help:

> {archive_file_path}        - fully qualified archive file (ex. "/path/to/core.a")

(instead of implying that it is always equal to `{build.path}/{archive_file}`).


On reason that the AVR core might not be using this new property, could be backward compatibility. IIRC older IDE versions can update the AVR core, and I'm not sure if there is a good mechanism to specify IDE version compatibility for a core currently (but this is probably a separate issue that should be separately solved if it is not already).

On a related note, it might be useful to mention in what arduino-builder/IDE version `{archive_file_path}` was introduced?

**Comment by jantje** [comment]
@matthijskooijman 
Thanks for joining the discussion.
You make some good points. 
I never considered {archive_file} may not be a global property. If {archive_file} is not a global property I see no obvious place to document it right now.

As to keeping history in the documentation. In my experience it is hard to keep documentation clean and hold history information. I scanned the hardware specification document and I found only history references like "since IDE..."
It is up to Arduino to decide whether you want to do so (temporarily) or not.


Brain fart---->
Maybe using the java term deprecated is a good acceptable solution

{ide_version}              - the IDE version (ex. "152" for Arduino IDE 1.5.2)
{object_files}             - the list of object files to include in the archive ("file1.o file2.o ....")
{archive_file_path}        - fully qualified archive file  (ex. "/path/to/core.a")
deprecated since Arduino IDE 1.6.6
{archive_file}             - the name of the core archive file (ex. "core.a")

**Comment by matthijskooijman** [comment]
@jantje, I don't really think that this is about "history". Current versions of the file still support the `{archive_file}` variable, and I suspect they will continue to do so in the future. In that sense, the variable is (AFAIK) not really deprecated and you can still use it where appropriate.

What is *not* appropriate, however, is to assume that `{archive_file}` is a filename inside `{build_path}`, so for the most common case (passing the full path to the .a file), you should use `{archive_file_path}. In a sense, using `{archive_file}` is not deprecated, but using `{build_path}/{archive_file}` *is* (which is what I tried to convey with my suggested addition.

**Comment by jantje** [comment]
Can we agree on something?

**Comment by jantje** [comment]
Can we agree on

{ide_version} - the IDE version (ex. "152" for Arduino IDE 1.5.2)
{object_files} - the list of object files to include in the archive ("file1.o file2.o ....")
{archive_file_path} - fully qualified archive file (ex. "/path/to/core.a")
deprecated since Arduino IDE 1.6.6
{archive_file} - the name of the core archive file (ex. "core.a")

If not...what is better

**Comment by per1234** [comment]
So you are proposing the following changes to
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#recipes-for-linking
1. Switch order of documentation of `{archive_file}` and `{archive_file_path}` so that `{archive_file}` comes last on the list of properties that can be used in `recipe.ar.pattern`.
1. Give a specific example of `{archive_file_path}` rather than using `{build.path}/{archive_file}` as the example.
1. State that `{archive_file}` is deprecated.

I assume you are implying that the equivalent changes should also be made to:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#recipes-to-build-the-corea-archive-file

I'm fine with (1) and (2). My dispute is with (3).

Although it's not precisely defined as such, I associate the term "deprecated" as used in APIs to indicate a component that is planned to be removed at some point in the future. I think that's the most common use of the term. The very Wikipedia page you referred to earlier gives focus on that usage of the term. I have not heard anything about plans to remove `{archive_file}` so I think this term is misleading. Deprecating an API component should be a formal process initiated by the official Arduino team rather than something done on a whim by a 3rd party.

Here's my proposed text:
>### Recipes for linking
>
>All the artifacts produced by the previous steps (sketch object files, libraries object files and core.a archive) are linked together using the **recipe.c.combine.pattern**.
>
>The recipe can be built concatenating the following properties set by the IDE:
>
>    {ide_version}              - the IDE version (ex. "152" for Arduino IDE 1.5.2)
    {object_files}             - the list of object files to include in the archive ("file1.o file2.o ....")
    {archive_file_path}        - fully qualified archive file (ex. "/path/to/core.a"). This property was added in Arduino IDE 1.6.6/arduino builder 1.0.0-beta12 as a replacement for {build.path}/{archive_file}.
    {archive_file}             - the name of the core archive file (ex. "core.a")

This also fulfills @matthijskooijman's recommendation that the IDE/arduino-builder version where `{archive_file_path}` was added be documented.

>I haven't checked, but it seems that what @per1234 about not being a global property makes sense, so the current place is correct.

That statement I made about it not being global was based on compiling with a dummy package that attempts to use the `{archive_file}` property in every recipe. The property name was only replaced by the archive filename in `recipe.ar.pattern` and `recipe.c.combine.pattern`. In all other recipes it just appears as `{archive_file}` in the command. I did not actually look through the source code as I wouldn't know where to even start with that.

>On reason that the AVR core might not be using this new property, could be backward compatibility. IIRC older IDE versions can update the AVR core, and I'm not sure if there is a good mechanism to specify IDE version compatibility for a core currently (but this is probably a separate issue that should be separately solved if it is not already).

Backwards compatibility of `{archive_file_path}` with Arduino IDE 1.6.5-r5 and earlier has already been provided by https://github.com/arduino/ArduinoCore-avr/commit/33c9558641d15d63d8f7857810f70e05d4e43d5d. I did a successful test compile using jantje's platform.txt from https://github.com/arduino/Arduino/pull/7544 with Arduino IDE 1.6.5-r5.

**Comment by jantje** [comment]
>I assume you are implying that the equivalent changes should also be made to:

yes

The problem I have with your proposal is that it is not clear that {archive_file_path} is to be preferred to  {build.path}/{archive_file}.
It is somewhat implicit (As Arduino decided to do so) but it is not explicit. 
Can we add  this note?

> When referring to the actual archive file on disk always use {archive_file_path}. Do not use {build.path}/{archive_file}.

**Comment by per1234** [comment]
I think saying it's a replacement for `{build.path}/{archive_file}` makes that quite clear already.

**Comment by jantje** [comment]
>I think saying it's a replacement for {build.path}/{archive_file} makes that quite clear already.

I don't agree.
