### ISSUE TITLE
13 th Digital Pin Blinking while reset

### ISSUE THREAD

**Issue by Gokul-1** [arduino/Arduino#7556]
I found 13th pin flickering while resetting. Kindly help me to solve the issue. Bootloader code also changed.

**Comment by per1234** [comment]
The bootloader's blinking of pin 13 is intentional and does not represent a bug.

This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
