### ISSUE TITLE
No silent install with Version 1.8.5

### ISSUE THREAD

**Issue by EGruber01** [arduino/Arduino#7558]
It is not possible to do a silent install for the arduino software using the /S - switch. When using this switch I always get asked if I accept the drivers certificate(s).
So it is not possible to do a mass install in schools, for instance.

with kind regards

E. Gruber

**Comment by facchinm** [comment]
Hi @EGruber01 ,
as highlighted by [this comment](https://github.com/arduino/Arduino/issues/4122#issuecomment-173269522) the issue is related with Arduino SRL certificates, so there's little we can do (except dropping that certificate, which is not really feasible since it supports all Arduino.org boards).
The workaround proposed there could help in a mass install, probably.
Let me know if it solves your issue!
