### ISSUE TITLE
New library: PxMatrix LED matrix library for ESP8266 and ESP32

### ISSUE THREAD

**Issue by 2dom** [arduino/Arduino#7584]
Could you please add https://github.com/2dom/PxMatrix

Thanks!

**Comment by cmaglie** [comment]
done

**Comment by 2dom** [comment]
Great ... thanks!

**Comment by 2dom** [comment]
I have continued developing the library and posted two new versions on github...how do they find their way into the library manager?

**Comment by 2dom** [comment]
I have continued developing the library but the new tagged releases do not appear in the library manager ... what am I doing wrong?

**Comment by per1234** [comment]
I believe the reason is that you changed the `name` value in library.properties from "PxMatrix LED MATRIX for Adafruit GFX" to "PxMatrix LED MATRIX library":
https://github.com/2dom/PxMatrix/commit/d1a5a2cd15627ff61920e9a705d4480a10d871a8

If that's the new name you want the library indexed under then cmaglie can update the entry.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name

**Comment by 2dom** [comment]
Yes ... I would like to change the name. Would you mind updating the entry? Thanks!

**Comment by cmaglie** [comment]
done
