### ISSUE TITLE
CRC doesnt match XMC1100

### ISSUE THREAD

**Issue by deydara** [arduino/Arduino#7603]
Hi! I have some problem with a package for xmc microcontrollers. 
"CRC doesn`t match, file is corrupted. It may be a temporary problem, please retry later"
for 1.1.0 version
Some ideas?

**Comment by per1234** [comment]
This was caused by Infineon changing the XMCFlasher file but not updating the checksum in https://github.com/Infineon/Assets/releases/download/current/package_infineon_index.json. I have reported this issue at https://github.com/Infineon/Assets/issues/3.

So the Arduino IDE was correct in giving that error and so this does not represent an Arduino bug.
