### ISSUE TITLE
DropboxManager library

### ISSUE THREAD

**Issue by lucasromeiro** [arduino/Arduino#7612]
https://github.com/lucasromeiro/DropboxManager

**Comment by per1234** [comment]
Although your repository currently meets all the requirements for addition to the Library Manager index, it did not at the time of the last release (because the library was in a subfolder of the repository). Please create (or redo) a tag or release with your library in the current form.

Once you have done this please comment here so we know we can proceed.

**Comment by lucasromeiro** [comment]
Hello, now is OK!

**Comment by lucasromeiro** [comment]
Hello, Something missing?

**Comment by per1234** [comment]
It looks to as if everything is in order, which is why I removed the "Waiting for feedback" label.

Your library will not be available for installation via Library Manager until it has been added to the index. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So there is no further action required from you.

**Comment by lucasromeiro** [comment]
Cool i'm learning Thank you!
How can I request an update in the library when I need it?

**Comment by per1234** [comment]
You only need to update the `version` field in your library.properties file and then create a new tag or release. The Library Manager indexer job does an hourly scan of all the repositories that have been added to the index and picks up any new tags. So your new releases will automatically be added and available from Library Manager shortly after you create it without any need to request an update.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Comment by cmaglie** [comment]
Library added, sorry for the delay.
