### ISSUE TITLE
[Library Manager] Please add ACAN library

### ISSUE THREAD

**Issue by pierremolinaro** [arduino/Arduino#7633]
Hi,

Please, can you include my ACAN library (CAN driver for Teensy 3.x):
https://github.com/pierremolinaro/acan
~~https://github.com/pierremolinaro/acan/tree/master/teensyduino-library/ACAN~~

Thanks,

Pierre Molinaro

**Comment by per1234** [comment]
In order to be added to the Library Manager index, your library must be located in the root of the repository, rather than in the teensyduino-library/ACAN subfolder.

Please resolve this issue, make a new release or tag, then comment here so we know we can proceed with adding your repository to the Library Manager index.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by pierremolinaro** [comment]
Ok, sorry about that. I do the modification.

Thanks,

Pierre Molinaro

**Comment by pierremolinaro** [comment]
It is done. The ACAN library is the repository: https://github.com/pierremolinaro/acan

Thanks,

Pierre Molinaro

**Comment by cmaglie** [comment]
Done

**Comment by pierremolinaro** [comment]
Thank you very much !

Pierre Molinaro
