### ISSUE TITLE
(.text+0x0): multiple definition of `__vector_7' Error

### ISSUE THREAD

**Issue by ghost** [arduino/Arduino#7691]
My Error Code:

Arduino:1.8.5 (Windows 10), Kart:"Arduino/Genuino Uno"

libraries\Tone\Tone.cpp.o (symbol from plugin): In function `timer0_toggle_count':

(.text+0x0): multiple definition of `__vector_7'

libraries\Arduino-IRremote-master\IRremote.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

[code.zip](https://github.com/arduino/Arduino/files/2098808/code.zip)

**Comment by PaulStoffregen** [comment]
You're trying to use 2 libraries (neither published directly from Arduino) which need the same timer.

The board you're using, Uno, only has 1 of that type of timer, so there simply is no good solution to using these 2 libs on Uno.  But even if this could be done, the place to ask would be the forums or issue trackers for the authors of these libraries, since they're not published or maintained by Arduino.
