### ISSUE TITLE
[Library Manager] Add Arduino_HTTP library

### ISSUE THREAD

**Issue by qub1750ul** [arduino/Arduino#7695]
https://github.com/qub1750ul/Arduino_HTTP

**Comment by per1234** [comment]
Due to the presence of the character `/`, the `name` value in your library.properties file is not compliant with the [Arduino Library specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format). Please fix this issue and then redo the tag or create a new one.

Once you have done this, please comment here so we can proceed with adding your library to the Library Manager index.

**Comment by qub1750ul** [comment]
Done

**Comment by cmaglie** [comment]
done!
