### ISSUE TITLE
Add new version of bossac

### ISSUE THREAD

**Issue by frippe75** [arduino/Arduino#7709]
As of https://github.com/shumatech/BOSSA/issues/33
 
There is a way to allow larger bootloaders than the default 8k (-e option of bossac).
Would be nice to see this integrated into the IDE as well.

Maybe add a new property in the boards.txt that gets picked up and passed to bossac.

**Comment by frippe75** [comment]
Just realize there are bossac 1.8.0 in other directories. Need to workout how to call them

**Comment by facchinm** [comment]
Hi @frippe75 ,
to target the new bossac you need to:
1- "link" it to your platform by adding 
```
          "toolsDependencies": [
            {
              "packager": "arduino",
              "name": "bossac",
              "version": "1.8.0-48-gb176eee"
            }
```
in `package_$yourboard_index.json`

2- replace all occurrences of `runtime.tool.bossac` in `platform.txt` with `runtime.tool.bossac-1.8.0-48-gb176eee` to make sure it gets picked up correctly.

Otherwise, you can add Adafruit's SAMD core json (https://adafruit.github.io/arduino-board-index/package_adafruit_index.json) that already requires it, install the core and then apply point 2)
