### ISSUE TITLE
arduino

### ISSUE THREAD

**Issue by FAHIMAA** [arduino/Arduino#7727]
hello all
 am looking for  help
i need a program in order  to communicate with BMS via a can bus so that i can read some information like the state of charge of the batterie,temperature ....,and store the data in sd card?
thank you

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. It is **NOT** appropriate to post this sort of thing here.

You can post your request to the Arduino Forum. Be aware that, if you just want someone to write a program for you, rather than help you write your own program, you should expect to pay for it.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
