### ISSUE TITLE
Library addition request

### ISSUE THREAD

**Issue by 4dsystems** [arduino/Arduino#7776]
Hello,

Can you please add the following libraries to the Library Manager.

https://github.com/4dsystems/SOMOIoD

https://github.com/4dsystems/GFX4d
https://github.com/4dsystems/GFX4DIoD9

https://github.com/4dsystems/ViSi-Genie-Arduino-Library
https://github.com/4dsystems/Diablo16-Serial-Arduino-Library
https://github.com/4dsystems/Picaso-Serial-Arduino-Library
https://github.com/4dsystems/Goldelox-Serial-Arduino-Library

Thank you

**Comment by 4dsystems** [comment]
Two more:

https://github.com/4dsystems/GFX4DIoD9
https://github.com/4dsystems/GFX4d

Thank you

**Comment by per1234** [comment]
There is a problem with https://github.com/4dsystems/GFX4DIoD9.

In order to be added to the Library Manager index, each library must have a unique library.properties `name` value. But https://github.com/4dsystems/GFX4DIoD9 and https://github.com/4dsystems/GFX4d both have the same `name` value of `GFX4d`. Please change the `name` value of one of the two libraries and then either redo the tag or else create a new release.

After that's done please comment here so we know we can proceed.

**Comment by 4dsystems** [comment]
One more:

https://github.com/4dsystems/SOMOIoD

Fixed GFX4DIoD9 as requested - Sorry - Typo.
https://github.com/4dsystems/GFX4DIoD9

**Comment by cmaglie** [comment]
Done
