### ISSUE TITLE
Update AVR Build Tools to newer version which is 64 bit for macOS

### ISSUE THREAD

**Issue by SConaway** [arduino/Arduino#7829]
Update AVR Build Tools to newer version which is 64 bit for macOS. I was working on this but can't seem to even build what we have now, so I need some help.

**Comment by facchinm** [comment]
Hi @SConaway ,
running `./package-avr-gcc.bash` from https://github.com/arduino/toolchain-avr/tree/staging (staging tree) should produce the correct toolchain on OSX, once the `-i386` occurrences are removed from https://github.com/arduino/toolchain-avr/blob/staging/package-avr-gcc.bash#L79 . 
If you find any problem with that procedure please open an issue on that repository; I'm closing the issue here in the meantime.
