### ISSUE TITLE
Unknow key code for Increase Font Size keyboard shortcut

### ISSUE THREAD

**Issue by nesdnuma** [arduino/Arduino#7950]
Hello,

This is what I see in the Edit/Increase Font Size menu: _Ctrl+Inconnu key code: 0x2b_

Inconnu obviously stands for "unknown" as I am running Windows in French language.

I reduced the font size without intention just by pressing the Ctrl key and moving my fingers on the trackpad but I cannot increase it back. When I relaunch the IDE, the reduced font size remains.

Is there any way to change this without a recompilation of the IDE?

**Comment by facchinm** [comment]
Hi @nesdnuma ,
which IDE version are you using? In 1.8.6 the way to increase font size is layout independent and you can get with
```CTRL + the_key_with_plus_sign```

So if you are on a normal AZERTY french keyboard you need to press `CTRL + SHIFT + '=' ` since ` SHIFT + '=' ` give you the `+` keystroke

Anyway, the CRTL + mouseWheel (or touchpad scrolling) should work just fine; make sure that your laptop is not stopping the touchpad events if a key is pressed (palm detection).

Last chance: open `C:\Users\yourusername\AppData\Arduino15\preferences.txt` and change `editor.font` last number with something like `15`
