### ISSUE TITLE
Library update

### ISSUE THREAD

**Issue by nathanRamaNoodles** [arduino/Arduino#7981]
My MusicWithoutDelay Library has been updated, but it's not showing on the library manager.

https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary

The current release is v3.5.0, but it would be nice if you add the previous versions too.

**Comment by per1234** [comment]
Versions 3.5.0, 3.0.0, 2.0.0, and 1.0.0 are all available for installation via Library Manager:
![clipboard01](https://user-images.githubusercontent.com/8572152/45274004-2da32600-b46a-11e8-8449-6cad26ad6cb0.png)
The reason why there is no 1.0.1 listed is because the `version` value in library.properties was still set to 1.0.0 at the time of the 1.0.1 release:
https://github.com/nathanRamaNoodles/MusicWithoutDelay-LIbrary/blob/v1.0.1/library.properties#L2
