### ISSUE TITLE
[Library Manager]  Please add Rhomb.io Duino Pinmap Library

### ISSUE THREAD

**Issue by jenguidanos** [arduino/Arduino#8141]
Please add Rhomb.io Duino Pinmap Library
https://github.com/Rhomb-io/rhio-pinmap

Thanks!

**Comment by per1234** [comment]
In order to be included in the Arduino Library Manager index, your library must have a library.properties file. Although there is a library.properties file in your repository, it was added after the 1.0.0 release. Please either create a new release which contains the library.properties file or else redo the existing release.

After doing so, please comment here so we'll know we can proceed.

**Comment by jenguidanos** [comment]
Okay, done. New tag 1.0.1. Sorry for the inconvenience.

**Comment by cmaglie** [comment]
done!
