### ISSUE TITLE
[CREATE] DS3231 library 

### ISSUE THREAD

**Issue by Giovani-Delgado** [arduino/Arduino#8201]
For months I have been successfully developing a sketch that contains the DS3231 library.
But two weeks ago I can not continue the compilation of my sketch. When compiling brings the following message:
"No matching function for call to'DS3231 (const uint8_t &, const uint8_t &) '"
I have tried to delete and reload the library several times and also several versions.
I already looked for help in the forum.
And so far nothing!
I think it's a bug from the last web editor's version.
I can not work with WEB EDITOR anymore.
Thanks for listening!

**Comment by per1234** [comment]
Here is the Arduino Forum thread:
http://forum.arduino.cc/index.php?topic=578664

Custom libraries are not getting include priority over pre-installed libraries in the Arduino Web Editor. I'm pretty sure that was how it used to work because I remember several times using that behavior to force the correct library to be used. So hopefully one of the Create team has taken note of that thread and will look into it.

I'm trying to assist @Giovani-Delgado get around the problem with a workaround. It's been slow going because I've fumbled things a couple times but I think we'll get it this time around.

According to https://github.com/arduino/arduino-create/issues/1#issuecomment-351344954, the [Create > Editor section of the Arduino Forum](http://forum.arduino.cc/index.php?board=101.0) is the appropriate place to submit bug reports or feature requests related to the Arduino Web Editor. Since there is already a thread there, I'll go ahead and close this issue.
