### ISSUE TITLE
Please add my library "MobaLedLib" to Library Manager

### ISSUE THREAD

**Issue by Hardi-St** [arduino/Arduino#8329]
Hi,

thank you very much for the wonderful Arduino IDE.

Please add my MobaLedLib to the Arduino library manager:
   https://github.com/Hardi-St/MobaLedLib

thanks
  Hardi

**Comment by cmaglie** [comment]
I've added the library to the index but there is a problem:

```
JOB 1923 - 2018/12/24 12:05:00 Scraping https://github.com/Hardi-St/MobaLedLib.git
JOB 1923 - 2018/12/24 12:05:04 Checking out tag: v0.7.0
JOB 1923 - 2018/12/24 12:05:04 Error syncing library: Error generating library from repo: 'sentence' and 'url' fields must be defined
```

this happens because the url field is empty, to fix it:

1) edit `library.properties` and add a value to the `url` property
2) commit and push
3) delete and redo the latest release tag

once done the library will be automatically published within an hour, no need to comment further here.
