### ISSUE TITLE
[Library Manager] Please add Robot Cing libraries

### ISSUE THREAD

**Issue by StanislavJochman** [arduino/Arduino#8351]
Source: https://github.com/RobotCing/Cing/tree/3.0.0/Software/Libraries
Tag: https://github.com/RobotCing/Cing/releases/tag/3.0.0

Please add Robot Cing libraries.
Main features:
Programing robot Cing without knowlage of electronics.

**Comment by per1234** [comment]
In order to be included in the Arduino Library Manager index, each library must be in a separate repository. The libraries must be in the root of their repositories.

In the case of the Adafruit NeoPixel, DallasTemperature, and OneWire libraries, there are already libraries of this name in the Library Manager index. Each library must have a unique name. If those are versions of the libraries you've customized, you should give them unique `name` values in their library.properties files (OneWire is missing a library.properties). Make sure your `name` values are compliant with the library specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

After doing that, please comment here with the links to each library repository so we'll know we can proceed.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by StanislavJochman** [comment]
So if i understand it correctly I should create repo for every library? Libraries like adafruit neopixel... won't be there i accidently put them there now. Each of Robot Cings library should have correct library.properties. 

Best regards 
Stanislav Jochman

**Comment by per1234** [comment]
>So if i understand it correctly I should create repo for every library?

That's correct. This is a requirement for inclusion in the Arduino Library Manager index. The indexer will essentially just do a `git clone` of each tag you push, so the repository must have a structure compatible with installation (as if you were doing a **Sketch > Include Library > Add .ZIP Library**). Having one library per repository will also make it easier for people to do manual library installations.

>Libraries like adafruit neopixel... won't be there i accidently put them there now.

Great!

>Each of Robot Cings library should have correct library.properties.

Yes. I took a look at the library.properties files for all the _IO libraries and they all appear to be fine.

**Comment by StanislavJochman** [comment]
Thanks for quick answer. I will fix it tomorrow.

Best regards
Stanislav Jochman

**Comment by StanislavJochman** [comment]
I have created repo for every library. I hope its correct now.

Sources: 
* https://github.com/RobotCing/Attiny85_IO
* https://github.com/RobotCing/Attiny85_IO_basic
* https://github.com/RobotCing/Attiny84_IO
* https://github.com/RobotCing/Attiny84_IO_basic
* https://github.com/RobotCing/Atmega8_IO
* https://github.com/RobotCing/Atmega8_IO_basic
* https://github.com/RobotCing/Atmega328_IO

Tags: 
* https://github.com/RobotCing/Attiny85_IO/releases/tag/3.0.1
* https://github.com/RobotCing/Attiny85_IO_basic/releases/tag/3.0.1
* https://github.com/RobotCing/Attiny84_IO/releases/tag/3.0.1
* https://github.com/RobotCing/Attiny84_IO_basic/releases/tag/3.0.1
* https://github.com/RobotCing/Atmega8_IO/releases/tag/3.0.1
* https://github.com/RobotCing/Atmega8_IO_basic/releases/tag/3.0.1
* https://github.com/RobotCing/Atmega328_IO/releases/tag/3.0.1

Best regards
Stanislav Jochman

**Comment by StanislavJochman** [comment]
Is it ok now?

Best regards
Stanislav Jochman

**Comment by per1234** [comment]
Yes

**Comment by cmaglie** [comment]
done!
