### ISSUE TITLE
Please add the Talkie library

### ISSUE THREAD

**Issue by ArminJo** [arduino/Arduino#8356]
Hello,

I used the old Talkie sources for educational purposes and therefore refurbished it and converted it to an Arduino compatible library.
https://github.com/ArminJo/Talkie

Could you add it to your list of libraries?

Thank you.
Armin

**Comment by PaulStoffregen** [comment]
I have a fork of Talkie here.  If your's becomes the official one for the Boards Manager, and chance you'd merge the many improvements from my fork?

https://github.com/PaulStoffregen/Talkie/commits/master

**Comment by ArminJo** [comment]
Hi Paul.
I took your fork as base for my improvements, because it seemed to be best maintained, and I hope all your improvements are already contained.
The only thing is the activation of Pin5 in the examples for the amplified PROP shield in the examples, which is not standard. Can I use a compile switch for #ifdef at your boards?

I plan to include even more improvements and compatibilities to other boards in the repo, and therefore I just ordered an Arduino Due and an ESP32 board for testing  :-) .
Best regards
Armin

**Comment by PaulStoffregen** [comment]
Ah, sounds good.

**Comment by ArminJo** [comment]
OK I found a glitch.
I forgot to disable the #define MEASURE_TIMING which in turn activates pin 12 at each interrupt.
The change is commited now. I created a new tag/release, I hope this was the right way, otherwise tell me what to do.
Thanks
Armin

**Comment by per1234** [comment]
I think the most recent tag with the library.properties `version` set to 1.0.0 will be used when your library is added to the index, which would achieve your goal. I'm not certain of that because I've never seen the script that does it, only observed its behavior from the index.

After your repository is added to the index, any tag you make that does not contain a different library.properties `version` value than a previous tag, will not be picked up by the indexer.

I do think it's a bit confusing to have two tags for a 1.0.0 version in the repository.

**Comment by ArminJo** [comment]
You're right, I now found the location in Github to delete a release. It did not work with my SmartGit client before. Now there is only one release fot the 1.0.0 version, this makes it unambiguous.

**Comment by cmaglie** [comment]
Done!
