### ISSUE TITLE
[Library Manager] Please add RS485HwSerial library

### ISSUE THREAD

**Issue by sauttefk** [arduino/Arduino#8517]
Please add RS485HwSerial library

https://github.com/sauttefk/RS485HwSerial

**Comment by sauttefk** [comment]
_ping_
Is there any obstacle that hinders the inclusion of this library?

**Comment by PaulStoffregen** [comment]
Unrelated, but any chance you might consider changing the API slightly?

Two reasons:

1: Other proposals have been considered (but so far languished) by the Arduino developers for a 3rd & 4th parameter on begin(), to allow users to supply larger buffers for transmit & receive.

2: Teensy has provided this RS485 feature for years using Serial1.transmitterEnable(pin).  If you go with a separate function rather than overloading begin, and you use this same name, your library will work automatically with many RS485 projects people have made using Teensy boards.

**Comment by per1234** [comment]
>Is there any obstacle that hinders the inclusion of this library?

@sauttefk everything looks fine to me. cmaglie will add it to the Library Manager index on the next run through the outstanding requests. Thanks!

**Comment by sauttefk** [comment]
@PaulStoffregen Thanks for your comments!
I will change my library and go with your transmitterEnable proposal.

**Comment by cmaglie** [comment]
Library added to the index.
