### ISSUE TITLE
https://github.com/rleddy/tinycmdtable/tree/v1.0

### ISSUE THREAD

**Issue by rleddy** [arduino/Arduino#8521]
https://github.com/rleddy/tinycmdtable

Just a little library for a little table. Plus some short node.js tools for generating most of the sketch that uses the commands.

**Comment by per1234** [comment]
In order to be added to the Arduino Library Manager index, your library must define the `url` field in library.properties. In your repository, that field is currently blank. Please add a URL and then either create a new tag/release or else redo the existing one.

Once that's finished, please comment here so we'll know that we can proceed.

Reference:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by rleddy** [comment]
The url field has been added

**Comment by per1234** [comment]
You still need to create a release or tag with the fixed library.properties.

**Comment by rleddy** [comment]
Done

**Comment by cmaglie** [comment]
Added the library to the index.
