### ISSUE TITLE
Arduino's EEPROM memory

### ISSUE THREAD

**Issue by Sneha0707** [arduino/Arduino#8630]
http://arduino-dblib.googlecode.com/files/DB.zip
unable to download the file.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. Since the Arduino organization has no connection with the file you're trying to download, this topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to provide all the information we'll need to help you.
