### ISSUE TITLE
[Library Manger] ArduinoUniqueID

### ISSUE THREAD

**Issue by ricaun** [arduino/Arduino#8639]
Hello please add this new library!
https://github.com/ricaun/CayenneLPPDecode
and
https://github.com/ricaun/ArduinoUniqueID

**Comment by PaulStoffregen** [comment]
Maybe consider adding function to your unique ID library to query the number of bytes?  Maybe have the example get the number, rather than hard-coding the size to 8 bytes?  This could pave the way for extending it to other chips (maybe someday even non-AVR chips) with a different number of ID bytes.

**Comment by ricaun** [comment]
That's a good idea!!! 
I upgraded to library now has a UniqueIDsize hows show how many unique byte the chip has.

**Comment by cmaglie** [comment]
done!
