### ISSUE TITLE
Arduino code no longer works after a few restarts and unplugs and resets (Read)

### ISSUE THREAD

**Issue by xcakepiggie** [arduino/Arduino#8766]
Hi,

I have tried to build a simple keyboard with this code: (not written by me)

https://pastebin.com/raw/vpcCur1J

It didn't work at first until I restarted my pc. After a restart, it worked fine and I uploaded THE SAME CODE again and now all of a sudden, it doesn't work (no keys inputted but Arduino can still read HIGH and LOW)

And this time, a restart didn't work. It isn't a power issue.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do end up determining that your issue is caused by a bug in some of Arduino's code, I'll be happy to re-open this issue.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).

**Comment by xcakepiggie** [comment]
> This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do end up determining that your issue is caused by a bug in some of Arduino's code, I'll be happy to re-open this issue.
> 
> Please do this:
> 
> 1. Read http://forum.arduino.cc/index.php?topic=148850
> 2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).

the website is really slow and I can't make an account because it is too slow and has some html issues

**Comment by per1234** [comment]
@xcakepiggie I'm sorry for any inconvenience. Very rarely the Arduino Forum will be running a bit slow or having issues, but it's always fixed within a matter of hours. I'm sure you'll be able to get on if you try again.

I have been using the forum constantly over the last days and have not had any problems.

If you try again and are still having troubles, it might be an issue on your system. If you have any ad blocker or noscript types of browser extensions installed, try disabling them.
