### ISSUE TITLE
No output on serial monitor

### ISSUE THREAD

**Issue by karansoi** [arduino/Arduino#8769]
There is no output on the serial monitor.
This is the code being tested
```c++
int counter = 1;
void setup(){
  Serial.begin(9600);
}
void loop(){
  
 int i;

 for (i=0; i <  10; i++) {  // blink light while we wait for serial monitor to get turned on
    delay(1000);
    digitalWrite(13, 1);
    delay(1000);
    digitalWrite(13,0);
 }
 Serial.print("Tone generater debug.  Total tones=");
  
  
  Serial.println("Hello World");
  Serial.print("Counter = ");
  Serial.println(counter);
  delay(1000);
  counter++;
}
```
Any lead to this is appreciated in anticipation.
BTW I am using Arduino IDE 1.8.9
The board used is an Arduino clone "Richduino-UNO Basic"
perhaps the MCU needs an updated bootloader(guessing)
Regards

**Comment by per1234** [comment]
This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do end up determining that your problem is caused by a bug in Arduino's software, I'll be happy to re-open this issue.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
