### ISSUE TITLE
Having some trouble updating library for arduino managed library

### ISSUE THREAD

**Issue by s-m-t** [arduino/Arduino#8939]
Hello,
I'm having some trouble getting the arduino package manager to update my library: https://github.com/arbotics-llc/databot_arduino

Part of the problem may be that in the initial version the url field in library.properties I mistyped the url as /databot-arduino with a hyphen instead of /databot_arduino with an underscore. Could this confuse the auto updater? Another issue may be that in trying to get it to work I deleted and remade multiple releases... Thanks.

**Comment by per1234** [comment]
The reason why your 0.1.1 release was not picked up by the Library Manager indexer is because you forgot to update the `version` field of library.properties:
https://github.com/arbotics-llc/databot_arduino/blob/v0.1.1/library.properties#L2

>Part of the problem may be that in the initial version the url field in library.properties I mistyped the url as /databot-arduino with a hyphen instead of /databot_arduino with an underscore. Could this confuse the auto updater?

I don't believe so.

Although the indexer job runs hourly, it may take a couple more hours for the updated index file to propagate to all servers. I don't see anything wrong with your 0.1.2 release. I think it will just take a little more time before it becomes available for installation via Library Manager.

**Comment by s-m-t** [comment]
Ok cool, I'll check again in the morning. Thank you

**Comment by s-m-t** [comment]
It updated, looks like it may have been because I had a newline in the paragraph section of library.properties?

**Comment by per1234** [comment]
You're right! I didn't notice that.
