### ISSUE TITLE
Please add library LiquidCrystal_PCF8574

### ISSUE THREAD

**Issue by mathertel** [arduino/Arduino#8952]
Please add the new implementation of the library to the library manager:

https://github.com/mathertel/LiquidCrystal_PCF8574

Thanks.

**Comment by per1234** [comment]
Since your library is already in the Arduino Library Manager index, there is no need to submit a request for each release. The Library Manager indexer job runs hourly and scans all the repositories in the index for new releases. So your 1.2.0 release will automatically be picked up and will be available for installation via Library Manager in a matter of a few hours.
