### ISSUE TITLE
Add theme manager to ide

### ISSUE THREAD

**Issue by TomasRoj** [arduino/Arduino#9053]
it would be good to have such a theme manager in ide. When I firstly downloaded the ide I was suprised that only one theme was availibe there. @per1234 has nice ino-themes project that can be used for example. Thanks, Tom.

**Comment by per1234** [comment]
A theme manager was already added by https://github.com/arduino/Arduino/pull/7124:
![Clipboard01](https://user-images.githubusercontent.com/8572152/60978820-92c3e400-a2e6-11e9-90d9-ca8572978ceb.png)
I just haven't gotten around to updating the installation instructions in my theme repository yet for that installation option as well as the one added by https://github.com/arduino/Arduino/pull/7115.

The tricky thing about the theme installation system added in https://github.com/arduino/Arduino/pull/7124 is that you need to structure your .zip files so that the theme is in the root of the .zip file, not in a subfolder. For this reason. you can't just download the .zip files from GitHub and dump them right into the `theme` subfolder of your sketchbook folder. You need to manually create the .zip files with the correct structure.
