### ISSUE TITLE
Project from 1.6.9 will not compile in 1.8.9 on Apple

### ISSUE THREAD

**Issue by hjamestwo** [arduino/Arduino#9088]
Please read the Issues section of the Contributing Rules at the "Contributing" link to the right before submitting an issue report.

Projects written on 1.6.9 on an Apple still compile in 1.6.9 on a Linux machine, but will not compile on 1.8.9 on the Apple.using Yosemite.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there. If we do find that your problem is caused by a bug in Arduino's software, I'll be sure to reopen this.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar). Be sure to post the full error output.
