### ISSUE TITLE
[Library Manager] Please add WakeOnLan library

### ISSUE THREAD

**Issue by a7md0** [arduino/Arduino#9103]
Please add WakeOnLan library to the Library Manager index

https://github.com/a7md0/WakeOnLan

Thanks

**Comment by per1234** [comment]
Hi. I believe your request will be blocked due to the lack of the required `maintainer` field in your library.properties file. Please add the missing field and then either create a new tag/release or else redo the existing release.

Once that's done, please comment here so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

**Comment by a7md0** [comment]
Fixed

**Comment by cmaglie** [comment]
done
