### ISSUE TITLE
variable resetting loop()

### ISSUE THREAD

**Issue by borgoyn** [arduino/Arduino#9114]
I am new to Arduino but am an experienced C programmer. I have written the following simple program and am surprised at the results.

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  Serial.println("Ready...");
}

void loop() {
  // put your main code here, to run repeatedly:
  int test;
  Serial.println(test);
  test=4;
}

I would expect that the first time through that "test" would print out 0 and then print out 4 every time after that. Instead it always prints 0. It seems that the variable declaration is not a declaration but an expression that is executed every time through the loop. This seems like a bug. Any comments would be welcome.

**Comment by per1234** [comment]
Local variables are not zero initialized. When you declare a local variable, you are just assigning a memory location and the unitialized local variable will have whatever value happens to have been in memory there. So the value is undefined and you shouldn't make any assumptions about the value of an uninitialized local variable. In some cases you might find that the uninitialized variable has the value 4 on the second loop. In others you might find that it has the value 0. `test` goes out of scope every time `loop()` returns so you are creating a new local variable named `test` on every loop. It sounds like you are expecting `test` to work as it would if you had made it [static](https://www.arduino.cc/reference/en/language/variables/variable-scope--qualifiers/static/).

One thing you should be aware of is that `loop()` is a function called from the `main` function that's hidden away in the Arduino core library. For example, here is Arduino AVR Boards' `main`:
https://github.com/arduino/ArduinoCore-avr/blob/1.6.23/cores/arduino/main.cpp#L33-L51
```c++
int main(void)
{
	init();

	initVariant();

#if defined(USBCON)
	USBDevice.attach();
#endif
	
	setup();
    
	for (;;) {
		loop();
		if (serialEventRun) serialEventRun();
	}
        
	return 0;
}
```

Another thing to note is that, after [some minor preprocessing](https://github.com/arduino/Arduino/wiki/Build-Process#pre-processing), the .ino files of Arduino sketches are compiled as C++, not C. It doesn't make any difference in this case, but it's a useful thing for an experienced programmer to know.

Since this does not represent a bug, I'm going to close this. If you have any questions or observations about programming in Arduino, there are plenty of knowledgeable people on the Arduino Forum who are very happy to discuss it with you:
https://forum.arduino.cc/
