### ISSUE TITLE
[Library Manager] Please update link and name repo library LoraWAN Beelan

### ISSUE THREAD

**Issue by sabas1080** [arduino/Arduino#9141]
Please update name and link the library

https://github.com/BeelanMX/arduino-LoRaWAN

Thanks!

**Comment by cmaglie** [comment]
We are not accepting anymore submissions for libraries that have the prefix "Arduino*" in the name because we would like to reserve this namespace for our own libraries.

You've submitted the library before we introduced this rule so in theory it should not apply to your case but, since you're changing the name anyway, may I propose to change it to something like `Beelan LoraWAN` instead of `Arduino LoraWAN`? This has two advantages:

- it's immediately clear that the library is made (or is a fork made) by `Beelan`
- `Arduino` is redundant: this is a library for Arduino (the ecosystem), there is no need to add the word `Arduino` in the name!

**Comment by sabas1080** [comment]
@cmaglie thanks, ready changes

**Comment by cmaglie** [comment]
Done, sorry for the long delay.
