### ISSUE TITLE
Line of code does not give an error.

### ISSUE THREAD

**Issue by Cyberex19** [arduino/Arduino#9154]
Добрый день.
При наборе строки кода - допустил ошибку, в конце случайно добавил ,2

Строка кода
P = P * 0.7500637554192,2;
ошибку не выдает.

Good day.
When typing a line of code - made a mistake, accidentally added at the end ,2

Line of code
P = P * 0.7500637554192,2;
does not give an error.

ARDUINO 1.8.9

**Comment by per1234** [comment]
It's not an error because it is valid syntax:
https://en.cppreference.com/w/cpp/language/operator_other#Built-in_comma_operator

If you set **File > Preferences > Compiler Warnings** to "More" or "All" then you do get a warning that might serve as a helpful indicator that something is not right with that line:
```
ketch_aug19a.ino:6:28: warning: right operand of comma operator has no effect [-Wunused-value]

   P = P * 0.7500637554192,2;

                            ^
```
