### ISSUE TITLE
Add an IDE option to enable and disable optimizations

### ISSUE THREAD

**Issue by r00ster91** [arduino/Arduino#9240]
As far as I know currently the way to enable/disable optimizations for compilation is to go to `C:/Program Files (x86)/Arduino/hardware/arduino/avr/platform.txt` and edit a specific line which seems pretty hacky and inconvenient. There seems to be already `-Os` but what if I want `-O2` or `-O3` or something? I wish the flags would be customizable or just add a drop down menu to add the optimizations you want.
Also wouldn't it be better to not have `-Os` there by default when you just do some debug builds? It only unnecessarily increases compile time. Maybe you can add a debug mode and a release mode where optimizations are only enabled in the release mode.

**Comment by facchinm** [comment]
@r00ster91 `-O2` and `-O3` will make the binary size exploding; `-Os` is the standard flag for embedded since it involves both optimization and size constraint (the generated code may be slower because it doesn't unroll loops but that loops are likely to compile into fewer instructions).
Anyway, you can always create a [derived core](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#referencing-another-core-variant-or-tool) or provide a [platform.local.txt](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification#platformlocaltxt) to override the flag for your convenience, but we are not going to add a menu to choose it.
