### ISSUE TITLE
Please, add those libraries to library manager

### ISSUE THREAD

**Issue by luisllamasbinaburo** [arduino/Arduino#9271]
Hi,

Could you please those libraries to the library manager ?
(sorry, I know they are a lot!)

- [x] https://github.com/luisllamasbinaburo/Arduino-ReactiveArduino
- [x] https://github.com/luisllamasbinaburo/ArduinoLinq
- [x] https://github.com/luisllamasbinaburo/Arduino-Interpolation
- [x] https://github.com/luisllamasbinaburo/Arduino-Easing
- [x] https://github.com/luisllamasbinaburo/Arduino-SyncWaveforms
- [x] https://github.com/luisllamasbinaburo/Arduino-Parser
- [x] https://github.com/luisllamasbinaburo/Arduino-EasyComma
- [x] https://github.com/luisllamasbinaburo/Arduino-BTS7960
- [x] https://github.com/luisllamasbinaburo/Arduino-TriangleSolver
- [x] https://github.com/luisllamasbinaburo/Arduino-Storyboard
- [x] https://github.com/luisllamasbinaburo/Arduino-MultiTask
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncTask
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncTimer
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncSerial
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncServo
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncSonar
- [x] https://github.com/luisllamasbinaburo/Arduino-AsyncStepper
- [x] https://github.com/luisllamasbinaburo/Arduino-SimpleStepper

Thank you!!

**Comment by per1234** [comment]
Hi. Arduino recently started a new policy that 3rd party libraries with a library.properties `name` value starting with the word "Arduino" (or any capitalization thereof) will no longer be accepted for inclusion in the Arduino Library manager index. The reason is that Arduino wants to reserve these names for their own official libraries.

If you want your ArduinoLinq and ArduinoParser libraries to be added to the Library Manager index, you will need to change the `name` value in library properties to one that is compliant with the Arduino Library Specification:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

Then update the `version` value in library.properties and create a new release/tag, or else redo the existing release/tag.

Note that this restriction only applies to the `name` value. You are not required to rename the repository or header files.

Once you have done this, please comment here so we'll know we can proceed.

More information:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by luisllamasbinaburo** [comment]
Ok, sorry. I was not aware of this.

I have already updated both code and releases.

**Comment by cmaglie** [comment]
done
