### ISSUE TITLE
dont want to open

### ISSUE THREAD

**Issue by Macka32** [arduino/Arduino#9412]
When i open arduino ide the loading screen shows for 2 seconds and then it closes,
i tryed to reinstall it from the microsoft store, but its still crashing.Then installing from the arduino website but its the same

**Comment by matthijskooijman** [comment]
Could you try running `arduino_debug.exe` (instead of `arduino.exe`)? It should be in the same folder and might show some more information that helps to diagnose this. You might need to run it from a command prompt, though.

**Comment by Macka32** [comment]
I am using Microsoft store version of arduino ide

**Comment by per1234** [comment]
Closing because there is not enough information to enable an investigation and enough time has passed that the issue is no longer of value for tracking occurrences.

@Macka32 if you are still experiencing this issue with the latest version of the Arduino IDE, you're welcome to comment here and I'll investigate.
