### ISSUE TITLE
the arduino software is targeting a non existent directory for varification

### ISSUE THREAD

**Issue by pleashelp** [arduino/Arduino#9415]
this is the error i keep geting:
exec: "C:\\Users\\user\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++": file does not exist
its targeting a non existent directory on my pc and I have updated the software and still the same error

**Comment by facchinm** [comment]
Probably something went wrong while installing the AVR core update; this is normally due to an antivirus messing up the installation (blocking the archives extraction). You can try reinstalling AVR core while keeping the antivirus paused and it should work. 
Please reopen the issue if you still have problems, thanks!
