### ISSUE TITLE
Can't this only use C++?

### ISSUE THREAD

**Issue by deepnum** [arduino/Arduino#9420]
It would be nice if no Java is used.

**Comment by matthijskooijman** [comment]
I'm not entirely sure what you're suggesting here? Is this a suggestion to rewrite the entire IDE in C++ rather than java? That does not seem like an appropriate suggestion for this repository (and that seems unlikely to happen as well). Maybe you mean something completely different, but in that case you should be more specific about what you mean.

I'll go ahead and close this issue, since it does not seem useful right now. If you want to add more information, we can re-open later if needed.

**Comment by deepnum** [comment]
@matthijskooijman my suggestion is to rewrite the entire IDE in C++.
