### ISSUE TITLE
avr/dtostrf() depricated?

### ISSUE THREAD

**Issue by dsyleixa** [arduino/Arduino#9423]
is avr/dtostrf() depricated? https://github.com/arduino/ArduinoCore-API/tree/master/api/deprecated-avr-comp/avr
what will be there instead in future?

**Comment by cmaglie** [comment]
(I'm going to move the issue the the proper repository `arduino/ArduinoCore-API`)

Please note that you're looking to a **compatibility layer** (since a lot of old libraries uses the `avr/dtostrf.h` we added a compatibility layer because we wanted to make those old libraries compatible also with new non-AVR architectures).

Anyway the compatibility layer will **not** be removed anytime soon (unless there is a strong reason to do so) we marked it deprecated because new libraries should not use it if possible.
