### ISSUE TITLE
[Library Manager] Please add TFTLCD-Library to the library manager

### ISSUE THREAD

**Issue by dherrada** [arduino/Arduino#9436]
Please add this repository:
https://github.com/adafruit/TFTLCD-Library

**Comment by per1234** [comment]
You need to create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in your library.properties file.

After doing so, please comment here to let us know we can proceed with adding your library to the Library Manager index.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by dherrada** [comment]
@per1234 Just added the release. Should be all good now.

**Comment by dherrada** [comment]
@per1234 So sorry to bug you. It'd be really great if this could get added soon. I'm waiting on this to be added to continue with a project I've been assigned. Thanks!

**Comment by per1234** [comment]
Hi @dherrada. I don't have access to add libraries. I just label the issues so that they can be easily organized. cmaglie occasionally comes through to clear all the outstanding Library Manager inclusion requests and closes those issues when that is done. You will receive a notification from GitHub of this and your library will be available in Library Manager shortly after that. So we'll get to it soon, please be patient.

**Comment by dherrada** [comment]
@per1234 I understand. Thanks for explaining that to me.

**Comment by cmaglie** [comment]
Done, sorry for the long delay

**Comment by dherrada** [comment]
@cmaglie Thank you
