### ISSUE TITLE
[Library Manager] Add Library LibSemaforo

### ISSUE THREAD

**Issue by javisank** [arduino/Arduino#9444]
Please add https://github.com/javisank/LibSemaforo

Thanks!

**Comment by per1234** [comment]
In order to be added to the Library Manager index your library must contain a library.properties file. The format of this file is documented here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

After adding the library.properties file, you will need to create a new tag/release or redo the existing one. Make sure that the `version` value matches the tag of the release that contains it.

Once you have done this please comment here so we know we can proceed.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by javisank** [comment]
Thanks for the quick response. I must have forgotten to do the commit with the library.properties file. I have just done it. 
Is there anything else to correct?

**Comment by per1234** [comment]
@javisank everything looks good to me now. Thanks!

**Comment by cmaglie** [comment]
Done.
