### ISSUE TITLE
[Library Manager]Please add library

### ISSUE THREAD

**Issue by HANBACK-HALEY** [arduino/Arduino#9602]
Hi, please add this library to the library manager.

https://github.com/HANBACK-HALEY/Hanbackpop

Thank you.

**Comment by per1234** [comment]
In order to be added to the Library Manager index your library must contain a library.properties file. The format of this file is documented here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

After adding the library.properties file, you will need to create a new tag/release or redo the existing one. Make sure that the `version` value matches the tag of the release that contains it.

Once you have done this please comment here so we know we can proceed.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by HANBACK-HALEY** [comment]
Hi, i added library.properties file. please check and add library. thank you.

**Comment by HANBACK-HALEY** [comment]
please cancel this library. sorry.
