### ISSUE TITLE
The documentation for the Nano 33 IoT states that there is a 3.3 jumper on the bottom...

### ISSUE THREAD

**Issue by darianbjohnson** [arduino/Arduino#9775]
It's not there... which is a bit of a bummer, because I purchased this explicitly to cut the jumper and power directly with a more efficient voltage regulator.
![IMG_1490](https://user-images.githubusercontent.com/21129686/74630749-e15d1a80-5120-11ea-88b3-fd51b6fd0003.jpg)

**Comment by dushyant18033** [comment]
Isn't it possible to directly power it through the 3.3v pin by connecting your efficient voltage regulator's output 3.3v to this pin and the ground to one of the GND pins.

**Comment by darianbjohnson** [comment]
In theory that's possible... I was just expecting a jumper (since the documentation online states that there is a jumper). There's a jumper for the BLE 33 Sense....

**Comment by facchinm** [comment]
The jumper only exist in the Nano 33 BLE. @dushyant18033 do you have a link to the wrong documentation?

**Comment by dushyant18033** [comment]
![Screenshot from 2020-02-24 13-57-54](https://user-images.githubusercontent.com/54281771/75137473-b15bdb80-570d-11ea-8fbf-44fe65cf5108.png)
I believe you are talking about this jumper. Yes you're right it does exist on the original board.
If you're able to program your board using standard USB procedure then this jumper must have been permanently connected internally on the board.
I believe you don't have any other option but to power using the 3.3v pin (Not sure if it is safe to do since this document says to cut apart the jumper before applying external 3.3v But I believe that as long as you're not connecting the 5v along with this 3.3v supply, you should be good to go).

**Comment by facchinm** [comment]
Nano 33 **IoT** and Nano 33 **BLE** only share a part of the name but are different boards with different processors.
You can power the nano 33 IoT from 3.3V pin without any side effect except a slightly increaded power consumption.

**Comment by per1234** [comment]
@facchinm the incorrect information is on the "FAQ" tab of the Nano 33 IoT's product page:
https://store.arduino.cc/arduino-nano-33-iot
>- 3.3V: This pin outputs 3.3V through the on-board voltage regulator. Note: for ultra low-power functionality, **you should cut the 3V3 jumper on the back of the board**, and use an external battery at 3V3.

**Comment by per1234** [comment]
@facchinm should this be re-opened?

**Comment by SimonePDA** [comment]
I will check all the FAQs of the 33IoT. We have several items on store for this board.

**Comment by SimonePDA** [comment]
All the FAQ bullets with this mistake have been amended and the references to the ultra low power and the jumper have been deleted.
The change affects 8 different product pages.
