### ISSUE TITLE
Basic GLCD(QY-12864BG) Arduino Library

### ISSUE THREAD

**Issue by KwangryeolPark** [arduino/Arduino#9853]
Hi, I developed a library for QY_12864BG Graphic LCD.
Please add this library to the library manager.

Github URL : https://github.com/KwangryeolPark/GLCD_QY_12864BG

Thank you so much.

**Comment by per1234** [comment]
Hi @KwangryeolPark
In order to be added to the Library Manager index your library must contain a library.properties file. The format of this file is documented here:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format

After adding the library.properties file, you will need to create a new tag/release or redo the existing one. Make sure that the `version` value matches the tag of the release that contains it.

Once you have done this please comment here so we know we can proceed.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by KwangryeolPark** [comment]
Thank you for helping me.
I edit the Library file as you said me.
Please check it.
Thank you

2020년 3월 9일 (월) 오후 3:04, per1234 <notifications@github.com>님이 작성:

**Comment by per1234** [comment]
The library.properties file looks good. Now all you need to do is either redo the existing tag/release or update the `version` value in library.properties and then create a new tag/release.

**Comment by KwangryeolPark** [comment]
https://github.com/KwangryeolPark/GLCD_QY_12864BG/

**Comment by cmaglie** [comment]
Done.
