### ISSUE TITLE
problem with pow() and any loop

### ISSUE THREAD

**Issue by aghfars** [arduino/Arduino#9909]
hi i found a problem with pow() in loop and this picture explain that.
![Annotation 2020-03-24 001447](https://user-images.githubusercontent.com/24976773/77356881-cce5f080-6d64-11ea-9f7a-9c56eb3014a0.jpg)

**Comment by PaulStoffregen** [comment]
You're truncating when you should be rounding.  Add 0.5 before truncating to integer.  Or use round().

**Comment by aghfars** [comment]
This problem only exists in loops.
![Annotation 2020-03-25 025305](https://user-images.githubusercontent.com/24976773/77482568-d8f4af80-6e43-11ea-8c7c-18e9955ae79c.jpg)

and i make my own function to fix this and its work.
Why should I use round () and increase the size of the program?
Why do you refuse to fix this problem?

![Annotation 2020-03-25 025937](https://user-images.githubusercontent.com/24976773/77483159-1ad22580-6e45-11ea-9970-224f45fcabd7.jpg)

**Comment by per1234** [comment]
@aghfars I think if you run this sketch the situation will be clear:
```c++
void setup()
{
  Serial.begin(9600);
  int i = 4;
  while (i >= 0)
  {
    double POW = pow(10, i);
    Serial.println(POW, 6);
    i--;
  }
}

void loop()
{}
```
The output will look something like this:
```
9999.998046
999.999816
99.999992
10.000000
1.000000
```
[`pow()` returns a `double`](https://www.arduino.cc/reference/en/language/functions/math/pow/). Floating point numbers are not exact. When you convert 9999.998046 to an `int` it is truncated to 9999. This is why you need to use `round()`.

This is not a bug. It is confusing, but this is just the way it works. The result is influenced by the compiler optimizations, which is why you get a different result without the code that doesn't have the `while` loop. Your `Pow` function returns an `int`, so it doesn't introduce the floating point issue.

I think Arduino's documentation does an OK job of explaining this situation. The return type of `pow()` is documented. We mention the the inexact nature of floating point numbers and truncation in the [`float` reference page](https://www.arduino.cc/reference/en/language/variables/data-types/float/), as well as the solutions. I guess it is problematic that if you check the `pow()` reference page, then the `double` reference page, you would not see the information on the `float` reference page.

**Comment by aghfars** [comment]
I re-wrote the function, but with double and no problems in the loop.

![Annotation 2020-03-25 134729](https://user-images.githubusercontent.com/24976773/77520875-78935b80-6e9f-11ea-978a-ab9077871d48.jpg)
