### ISSUE TITLE
Partition the board memory virtually and utilize only a section

### ISSUE THREAD

**Issue by aRbhaSun20** [arduino/Arduino#9969]
[possible_bugs_in_arduino.docx](https://github.com/arduino/Arduino/files/4402101/possible_bugs_in_arduino.docx)

EDIT - full text from above file:
>I am working with Arduino for past three years and having used multiple boards for indutrial to iot based lilypad and even edison and galelio but found a common error:
>
>The high end board once the basic firmware is loaded and entire board can’t be used for a different purpose even though the entire boards configuration is not used completion,
>
>solution : 
the possible solution may be if we can partition the board memory virtually and utilize only a section of board hence multiple programs and be run
>
>I am working with Arduino with Linux as a Background where for serial communication and loading the firmata on the board makes the board used for only one purpose as the length of the wire is limited but possible solution is ther for wireless but produces a lot of latency to connect, pair, and interchange data.

**Comment by matthijskooijman** [comment]
Thanks for your contribution. However, putting your content in an attachment like that is not really ideal, since it makes it harder to participate in this discussion. Also, your issue summary is really generic. Maybe you could put the issue itself in the issue text and update the summary line to be more specific about the issue you are adressing? I had a look at the document and from that it is not immediately clear to me what the issue is exactly, so you might want to also add a bit more detail and maybe an example to clarify.

**Comment by per1234** [comment]
Closing due to lack of response.

@aRbhaSun20, if you'll provide the requested information I'll be happy to re-open this issue.
