### ISSUE TITLE
MKR1000 Arduino Cloud Crypto Issue

### ISSUE THREAD

**Issue by ncohen17** [arduino/Arduino#9984]
Hello, 

I just purchased from from RS Components an MKR1000 Wi-Fi. When trying to connect it to the Arduino IoT cloud I go through the setup to configure the Crypto chip. After a few minutes I get this message:
We weren't able to configure the Crypto Chip. Timeout reached before we could configure your board.
Please try again. If this problem persists, you may write us on the Forum.
I have tried multiple times to set it up and the issue doesn't change. 
I have also tried with the MKR1010 and it works right away. 
In addition, I have tried to install and reinstall the Arduino Create plugin but it doesn't seem to help. 

Please if someone can help me solve this issue weather it is a software or a hardware issue.

**Comment by per1234** [comment]
Hi @ncohen17. I'm sorry to hear you're having a problem using the Arduino IoT Cloud.

I'm closing this issue because the correct place to request support or report issues related to the Arduino IoT Cloud is the Arduino forum's **Create > IoT Cloud Beta** board:
http://forum.arduino.cc/index.php?board=128.0

I see you've already made a post there and are getting assistance:
https://forum.arduino.cc/index.php?topic=674840
